Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    HiddenLayer1:
      Precision:
        bias: fixed<18,4>
        result: fixed<18,4>
        weight: fixed<18,4>
      Trace: false
    HiddenLayer1_relu:
      Precision:
        result: fixed<18,4>
      Trace: false
    HiddenLayer2:
      Precision:
        bias: fixed<18,4>
        result: fixed<18,4>
        weight: fixed<18,4>
      Trace: false
    HiddenLayer2_relu:
      Precision:
        result: fixed<18,4>
      Trace: false
    OuputLayer:
      Precision:
        bias: fixed<18,4>
        result: fixed<18,4>
        weight: fixed<18,4>
      Trace: false
    OuputLayer_sigmoid:
      Precision:
        result: fixed<18,4>
      Trace: false
    input_2:
      Precision:
        result: fixed<32,32>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<18,4>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: ../Data/x_test.npy
KerasModel: !keras_model '../tmp/lbnl/keras_model.h5'
OutputDir: ../tmp/lbnl
OutputPredictions: ../Data/y_test.npy
Part: xc7vx485tffg1761-2
ProjectName: myproject
Stamp: f8B5F8D3
