// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s (
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        data_20_V_read,
        data_21_V_read,
        data_22_V_read,
        data_23_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_27_V_read,
        data_28_V_read,
        data_29_V_read,
        data_30_V_read,
        data_31_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31
);


output   ap_ready;
input  [15:0] data_0_V_read;
input  [15:0] data_1_V_read;
input  [15:0] data_2_V_read;
input  [15:0] data_3_V_read;
input  [15:0] data_4_V_read;
input  [15:0] data_5_V_read;
input  [15:0] data_6_V_read;
input  [15:0] data_7_V_read;
input  [15:0] data_8_V_read;
input  [15:0] data_9_V_read;
input  [15:0] data_10_V_read;
input  [15:0] data_11_V_read;
input  [15:0] data_12_V_read;
input  [15:0] data_13_V_read;
input  [15:0] data_14_V_read;
input  [15:0] data_15_V_read;
input  [15:0] data_16_V_read;
input  [15:0] data_17_V_read;
input  [15:0] data_18_V_read;
input  [15:0] data_19_V_read;
input  [15:0] data_20_V_read;
input  [15:0] data_21_V_read;
input  [15:0] data_22_V_read;
input  [15:0] data_23_V_read;
input  [15:0] data_24_V_read;
input  [15:0] data_25_V_read;
input  [15:0] data_26_V_read;
input  [15:0] data_27_V_read;
input  [15:0] data_28_V_read;
input  [15:0] data_29_V_read;
input  [15:0] data_30_V_read;
input  [15:0] data_31_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;

wire   [0:0] tmp_2_fu_274_p2;
wire   [14:0] tmp_fu_280_p1;
wire   [14:0] res_0_V_write_assign_fu_284_p3;
wire   [0:0] tmp_2_1_fu_296_p2;
wire   [14:0] tmp_22_fu_302_p1;
wire   [14:0] res_1_V_write_assign_fu_306_p3;
wire   [0:0] tmp_2_2_fu_318_p2;
wire   [14:0] tmp_23_fu_324_p1;
wire   [14:0] res_2_V_write_assign_fu_328_p3;
wire   [0:0] tmp_2_3_fu_340_p2;
wire   [14:0] tmp_24_fu_346_p1;
wire   [14:0] res_3_V_write_assign_fu_350_p3;
wire   [0:0] tmp_2_4_fu_362_p2;
wire   [14:0] tmp_25_fu_368_p1;
wire   [14:0] res_4_V_write_assign_fu_372_p3;
wire   [0:0] tmp_2_5_fu_384_p2;
wire   [14:0] tmp_26_fu_390_p1;
wire   [14:0] res_5_V_write_assign_fu_394_p3;
wire   [0:0] tmp_2_6_fu_406_p2;
wire   [14:0] tmp_27_fu_412_p1;
wire   [14:0] res_6_V_write_assign_fu_416_p3;
wire   [0:0] tmp_2_7_fu_428_p2;
wire   [14:0] tmp_28_fu_434_p1;
wire   [14:0] res_7_V_write_assign_fu_438_p3;
wire   [0:0] tmp_2_8_fu_450_p2;
wire   [14:0] tmp_29_fu_456_p1;
wire   [14:0] res_8_V_write_assign_fu_460_p3;
wire   [0:0] tmp_2_9_fu_472_p2;
wire   [14:0] tmp_30_fu_478_p1;
wire   [14:0] res_9_V_write_assign_fu_482_p3;
wire   [0:0] tmp_2_s_fu_494_p2;
wire   [14:0] tmp_31_fu_500_p1;
wire   [14:0] res_10_V_write_assign_fu_504_p3;
wire   [0:0] tmp_2_10_fu_516_p2;
wire   [14:0] tmp_32_fu_522_p1;
wire   [14:0] res_11_V_write_assign_fu_526_p3;
wire   [0:0] tmp_2_11_fu_538_p2;
wire   [14:0] tmp_33_fu_544_p1;
wire   [14:0] res_12_V_write_assign_fu_548_p3;
wire   [0:0] tmp_2_12_fu_560_p2;
wire   [14:0] tmp_34_fu_566_p1;
wire   [14:0] res_13_V_write_assign_fu_570_p3;
wire   [0:0] tmp_2_13_fu_582_p2;
wire   [14:0] tmp_35_fu_588_p1;
wire   [14:0] res_14_V_write_assign_fu_592_p3;
wire   [0:0] tmp_2_14_fu_604_p2;
wire   [14:0] tmp_36_fu_610_p1;
wire   [14:0] res_15_V_write_assign_fu_614_p3;
wire   [0:0] tmp_2_15_fu_626_p2;
wire   [14:0] tmp_37_fu_632_p1;
wire   [14:0] res_16_V_write_assign_fu_636_p3;
wire   [0:0] tmp_2_16_fu_648_p2;
wire   [14:0] tmp_38_fu_654_p1;
wire   [14:0] res_17_V_write_assign_fu_658_p3;
wire   [0:0] tmp_2_17_fu_670_p2;
wire   [14:0] tmp_39_fu_676_p1;
wire   [14:0] res_18_V_write_assign_fu_680_p3;
wire   [0:0] tmp_2_18_fu_692_p2;
wire   [14:0] tmp_40_fu_698_p1;
wire   [14:0] res_19_V_write_assign_fu_702_p3;
wire   [0:0] tmp_2_19_fu_714_p2;
wire   [14:0] tmp_41_fu_720_p1;
wire   [14:0] res_20_V_write_assign_fu_724_p3;
wire   [0:0] tmp_2_20_fu_736_p2;
wire   [14:0] tmp_42_fu_742_p1;
wire   [14:0] res_21_V_write_assign_fu_746_p3;
wire   [0:0] tmp_2_21_fu_758_p2;
wire   [14:0] tmp_43_fu_764_p1;
wire   [14:0] res_22_V_write_assign_fu_768_p3;
wire   [0:0] tmp_2_22_fu_780_p2;
wire   [14:0] tmp_44_fu_786_p1;
wire   [14:0] res_23_V_write_assign_fu_790_p3;
wire   [0:0] tmp_2_23_fu_802_p2;
wire   [14:0] tmp_45_fu_808_p1;
wire   [14:0] res_24_V_write_assign_fu_812_p3;
wire   [0:0] tmp_2_24_fu_824_p2;
wire   [14:0] tmp_46_fu_830_p1;
wire   [14:0] res_25_V_write_assign_fu_834_p3;
wire   [0:0] tmp_2_25_fu_846_p2;
wire   [14:0] tmp_47_fu_852_p1;
wire   [14:0] res_26_V_write_assign_fu_856_p3;
wire   [0:0] tmp_2_26_fu_868_p2;
wire   [14:0] tmp_48_fu_874_p1;
wire   [14:0] res_27_V_write_assign_fu_878_p3;
wire   [0:0] tmp_2_27_fu_890_p2;
wire   [14:0] tmp_49_fu_896_p1;
wire   [14:0] res_28_V_write_assign_fu_900_p3;
wire   [0:0] tmp_2_28_fu_912_p2;
wire   [14:0] tmp_50_fu_918_p1;
wire   [14:0] res_29_V_write_assign_fu_922_p3;
wire   [0:0] tmp_2_29_fu_934_p2;
wire   [14:0] tmp_51_fu_940_p1;
wire   [14:0] res_30_V_write_assign_fu_944_p3;
wire   [0:0] tmp_2_30_fu_956_p2;
wire   [14:0] tmp_52_fu_962_p1;
wire   [14:0] res_31_V_write_assign_fu_966_p3;
wire   [15:0] res_0_V_write_assign_cast_fu_292_p1;
wire   [15:0] res_1_V_write_assign_cast_fu_314_p1;
wire   [15:0] res_2_V_write_assign_cast_fu_336_p1;
wire   [15:0] res_3_V_write_assign_cast_fu_358_p1;
wire   [15:0] res_4_V_write_assign_cast_fu_380_p1;
wire   [15:0] res_5_V_write_assign_cast_fu_402_p1;
wire   [15:0] res_6_V_write_assign_cast_fu_424_p1;
wire   [15:0] res_7_V_write_assign_cast_fu_446_p1;
wire   [15:0] res_8_V_write_assign_cast_fu_468_p1;
wire   [15:0] res_9_V_write_assign_cast_fu_490_p1;
wire   [15:0] res_10_V_write_assign_cast_fu_512_p1;
wire   [15:0] res_11_V_write_assign_cast_fu_534_p1;
wire   [15:0] res_12_V_write_assign_cast_fu_556_p1;
wire   [15:0] res_13_V_write_assign_cast_fu_578_p1;
wire   [15:0] res_14_V_write_assign_cast_fu_600_p1;
wire   [15:0] res_15_V_write_assign_cast_fu_622_p1;
wire   [15:0] res_16_V_write_assign_cast_fu_644_p1;
wire   [15:0] res_17_V_write_assign_cast_fu_666_p1;
wire   [15:0] res_18_V_write_assign_cast_fu_688_p1;
wire   [15:0] res_19_V_write_assign_cast_fu_710_p1;
wire   [15:0] res_20_V_write_assign_cast_fu_732_p1;
wire   [15:0] res_21_V_write_assign_cast_fu_754_p1;
wire   [15:0] res_22_V_write_assign_cast_fu_776_p1;
wire   [15:0] res_23_V_write_assign_cast_fu_798_p1;
wire   [15:0] res_24_V_write_assign_cast_fu_820_p1;
wire   [15:0] res_25_V_write_assign_cast_fu_842_p1;
wire   [15:0] res_26_V_write_assign_cast_fu_864_p1;
wire   [15:0] res_27_V_write_assign_cast_fu_886_p1;
wire   [15:0] res_28_V_write_assign_cast_fu_908_p1;
wire   [15:0] res_29_V_write_assign_cast_fu_930_p1;
wire   [15:0] res_30_V_write_assign_cast_fu_952_p1;
wire   [15:0] res_31_V_write_assign_cast_fu_974_p1;

assign ap_ready = 1'b1;

assign ap_return_0 = res_0_V_write_assign_cast_fu_292_p1;

assign ap_return_1 = res_1_V_write_assign_cast_fu_314_p1;

assign ap_return_10 = res_10_V_write_assign_cast_fu_512_p1;

assign ap_return_11 = res_11_V_write_assign_cast_fu_534_p1;

assign ap_return_12 = res_12_V_write_assign_cast_fu_556_p1;

assign ap_return_13 = res_13_V_write_assign_cast_fu_578_p1;

assign ap_return_14 = res_14_V_write_assign_cast_fu_600_p1;

assign ap_return_15 = res_15_V_write_assign_cast_fu_622_p1;

assign ap_return_16 = res_16_V_write_assign_cast_fu_644_p1;

assign ap_return_17 = res_17_V_write_assign_cast_fu_666_p1;

assign ap_return_18 = res_18_V_write_assign_cast_fu_688_p1;

assign ap_return_19 = res_19_V_write_assign_cast_fu_710_p1;

assign ap_return_2 = res_2_V_write_assign_cast_fu_336_p1;

assign ap_return_20 = res_20_V_write_assign_cast_fu_732_p1;

assign ap_return_21 = res_21_V_write_assign_cast_fu_754_p1;

assign ap_return_22 = res_22_V_write_assign_cast_fu_776_p1;

assign ap_return_23 = res_23_V_write_assign_cast_fu_798_p1;

assign ap_return_24 = res_24_V_write_assign_cast_fu_820_p1;

assign ap_return_25 = res_25_V_write_assign_cast_fu_842_p1;

assign ap_return_26 = res_26_V_write_assign_cast_fu_864_p1;

assign ap_return_27 = res_27_V_write_assign_cast_fu_886_p1;

assign ap_return_28 = res_28_V_write_assign_cast_fu_908_p1;

assign ap_return_29 = res_29_V_write_assign_cast_fu_930_p1;

assign ap_return_3 = res_3_V_write_assign_cast_fu_358_p1;

assign ap_return_30 = res_30_V_write_assign_cast_fu_952_p1;

assign ap_return_31 = res_31_V_write_assign_cast_fu_974_p1;

assign ap_return_4 = res_4_V_write_assign_cast_fu_380_p1;

assign ap_return_5 = res_5_V_write_assign_cast_fu_402_p1;

assign ap_return_6 = res_6_V_write_assign_cast_fu_424_p1;

assign ap_return_7 = res_7_V_write_assign_cast_fu_446_p1;

assign ap_return_8 = res_8_V_write_assign_cast_fu_468_p1;

assign ap_return_9 = res_9_V_write_assign_cast_fu_490_p1;

assign res_0_V_write_assign_cast_fu_292_p1 = res_0_V_write_assign_fu_284_p3;

assign res_0_V_write_assign_fu_284_p3 = ((tmp_2_fu_274_p2[0:0] === 1'b1) ? tmp_fu_280_p1 : 15'd0);

assign res_10_V_write_assign_cast_fu_512_p1 = res_10_V_write_assign_fu_504_p3;

assign res_10_V_write_assign_fu_504_p3 = ((tmp_2_s_fu_494_p2[0:0] === 1'b1) ? tmp_31_fu_500_p1 : 15'd0);

assign res_11_V_write_assign_cast_fu_534_p1 = res_11_V_write_assign_fu_526_p3;

assign res_11_V_write_assign_fu_526_p3 = ((tmp_2_10_fu_516_p2[0:0] === 1'b1) ? tmp_32_fu_522_p1 : 15'd0);

assign res_12_V_write_assign_cast_fu_556_p1 = res_12_V_write_assign_fu_548_p3;

assign res_12_V_write_assign_fu_548_p3 = ((tmp_2_11_fu_538_p2[0:0] === 1'b1) ? tmp_33_fu_544_p1 : 15'd0);

assign res_13_V_write_assign_cast_fu_578_p1 = res_13_V_write_assign_fu_570_p3;

assign res_13_V_write_assign_fu_570_p3 = ((tmp_2_12_fu_560_p2[0:0] === 1'b1) ? tmp_34_fu_566_p1 : 15'd0);

assign res_14_V_write_assign_cast_fu_600_p1 = res_14_V_write_assign_fu_592_p3;

assign res_14_V_write_assign_fu_592_p3 = ((tmp_2_13_fu_582_p2[0:0] === 1'b1) ? tmp_35_fu_588_p1 : 15'd0);

assign res_15_V_write_assign_cast_fu_622_p1 = res_15_V_write_assign_fu_614_p3;

assign res_15_V_write_assign_fu_614_p3 = ((tmp_2_14_fu_604_p2[0:0] === 1'b1) ? tmp_36_fu_610_p1 : 15'd0);

assign res_16_V_write_assign_cast_fu_644_p1 = res_16_V_write_assign_fu_636_p3;

assign res_16_V_write_assign_fu_636_p3 = ((tmp_2_15_fu_626_p2[0:0] === 1'b1) ? tmp_37_fu_632_p1 : 15'd0);

assign res_17_V_write_assign_cast_fu_666_p1 = res_17_V_write_assign_fu_658_p3;

assign res_17_V_write_assign_fu_658_p3 = ((tmp_2_16_fu_648_p2[0:0] === 1'b1) ? tmp_38_fu_654_p1 : 15'd0);

assign res_18_V_write_assign_cast_fu_688_p1 = res_18_V_write_assign_fu_680_p3;

assign res_18_V_write_assign_fu_680_p3 = ((tmp_2_17_fu_670_p2[0:0] === 1'b1) ? tmp_39_fu_676_p1 : 15'd0);

assign res_19_V_write_assign_cast_fu_710_p1 = res_19_V_write_assign_fu_702_p3;

assign res_19_V_write_assign_fu_702_p3 = ((tmp_2_18_fu_692_p2[0:0] === 1'b1) ? tmp_40_fu_698_p1 : 15'd0);

assign res_1_V_write_assign_cast_fu_314_p1 = res_1_V_write_assign_fu_306_p3;

assign res_1_V_write_assign_fu_306_p3 = ((tmp_2_1_fu_296_p2[0:0] === 1'b1) ? tmp_22_fu_302_p1 : 15'd0);

assign res_20_V_write_assign_cast_fu_732_p1 = res_20_V_write_assign_fu_724_p3;

assign res_20_V_write_assign_fu_724_p3 = ((tmp_2_19_fu_714_p2[0:0] === 1'b1) ? tmp_41_fu_720_p1 : 15'd0);

assign res_21_V_write_assign_cast_fu_754_p1 = res_21_V_write_assign_fu_746_p3;

assign res_21_V_write_assign_fu_746_p3 = ((tmp_2_20_fu_736_p2[0:0] === 1'b1) ? tmp_42_fu_742_p1 : 15'd0);

assign res_22_V_write_assign_cast_fu_776_p1 = res_22_V_write_assign_fu_768_p3;

assign res_22_V_write_assign_fu_768_p3 = ((tmp_2_21_fu_758_p2[0:0] === 1'b1) ? tmp_43_fu_764_p1 : 15'd0);

assign res_23_V_write_assign_cast_fu_798_p1 = res_23_V_write_assign_fu_790_p3;

assign res_23_V_write_assign_fu_790_p3 = ((tmp_2_22_fu_780_p2[0:0] === 1'b1) ? tmp_44_fu_786_p1 : 15'd0);

assign res_24_V_write_assign_cast_fu_820_p1 = res_24_V_write_assign_fu_812_p3;

assign res_24_V_write_assign_fu_812_p3 = ((tmp_2_23_fu_802_p2[0:0] === 1'b1) ? tmp_45_fu_808_p1 : 15'd0);

assign res_25_V_write_assign_cast_fu_842_p1 = res_25_V_write_assign_fu_834_p3;

assign res_25_V_write_assign_fu_834_p3 = ((tmp_2_24_fu_824_p2[0:0] === 1'b1) ? tmp_46_fu_830_p1 : 15'd0);

assign res_26_V_write_assign_cast_fu_864_p1 = res_26_V_write_assign_fu_856_p3;

assign res_26_V_write_assign_fu_856_p3 = ((tmp_2_25_fu_846_p2[0:0] === 1'b1) ? tmp_47_fu_852_p1 : 15'd0);

assign res_27_V_write_assign_cast_fu_886_p1 = res_27_V_write_assign_fu_878_p3;

assign res_27_V_write_assign_fu_878_p3 = ((tmp_2_26_fu_868_p2[0:0] === 1'b1) ? tmp_48_fu_874_p1 : 15'd0);

assign res_28_V_write_assign_cast_fu_908_p1 = res_28_V_write_assign_fu_900_p3;

assign res_28_V_write_assign_fu_900_p3 = ((tmp_2_27_fu_890_p2[0:0] === 1'b1) ? tmp_49_fu_896_p1 : 15'd0);

assign res_29_V_write_assign_cast_fu_930_p1 = res_29_V_write_assign_fu_922_p3;

assign res_29_V_write_assign_fu_922_p3 = ((tmp_2_28_fu_912_p2[0:0] === 1'b1) ? tmp_50_fu_918_p1 : 15'd0);

assign res_2_V_write_assign_cast_fu_336_p1 = res_2_V_write_assign_fu_328_p3;

assign res_2_V_write_assign_fu_328_p3 = ((tmp_2_2_fu_318_p2[0:0] === 1'b1) ? tmp_23_fu_324_p1 : 15'd0);

assign res_30_V_write_assign_cast_fu_952_p1 = res_30_V_write_assign_fu_944_p3;

assign res_30_V_write_assign_fu_944_p3 = ((tmp_2_29_fu_934_p2[0:0] === 1'b1) ? tmp_51_fu_940_p1 : 15'd0);

assign res_31_V_write_assign_cast_fu_974_p1 = res_31_V_write_assign_fu_966_p3;

assign res_31_V_write_assign_fu_966_p3 = ((tmp_2_30_fu_956_p2[0:0] === 1'b1) ? tmp_52_fu_962_p1 : 15'd0);

assign res_3_V_write_assign_cast_fu_358_p1 = res_3_V_write_assign_fu_350_p3;

assign res_3_V_write_assign_fu_350_p3 = ((tmp_2_3_fu_340_p2[0:0] === 1'b1) ? tmp_24_fu_346_p1 : 15'd0);

assign res_4_V_write_assign_cast_fu_380_p1 = res_4_V_write_assign_fu_372_p3;

assign res_4_V_write_assign_fu_372_p3 = ((tmp_2_4_fu_362_p2[0:0] === 1'b1) ? tmp_25_fu_368_p1 : 15'd0);

assign res_5_V_write_assign_cast_fu_402_p1 = res_5_V_write_assign_fu_394_p3;

assign res_5_V_write_assign_fu_394_p3 = ((tmp_2_5_fu_384_p2[0:0] === 1'b1) ? tmp_26_fu_390_p1 : 15'd0);

assign res_6_V_write_assign_cast_fu_424_p1 = res_6_V_write_assign_fu_416_p3;

assign res_6_V_write_assign_fu_416_p3 = ((tmp_2_6_fu_406_p2[0:0] === 1'b1) ? tmp_27_fu_412_p1 : 15'd0);

assign res_7_V_write_assign_cast_fu_446_p1 = res_7_V_write_assign_fu_438_p3;

assign res_7_V_write_assign_fu_438_p3 = ((tmp_2_7_fu_428_p2[0:0] === 1'b1) ? tmp_28_fu_434_p1 : 15'd0);

assign res_8_V_write_assign_cast_fu_468_p1 = res_8_V_write_assign_fu_460_p3;

assign res_8_V_write_assign_fu_460_p3 = ((tmp_2_8_fu_450_p2[0:0] === 1'b1) ? tmp_29_fu_456_p1 : 15'd0);

assign res_9_V_write_assign_cast_fu_490_p1 = res_9_V_write_assign_fu_482_p3;

assign res_9_V_write_assign_fu_482_p3 = ((tmp_2_9_fu_472_p2[0:0] === 1'b1) ? tmp_30_fu_478_p1 : 15'd0);

assign tmp_22_fu_302_p1 = data_1_V_read[14:0];

assign tmp_23_fu_324_p1 = data_2_V_read[14:0];

assign tmp_24_fu_346_p1 = data_3_V_read[14:0];

assign tmp_25_fu_368_p1 = data_4_V_read[14:0];

assign tmp_26_fu_390_p1 = data_5_V_read[14:0];

assign tmp_27_fu_412_p1 = data_6_V_read[14:0];

assign tmp_28_fu_434_p1 = data_7_V_read[14:0];

assign tmp_29_fu_456_p1 = data_8_V_read[14:0];

assign tmp_2_10_fu_516_p2 = (($signed(data_11_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_11_fu_538_p2 = (($signed(data_12_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_12_fu_560_p2 = (($signed(data_13_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_13_fu_582_p2 = (($signed(data_14_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_14_fu_604_p2 = (($signed(data_15_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_15_fu_626_p2 = (($signed(data_16_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_16_fu_648_p2 = (($signed(data_17_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_17_fu_670_p2 = (($signed(data_18_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_18_fu_692_p2 = (($signed(data_19_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_19_fu_714_p2 = (($signed(data_20_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_1_fu_296_p2 = (($signed(data_1_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_20_fu_736_p2 = (($signed(data_21_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_21_fu_758_p2 = (($signed(data_22_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_22_fu_780_p2 = (($signed(data_23_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_23_fu_802_p2 = (($signed(data_24_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_24_fu_824_p2 = (($signed(data_25_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_25_fu_846_p2 = (($signed(data_26_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_26_fu_868_p2 = (($signed(data_27_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_27_fu_890_p2 = (($signed(data_28_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_28_fu_912_p2 = (($signed(data_29_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_29_fu_934_p2 = (($signed(data_30_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_2_fu_318_p2 = (($signed(data_2_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_30_fu_956_p2 = (($signed(data_31_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_3_fu_340_p2 = (($signed(data_3_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_4_fu_362_p2 = (($signed(data_4_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_5_fu_384_p2 = (($signed(data_5_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_6_fu_406_p2 = (($signed(data_6_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_7_fu_428_p2 = (($signed(data_7_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_8_fu_450_p2 = (($signed(data_8_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_9_fu_472_p2 = (($signed(data_9_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_fu_274_p2 = (($signed(data_0_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_2_s_fu_494_p2 = (($signed(data_10_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign tmp_30_fu_478_p1 = data_9_V_read[14:0];

assign tmp_31_fu_500_p1 = data_10_V_read[14:0];

assign tmp_32_fu_522_p1 = data_11_V_read[14:0];

assign tmp_33_fu_544_p1 = data_12_V_read[14:0];

assign tmp_34_fu_566_p1 = data_13_V_read[14:0];

assign tmp_35_fu_588_p1 = data_14_V_read[14:0];

assign tmp_36_fu_610_p1 = data_15_V_read[14:0];

assign tmp_37_fu_632_p1 = data_16_V_read[14:0];

assign tmp_38_fu_654_p1 = data_17_V_read[14:0];

assign tmp_39_fu_676_p1 = data_18_V_read[14:0];

assign tmp_40_fu_698_p1 = data_19_V_read[14:0];

assign tmp_41_fu_720_p1 = data_20_V_read[14:0];

assign tmp_42_fu_742_p1 = data_21_V_read[14:0];

assign tmp_43_fu_764_p1 = data_22_V_read[14:0];

assign tmp_44_fu_786_p1 = data_23_V_read[14:0];

assign tmp_45_fu_808_p1 = data_24_V_read[14:0];

assign tmp_46_fu_830_p1 = data_25_V_read[14:0];

assign tmp_47_fu_852_p1 = data_26_V_read[14:0];

assign tmp_48_fu_874_p1 = data_27_V_read[14:0];

assign tmp_49_fu_896_p1 = data_28_V_read[14:0];

assign tmp_50_fu_918_p1 = data_29_V_read[14:0];

assign tmp_51_fu_940_p1 = data_30_V_read[14:0];

assign tmp_52_fu_962_p1 = data_31_V_read[14:0];

assign tmp_fu_280_p1 = data_0_V_read[14:0];

endmodule //relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s
