// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::ap_const_logic_1 = sc_dt::Log_1;
const bool relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::ap_const_boolean_1 = true;
const sc_lv<16> relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::ap_const_lv16_0 = "0000000000000000";
const sc_lv<15> relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::ap_const_lv15_0 = "000000000000000";
const sc_logic relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::ap_const_logic_0 = sc_dt::Log_0;

relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( res_0_V_write_assign_cast_fu_292_p1 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( res_1_V_write_assign_cast_fu_314_p1 );

    SC_METHOD(thread_ap_return_10);
    sensitive << ( res_10_V_write_assign_cast_fu_512_p1 );

    SC_METHOD(thread_ap_return_11);
    sensitive << ( res_11_V_write_assign_cast_fu_534_p1 );

    SC_METHOD(thread_ap_return_12);
    sensitive << ( res_12_V_write_assign_cast_fu_556_p1 );

    SC_METHOD(thread_ap_return_13);
    sensitive << ( res_13_V_write_assign_cast_fu_578_p1 );

    SC_METHOD(thread_ap_return_14);
    sensitive << ( res_14_V_write_assign_cast_fu_600_p1 );

    SC_METHOD(thread_ap_return_15);
    sensitive << ( res_15_V_write_assign_cast_fu_622_p1 );

    SC_METHOD(thread_ap_return_16);
    sensitive << ( res_16_V_write_assign_cast_fu_644_p1 );

    SC_METHOD(thread_ap_return_17);
    sensitive << ( res_17_V_write_assign_cast_fu_666_p1 );

    SC_METHOD(thread_ap_return_18);
    sensitive << ( res_18_V_write_assign_cast_fu_688_p1 );

    SC_METHOD(thread_ap_return_19);
    sensitive << ( res_19_V_write_assign_cast_fu_710_p1 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( res_2_V_write_assign_cast_fu_336_p1 );

    SC_METHOD(thread_ap_return_20);
    sensitive << ( res_20_V_write_assign_cast_fu_732_p1 );

    SC_METHOD(thread_ap_return_21);
    sensitive << ( res_21_V_write_assign_cast_fu_754_p1 );

    SC_METHOD(thread_ap_return_22);
    sensitive << ( res_22_V_write_assign_cast_fu_776_p1 );

    SC_METHOD(thread_ap_return_23);
    sensitive << ( res_23_V_write_assign_cast_fu_798_p1 );

    SC_METHOD(thread_ap_return_24);
    sensitive << ( res_24_V_write_assign_cast_fu_820_p1 );

    SC_METHOD(thread_ap_return_25);
    sensitive << ( res_25_V_write_assign_cast_fu_842_p1 );

    SC_METHOD(thread_ap_return_26);
    sensitive << ( res_26_V_write_assign_cast_fu_864_p1 );

    SC_METHOD(thread_ap_return_27);
    sensitive << ( res_27_V_write_assign_cast_fu_886_p1 );

    SC_METHOD(thread_ap_return_28);
    sensitive << ( res_28_V_write_assign_cast_fu_908_p1 );

    SC_METHOD(thread_ap_return_29);
    sensitive << ( res_29_V_write_assign_cast_fu_930_p1 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( res_3_V_write_assign_cast_fu_358_p1 );

    SC_METHOD(thread_ap_return_30);
    sensitive << ( res_30_V_write_assign_cast_fu_952_p1 );

    SC_METHOD(thread_ap_return_31);
    sensitive << ( res_31_V_write_assign_cast_fu_974_p1 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( res_4_V_write_assign_cast_fu_380_p1 );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( res_5_V_write_assign_cast_fu_402_p1 );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( res_6_V_write_assign_cast_fu_424_p1 );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( res_7_V_write_assign_cast_fu_446_p1 );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( res_8_V_write_assign_cast_fu_468_p1 );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( res_9_V_write_assign_cast_fu_490_p1 );

    SC_METHOD(thread_res_0_V_write_assign_cast_fu_292_p1);
    sensitive << ( res_0_V_write_assign_fu_284_p3 );

    SC_METHOD(thread_res_0_V_write_assign_fu_284_p3);
    sensitive << ( tmp_2_fu_274_p2 );
    sensitive << ( tmp_fu_280_p1 );

    SC_METHOD(thread_res_10_V_write_assign_cast_fu_512_p1);
    sensitive << ( res_10_V_write_assign_fu_504_p3 );

    SC_METHOD(thread_res_10_V_write_assign_fu_504_p3);
    sensitive << ( tmp_2_s_fu_494_p2 );
    sensitive << ( tmp_31_fu_500_p1 );

    SC_METHOD(thread_res_11_V_write_assign_cast_fu_534_p1);
    sensitive << ( res_11_V_write_assign_fu_526_p3 );

    SC_METHOD(thread_res_11_V_write_assign_fu_526_p3);
    sensitive << ( tmp_2_10_fu_516_p2 );
    sensitive << ( tmp_32_fu_522_p1 );

    SC_METHOD(thread_res_12_V_write_assign_cast_fu_556_p1);
    sensitive << ( res_12_V_write_assign_fu_548_p3 );

    SC_METHOD(thread_res_12_V_write_assign_fu_548_p3);
    sensitive << ( tmp_2_11_fu_538_p2 );
    sensitive << ( tmp_33_fu_544_p1 );

    SC_METHOD(thread_res_13_V_write_assign_cast_fu_578_p1);
    sensitive << ( res_13_V_write_assign_fu_570_p3 );

    SC_METHOD(thread_res_13_V_write_assign_fu_570_p3);
    sensitive << ( tmp_2_12_fu_560_p2 );
    sensitive << ( tmp_34_fu_566_p1 );

    SC_METHOD(thread_res_14_V_write_assign_cast_fu_600_p1);
    sensitive << ( res_14_V_write_assign_fu_592_p3 );

    SC_METHOD(thread_res_14_V_write_assign_fu_592_p3);
    sensitive << ( tmp_2_13_fu_582_p2 );
    sensitive << ( tmp_35_fu_588_p1 );

    SC_METHOD(thread_res_15_V_write_assign_cast_fu_622_p1);
    sensitive << ( res_15_V_write_assign_fu_614_p3 );

    SC_METHOD(thread_res_15_V_write_assign_fu_614_p3);
    sensitive << ( tmp_2_14_fu_604_p2 );
    sensitive << ( tmp_36_fu_610_p1 );

    SC_METHOD(thread_res_16_V_write_assign_cast_fu_644_p1);
    sensitive << ( res_16_V_write_assign_fu_636_p3 );

    SC_METHOD(thread_res_16_V_write_assign_fu_636_p3);
    sensitive << ( tmp_2_15_fu_626_p2 );
    sensitive << ( tmp_37_fu_632_p1 );

    SC_METHOD(thread_res_17_V_write_assign_cast_fu_666_p1);
    sensitive << ( res_17_V_write_assign_fu_658_p3 );

    SC_METHOD(thread_res_17_V_write_assign_fu_658_p3);
    sensitive << ( tmp_2_16_fu_648_p2 );
    sensitive << ( tmp_38_fu_654_p1 );

    SC_METHOD(thread_res_18_V_write_assign_cast_fu_688_p1);
    sensitive << ( res_18_V_write_assign_fu_680_p3 );

    SC_METHOD(thread_res_18_V_write_assign_fu_680_p3);
    sensitive << ( tmp_2_17_fu_670_p2 );
    sensitive << ( tmp_39_fu_676_p1 );

    SC_METHOD(thread_res_19_V_write_assign_cast_fu_710_p1);
    sensitive << ( res_19_V_write_assign_fu_702_p3 );

    SC_METHOD(thread_res_19_V_write_assign_fu_702_p3);
    sensitive << ( tmp_2_18_fu_692_p2 );
    sensitive << ( tmp_40_fu_698_p1 );

    SC_METHOD(thread_res_1_V_write_assign_cast_fu_314_p1);
    sensitive << ( res_1_V_write_assign_fu_306_p3 );

    SC_METHOD(thread_res_1_V_write_assign_fu_306_p3);
    sensitive << ( tmp_2_1_fu_296_p2 );
    sensitive << ( tmp_22_fu_302_p1 );

    SC_METHOD(thread_res_20_V_write_assign_cast_fu_732_p1);
    sensitive << ( res_20_V_write_assign_fu_724_p3 );

    SC_METHOD(thread_res_20_V_write_assign_fu_724_p3);
    sensitive << ( tmp_2_19_fu_714_p2 );
    sensitive << ( tmp_41_fu_720_p1 );

    SC_METHOD(thread_res_21_V_write_assign_cast_fu_754_p1);
    sensitive << ( res_21_V_write_assign_fu_746_p3 );

    SC_METHOD(thread_res_21_V_write_assign_fu_746_p3);
    sensitive << ( tmp_2_20_fu_736_p2 );
    sensitive << ( tmp_42_fu_742_p1 );

    SC_METHOD(thread_res_22_V_write_assign_cast_fu_776_p1);
    sensitive << ( res_22_V_write_assign_fu_768_p3 );

    SC_METHOD(thread_res_22_V_write_assign_fu_768_p3);
    sensitive << ( tmp_2_21_fu_758_p2 );
    sensitive << ( tmp_43_fu_764_p1 );

    SC_METHOD(thread_res_23_V_write_assign_cast_fu_798_p1);
    sensitive << ( res_23_V_write_assign_fu_790_p3 );

    SC_METHOD(thread_res_23_V_write_assign_fu_790_p3);
    sensitive << ( tmp_2_22_fu_780_p2 );
    sensitive << ( tmp_44_fu_786_p1 );

    SC_METHOD(thread_res_24_V_write_assign_cast_fu_820_p1);
    sensitive << ( res_24_V_write_assign_fu_812_p3 );

    SC_METHOD(thread_res_24_V_write_assign_fu_812_p3);
    sensitive << ( tmp_2_23_fu_802_p2 );
    sensitive << ( tmp_45_fu_808_p1 );

    SC_METHOD(thread_res_25_V_write_assign_cast_fu_842_p1);
    sensitive << ( res_25_V_write_assign_fu_834_p3 );

    SC_METHOD(thread_res_25_V_write_assign_fu_834_p3);
    sensitive << ( tmp_2_24_fu_824_p2 );
    sensitive << ( tmp_46_fu_830_p1 );

    SC_METHOD(thread_res_26_V_write_assign_cast_fu_864_p1);
    sensitive << ( res_26_V_write_assign_fu_856_p3 );

    SC_METHOD(thread_res_26_V_write_assign_fu_856_p3);
    sensitive << ( tmp_2_25_fu_846_p2 );
    sensitive << ( tmp_47_fu_852_p1 );

    SC_METHOD(thread_res_27_V_write_assign_cast_fu_886_p1);
    sensitive << ( res_27_V_write_assign_fu_878_p3 );

    SC_METHOD(thread_res_27_V_write_assign_fu_878_p3);
    sensitive << ( tmp_2_26_fu_868_p2 );
    sensitive << ( tmp_48_fu_874_p1 );

    SC_METHOD(thread_res_28_V_write_assign_cast_fu_908_p1);
    sensitive << ( res_28_V_write_assign_fu_900_p3 );

    SC_METHOD(thread_res_28_V_write_assign_fu_900_p3);
    sensitive << ( tmp_2_27_fu_890_p2 );
    sensitive << ( tmp_49_fu_896_p1 );

    SC_METHOD(thread_res_29_V_write_assign_cast_fu_930_p1);
    sensitive << ( res_29_V_write_assign_fu_922_p3 );

    SC_METHOD(thread_res_29_V_write_assign_fu_922_p3);
    sensitive << ( tmp_2_28_fu_912_p2 );
    sensitive << ( tmp_50_fu_918_p1 );

    SC_METHOD(thread_res_2_V_write_assign_cast_fu_336_p1);
    sensitive << ( res_2_V_write_assign_fu_328_p3 );

    SC_METHOD(thread_res_2_V_write_assign_fu_328_p3);
    sensitive << ( tmp_2_2_fu_318_p2 );
    sensitive << ( tmp_23_fu_324_p1 );

    SC_METHOD(thread_res_30_V_write_assign_cast_fu_952_p1);
    sensitive << ( res_30_V_write_assign_fu_944_p3 );

    SC_METHOD(thread_res_30_V_write_assign_fu_944_p3);
    sensitive << ( tmp_2_29_fu_934_p2 );
    sensitive << ( tmp_51_fu_940_p1 );

    SC_METHOD(thread_res_31_V_write_assign_cast_fu_974_p1);
    sensitive << ( res_31_V_write_assign_fu_966_p3 );

    SC_METHOD(thread_res_31_V_write_assign_fu_966_p3);
    sensitive << ( tmp_2_30_fu_956_p2 );
    sensitive << ( tmp_52_fu_962_p1 );

    SC_METHOD(thread_res_3_V_write_assign_cast_fu_358_p1);
    sensitive << ( res_3_V_write_assign_fu_350_p3 );

    SC_METHOD(thread_res_3_V_write_assign_fu_350_p3);
    sensitive << ( tmp_2_3_fu_340_p2 );
    sensitive << ( tmp_24_fu_346_p1 );

    SC_METHOD(thread_res_4_V_write_assign_cast_fu_380_p1);
    sensitive << ( res_4_V_write_assign_fu_372_p3 );

    SC_METHOD(thread_res_4_V_write_assign_fu_372_p3);
    sensitive << ( tmp_2_4_fu_362_p2 );
    sensitive << ( tmp_25_fu_368_p1 );

    SC_METHOD(thread_res_5_V_write_assign_cast_fu_402_p1);
    sensitive << ( res_5_V_write_assign_fu_394_p3 );

    SC_METHOD(thread_res_5_V_write_assign_fu_394_p3);
    sensitive << ( tmp_2_5_fu_384_p2 );
    sensitive << ( tmp_26_fu_390_p1 );

    SC_METHOD(thread_res_6_V_write_assign_cast_fu_424_p1);
    sensitive << ( res_6_V_write_assign_fu_416_p3 );

    SC_METHOD(thread_res_6_V_write_assign_fu_416_p3);
    sensitive << ( tmp_2_6_fu_406_p2 );
    sensitive << ( tmp_27_fu_412_p1 );

    SC_METHOD(thread_res_7_V_write_assign_cast_fu_446_p1);
    sensitive << ( res_7_V_write_assign_fu_438_p3 );

    SC_METHOD(thread_res_7_V_write_assign_fu_438_p3);
    sensitive << ( tmp_2_7_fu_428_p2 );
    sensitive << ( tmp_28_fu_434_p1 );

    SC_METHOD(thread_res_8_V_write_assign_cast_fu_468_p1);
    sensitive << ( res_8_V_write_assign_fu_460_p3 );

    SC_METHOD(thread_res_8_V_write_assign_fu_460_p3);
    sensitive << ( tmp_2_8_fu_450_p2 );
    sensitive << ( tmp_29_fu_456_p1 );

    SC_METHOD(thread_res_9_V_write_assign_cast_fu_490_p1);
    sensitive << ( res_9_V_write_assign_fu_482_p3 );

    SC_METHOD(thread_res_9_V_write_assign_fu_482_p3);
    sensitive << ( tmp_2_9_fu_472_p2 );
    sensitive << ( tmp_30_fu_478_p1 );

    SC_METHOD(thread_tmp_22_fu_302_p1);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_tmp_23_fu_324_p1);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_tmp_24_fu_346_p1);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_tmp_25_fu_368_p1);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_tmp_26_fu_390_p1);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_tmp_27_fu_412_p1);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_tmp_28_fu_434_p1);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_tmp_29_fu_456_p1);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_tmp_2_10_fu_516_p2);
    sensitive << ( data_11_V_read );

    SC_METHOD(thread_tmp_2_11_fu_538_p2);
    sensitive << ( data_12_V_read );

    SC_METHOD(thread_tmp_2_12_fu_560_p2);
    sensitive << ( data_13_V_read );

    SC_METHOD(thread_tmp_2_13_fu_582_p2);
    sensitive << ( data_14_V_read );

    SC_METHOD(thread_tmp_2_14_fu_604_p2);
    sensitive << ( data_15_V_read );

    SC_METHOD(thread_tmp_2_15_fu_626_p2);
    sensitive << ( data_16_V_read );

    SC_METHOD(thread_tmp_2_16_fu_648_p2);
    sensitive << ( data_17_V_read );

    SC_METHOD(thread_tmp_2_17_fu_670_p2);
    sensitive << ( data_18_V_read );

    SC_METHOD(thread_tmp_2_18_fu_692_p2);
    sensitive << ( data_19_V_read );

    SC_METHOD(thread_tmp_2_19_fu_714_p2);
    sensitive << ( data_20_V_read );

    SC_METHOD(thread_tmp_2_1_fu_296_p2);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_tmp_2_20_fu_736_p2);
    sensitive << ( data_21_V_read );

    SC_METHOD(thread_tmp_2_21_fu_758_p2);
    sensitive << ( data_22_V_read );

    SC_METHOD(thread_tmp_2_22_fu_780_p2);
    sensitive << ( data_23_V_read );

    SC_METHOD(thread_tmp_2_23_fu_802_p2);
    sensitive << ( data_24_V_read );

    SC_METHOD(thread_tmp_2_24_fu_824_p2);
    sensitive << ( data_25_V_read );

    SC_METHOD(thread_tmp_2_25_fu_846_p2);
    sensitive << ( data_26_V_read );

    SC_METHOD(thread_tmp_2_26_fu_868_p2);
    sensitive << ( data_27_V_read );

    SC_METHOD(thread_tmp_2_27_fu_890_p2);
    sensitive << ( data_28_V_read );

    SC_METHOD(thread_tmp_2_28_fu_912_p2);
    sensitive << ( data_29_V_read );

    SC_METHOD(thread_tmp_2_29_fu_934_p2);
    sensitive << ( data_30_V_read );

    SC_METHOD(thread_tmp_2_2_fu_318_p2);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_tmp_2_30_fu_956_p2);
    sensitive << ( data_31_V_read );

    SC_METHOD(thread_tmp_2_3_fu_340_p2);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_tmp_2_4_fu_362_p2);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_tmp_2_5_fu_384_p2);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_tmp_2_6_fu_406_p2);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_tmp_2_7_fu_428_p2);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_tmp_2_8_fu_450_p2);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_tmp_2_9_fu_472_p2);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_tmp_2_fu_274_p2);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_tmp_2_s_fu_494_p2);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_tmp_30_fu_478_p1);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_tmp_31_fu_500_p1);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_tmp_32_fu_522_p1);
    sensitive << ( data_11_V_read );

    SC_METHOD(thread_tmp_33_fu_544_p1);
    sensitive << ( data_12_V_read );

    SC_METHOD(thread_tmp_34_fu_566_p1);
    sensitive << ( data_13_V_read );

    SC_METHOD(thread_tmp_35_fu_588_p1);
    sensitive << ( data_14_V_read );

    SC_METHOD(thread_tmp_36_fu_610_p1);
    sensitive << ( data_15_V_read );

    SC_METHOD(thread_tmp_37_fu_632_p1);
    sensitive << ( data_16_V_read );

    SC_METHOD(thread_tmp_38_fu_654_p1);
    sensitive << ( data_17_V_read );

    SC_METHOD(thread_tmp_39_fu_676_p1);
    sensitive << ( data_18_V_read );

    SC_METHOD(thread_tmp_40_fu_698_p1);
    sensitive << ( data_19_V_read );

    SC_METHOD(thread_tmp_41_fu_720_p1);
    sensitive << ( data_20_V_read );

    SC_METHOD(thread_tmp_42_fu_742_p1);
    sensitive << ( data_21_V_read );

    SC_METHOD(thread_tmp_43_fu_764_p1);
    sensitive << ( data_22_V_read );

    SC_METHOD(thread_tmp_44_fu_786_p1);
    sensitive << ( data_23_V_read );

    SC_METHOD(thread_tmp_45_fu_808_p1);
    sensitive << ( data_24_V_read );

    SC_METHOD(thread_tmp_46_fu_830_p1);
    sensitive << ( data_25_V_read );

    SC_METHOD(thread_tmp_47_fu_852_p1);
    sensitive << ( data_26_V_read );

    SC_METHOD(thread_tmp_48_fu_874_p1);
    sensitive << ( data_27_V_read );

    SC_METHOD(thread_tmp_49_fu_896_p1);
    sensitive << ( data_28_V_read );

    SC_METHOD(thread_tmp_50_fu_918_p1);
    sensitive << ( data_29_V_read );

    SC_METHOD(thread_tmp_51_fu_940_p1);
    sensitive << ( data_30_V_read );

    SC_METHOD(thread_tmp_52_fu_962_p1);
    sensitive << ( data_31_V_read );

    SC_METHOD(thread_tmp_fu_280_p1);
    sensitive << ( data_0_V_read );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, data_10_V_read, "(port)data_10_V_read");
    sc_trace(mVcdFile, data_11_V_read, "(port)data_11_V_read");
    sc_trace(mVcdFile, data_12_V_read, "(port)data_12_V_read");
    sc_trace(mVcdFile, data_13_V_read, "(port)data_13_V_read");
    sc_trace(mVcdFile, data_14_V_read, "(port)data_14_V_read");
    sc_trace(mVcdFile, data_15_V_read, "(port)data_15_V_read");
    sc_trace(mVcdFile, data_16_V_read, "(port)data_16_V_read");
    sc_trace(mVcdFile, data_17_V_read, "(port)data_17_V_read");
    sc_trace(mVcdFile, data_18_V_read, "(port)data_18_V_read");
    sc_trace(mVcdFile, data_19_V_read, "(port)data_19_V_read");
    sc_trace(mVcdFile, data_20_V_read, "(port)data_20_V_read");
    sc_trace(mVcdFile, data_21_V_read, "(port)data_21_V_read");
    sc_trace(mVcdFile, data_22_V_read, "(port)data_22_V_read");
    sc_trace(mVcdFile, data_23_V_read, "(port)data_23_V_read");
    sc_trace(mVcdFile, data_24_V_read, "(port)data_24_V_read");
    sc_trace(mVcdFile, data_25_V_read, "(port)data_25_V_read");
    sc_trace(mVcdFile, data_26_V_read, "(port)data_26_V_read");
    sc_trace(mVcdFile, data_27_V_read, "(port)data_27_V_read");
    sc_trace(mVcdFile, data_28_V_read, "(port)data_28_V_read");
    sc_trace(mVcdFile, data_29_V_read, "(port)data_29_V_read");
    sc_trace(mVcdFile, data_30_V_read, "(port)data_30_V_read");
    sc_trace(mVcdFile, data_31_V_read, "(port)data_31_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
    sc_trace(mVcdFile, ap_return_10, "(port)ap_return_10");
    sc_trace(mVcdFile, ap_return_11, "(port)ap_return_11");
    sc_trace(mVcdFile, ap_return_12, "(port)ap_return_12");
    sc_trace(mVcdFile, ap_return_13, "(port)ap_return_13");
    sc_trace(mVcdFile, ap_return_14, "(port)ap_return_14");
    sc_trace(mVcdFile, ap_return_15, "(port)ap_return_15");
    sc_trace(mVcdFile, ap_return_16, "(port)ap_return_16");
    sc_trace(mVcdFile, ap_return_17, "(port)ap_return_17");
    sc_trace(mVcdFile, ap_return_18, "(port)ap_return_18");
    sc_trace(mVcdFile, ap_return_19, "(port)ap_return_19");
    sc_trace(mVcdFile, ap_return_20, "(port)ap_return_20");
    sc_trace(mVcdFile, ap_return_21, "(port)ap_return_21");
    sc_trace(mVcdFile, ap_return_22, "(port)ap_return_22");
    sc_trace(mVcdFile, ap_return_23, "(port)ap_return_23");
    sc_trace(mVcdFile, ap_return_24, "(port)ap_return_24");
    sc_trace(mVcdFile, ap_return_25, "(port)ap_return_25");
    sc_trace(mVcdFile, ap_return_26, "(port)ap_return_26");
    sc_trace(mVcdFile, ap_return_27, "(port)ap_return_27");
    sc_trace(mVcdFile, ap_return_28, "(port)ap_return_28");
    sc_trace(mVcdFile, ap_return_29, "(port)ap_return_29");
    sc_trace(mVcdFile, ap_return_30, "(port)ap_return_30");
    sc_trace(mVcdFile, ap_return_31, "(port)ap_return_31");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, tmp_2_fu_274_p2, "tmp_2_fu_274_p2");
    sc_trace(mVcdFile, tmp_fu_280_p1, "tmp_fu_280_p1");
    sc_trace(mVcdFile, res_0_V_write_assign_fu_284_p3, "res_0_V_write_assign_fu_284_p3");
    sc_trace(mVcdFile, tmp_2_1_fu_296_p2, "tmp_2_1_fu_296_p2");
    sc_trace(mVcdFile, tmp_22_fu_302_p1, "tmp_22_fu_302_p1");
    sc_trace(mVcdFile, res_1_V_write_assign_fu_306_p3, "res_1_V_write_assign_fu_306_p3");
    sc_trace(mVcdFile, tmp_2_2_fu_318_p2, "tmp_2_2_fu_318_p2");
    sc_trace(mVcdFile, tmp_23_fu_324_p1, "tmp_23_fu_324_p1");
    sc_trace(mVcdFile, res_2_V_write_assign_fu_328_p3, "res_2_V_write_assign_fu_328_p3");
    sc_trace(mVcdFile, tmp_2_3_fu_340_p2, "tmp_2_3_fu_340_p2");
    sc_trace(mVcdFile, tmp_24_fu_346_p1, "tmp_24_fu_346_p1");
    sc_trace(mVcdFile, res_3_V_write_assign_fu_350_p3, "res_3_V_write_assign_fu_350_p3");
    sc_trace(mVcdFile, tmp_2_4_fu_362_p2, "tmp_2_4_fu_362_p2");
    sc_trace(mVcdFile, tmp_25_fu_368_p1, "tmp_25_fu_368_p1");
    sc_trace(mVcdFile, res_4_V_write_assign_fu_372_p3, "res_4_V_write_assign_fu_372_p3");
    sc_trace(mVcdFile, tmp_2_5_fu_384_p2, "tmp_2_5_fu_384_p2");
    sc_trace(mVcdFile, tmp_26_fu_390_p1, "tmp_26_fu_390_p1");
    sc_trace(mVcdFile, res_5_V_write_assign_fu_394_p3, "res_5_V_write_assign_fu_394_p3");
    sc_trace(mVcdFile, tmp_2_6_fu_406_p2, "tmp_2_6_fu_406_p2");
    sc_trace(mVcdFile, tmp_27_fu_412_p1, "tmp_27_fu_412_p1");
    sc_trace(mVcdFile, res_6_V_write_assign_fu_416_p3, "res_6_V_write_assign_fu_416_p3");
    sc_trace(mVcdFile, tmp_2_7_fu_428_p2, "tmp_2_7_fu_428_p2");
    sc_trace(mVcdFile, tmp_28_fu_434_p1, "tmp_28_fu_434_p1");
    sc_trace(mVcdFile, res_7_V_write_assign_fu_438_p3, "res_7_V_write_assign_fu_438_p3");
    sc_trace(mVcdFile, tmp_2_8_fu_450_p2, "tmp_2_8_fu_450_p2");
    sc_trace(mVcdFile, tmp_29_fu_456_p1, "tmp_29_fu_456_p1");
    sc_trace(mVcdFile, res_8_V_write_assign_fu_460_p3, "res_8_V_write_assign_fu_460_p3");
    sc_trace(mVcdFile, tmp_2_9_fu_472_p2, "tmp_2_9_fu_472_p2");
    sc_trace(mVcdFile, tmp_30_fu_478_p1, "tmp_30_fu_478_p1");
    sc_trace(mVcdFile, res_9_V_write_assign_fu_482_p3, "res_9_V_write_assign_fu_482_p3");
    sc_trace(mVcdFile, tmp_2_s_fu_494_p2, "tmp_2_s_fu_494_p2");
    sc_trace(mVcdFile, tmp_31_fu_500_p1, "tmp_31_fu_500_p1");
    sc_trace(mVcdFile, res_10_V_write_assign_fu_504_p3, "res_10_V_write_assign_fu_504_p3");
    sc_trace(mVcdFile, tmp_2_10_fu_516_p2, "tmp_2_10_fu_516_p2");
    sc_trace(mVcdFile, tmp_32_fu_522_p1, "tmp_32_fu_522_p1");
    sc_trace(mVcdFile, res_11_V_write_assign_fu_526_p3, "res_11_V_write_assign_fu_526_p3");
    sc_trace(mVcdFile, tmp_2_11_fu_538_p2, "tmp_2_11_fu_538_p2");
    sc_trace(mVcdFile, tmp_33_fu_544_p1, "tmp_33_fu_544_p1");
    sc_trace(mVcdFile, res_12_V_write_assign_fu_548_p3, "res_12_V_write_assign_fu_548_p3");
    sc_trace(mVcdFile, tmp_2_12_fu_560_p2, "tmp_2_12_fu_560_p2");
    sc_trace(mVcdFile, tmp_34_fu_566_p1, "tmp_34_fu_566_p1");
    sc_trace(mVcdFile, res_13_V_write_assign_fu_570_p3, "res_13_V_write_assign_fu_570_p3");
    sc_trace(mVcdFile, tmp_2_13_fu_582_p2, "tmp_2_13_fu_582_p2");
    sc_trace(mVcdFile, tmp_35_fu_588_p1, "tmp_35_fu_588_p1");
    sc_trace(mVcdFile, res_14_V_write_assign_fu_592_p3, "res_14_V_write_assign_fu_592_p3");
    sc_trace(mVcdFile, tmp_2_14_fu_604_p2, "tmp_2_14_fu_604_p2");
    sc_trace(mVcdFile, tmp_36_fu_610_p1, "tmp_36_fu_610_p1");
    sc_trace(mVcdFile, res_15_V_write_assign_fu_614_p3, "res_15_V_write_assign_fu_614_p3");
    sc_trace(mVcdFile, tmp_2_15_fu_626_p2, "tmp_2_15_fu_626_p2");
    sc_trace(mVcdFile, tmp_37_fu_632_p1, "tmp_37_fu_632_p1");
    sc_trace(mVcdFile, res_16_V_write_assign_fu_636_p3, "res_16_V_write_assign_fu_636_p3");
    sc_trace(mVcdFile, tmp_2_16_fu_648_p2, "tmp_2_16_fu_648_p2");
    sc_trace(mVcdFile, tmp_38_fu_654_p1, "tmp_38_fu_654_p1");
    sc_trace(mVcdFile, res_17_V_write_assign_fu_658_p3, "res_17_V_write_assign_fu_658_p3");
    sc_trace(mVcdFile, tmp_2_17_fu_670_p2, "tmp_2_17_fu_670_p2");
    sc_trace(mVcdFile, tmp_39_fu_676_p1, "tmp_39_fu_676_p1");
    sc_trace(mVcdFile, res_18_V_write_assign_fu_680_p3, "res_18_V_write_assign_fu_680_p3");
    sc_trace(mVcdFile, tmp_2_18_fu_692_p2, "tmp_2_18_fu_692_p2");
    sc_trace(mVcdFile, tmp_40_fu_698_p1, "tmp_40_fu_698_p1");
    sc_trace(mVcdFile, res_19_V_write_assign_fu_702_p3, "res_19_V_write_assign_fu_702_p3");
    sc_trace(mVcdFile, tmp_2_19_fu_714_p2, "tmp_2_19_fu_714_p2");
    sc_trace(mVcdFile, tmp_41_fu_720_p1, "tmp_41_fu_720_p1");
    sc_trace(mVcdFile, res_20_V_write_assign_fu_724_p3, "res_20_V_write_assign_fu_724_p3");
    sc_trace(mVcdFile, tmp_2_20_fu_736_p2, "tmp_2_20_fu_736_p2");
    sc_trace(mVcdFile, tmp_42_fu_742_p1, "tmp_42_fu_742_p1");
    sc_trace(mVcdFile, res_21_V_write_assign_fu_746_p3, "res_21_V_write_assign_fu_746_p3");
    sc_trace(mVcdFile, tmp_2_21_fu_758_p2, "tmp_2_21_fu_758_p2");
    sc_trace(mVcdFile, tmp_43_fu_764_p1, "tmp_43_fu_764_p1");
    sc_trace(mVcdFile, res_22_V_write_assign_fu_768_p3, "res_22_V_write_assign_fu_768_p3");
    sc_trace(mVcdFile, tmp_2_22_fu_780_p2, "tmp_2_22_fu_780_p2");
    sc_trace(mVcdFile, tmp_44_fu_786_p1, "tmp_44_fu_786_p1");
    sc_trace(mVcdFile, res_23_V_write_assign_fu_790_p3, "res_23_V_write_assign_fu_790_p3");
    sc_trace(mVcdFile, tmp_2_23_fu_802_p2, "tmp_2_23_fu_802_p2");
    sc_trace(mVcdFile, tmp_45_fu_808_p1, "tmp_45_fu_808_p1");
    sc_trace(mVcdFile, res_24_V_write_assign_fu_812_p3, "res_24_V_write_assign_fu_812_p3");
    sc_trace(mVcdFile, tmp_2_24_fu_824_p2, "tmp_2_24_fu_824_p2");
    sc_trace(mVcdFile, tmp_46_fu_830_p1, "tmp_46_fu_830_p1");
    sc_trace(mVcdFile, res_25_V_write_assign_fu_834_p3, "res_25_V_write_assign_fu_834_p3");
    sc_trace(mVcdFile, tmp_2_25_fu_846_p2, "tmp_2_25_fu_846_p2");
    sc_trace(mVcdFile, tmp_47_fu_852_p1, "tmp_47_fu_852_p1");
    sc_trace(mVcdFile, res_26_V_write_assign_fu_856_p3, "res_26_V_write_assign_fu_856_p3");
    sc_trace(mVcdFile, tmp_2_26_fu_868_p2, "tmp_2_26_fu_868_p2");
    sc_trace(mVcdFile, tmp_48_fu_874_p1, "tmp_48_fu_874_p1");
    sc_trace(mVcdFile, res_27_V_write_assign_fu_878_p3, "res_27_V_write_assign_fu_878_p3");
    sc_trace(mVcdFile, tmp_2_27_fu_890_p2, "tmp_2_27_fu_890_p2");
    sc_trace(mVcdFile, tmp_49_fu_896_p1, "tmp_49_fu_896_p1");
    sc_trace(mVcdFile, res_28_V_write_assign_fu_900_p3, "res_28_V_write_assign_fu_900_p3");
    sc_trace(mVcdFile, tmp_2_28_fu_912_p2, "tmp_2_28_fu_912_p2");
    sc_trace(mVcdFile, tmp_50_fu_918_p1, "tmp_50_fu_918_p1");
    sc_trace(mVcdFile, res_29_V_write_assign_fu_922_p3, "res_29_V_write_assign_fu_922_p3");
    sc_trace(mVcdFile, tmp_2_29_fu_934_p2, "tmp_2_29_fu_934_p2");
    sc_trace(mVcdFile, tmp_51_fu_940_p1, "tmp_51_fu_940_p1");
    sc_trace(mVcdFile, res_30_V_write_assign_fu_944_p3, "res_30_V_write_assign_fu_944_p3");
    sc_trace(mVcdFile, tmp_2_30_fu_956_p2, "tmp_2_30_fu_956_p2");
    sc_trace(mVcdFile, tmp_52_fu_962_p1, "tmp_52_fu_962_p1");
    sc_trace(mVcdFile, res_31_V_write_assign_fu_966_p3, "res_31_V_write_assign_fu_966_p3");
    sc_trace(mVcdFile, res_0_V_write_assign_cast_fu_292_p1, "res_0_V_write_assign_cast_fu_292_p1");
    sc_trace(mVcdFile, res_1_V_write_assign_cast_fu_314_p1, "res_1_V_write_assign_cast_fu_314_p1");
    sc_trace(mVcdFile, res_2_V_write_assign_cast_fu_336_p1, "res_2_V_write_assign_cast_fu_336_p1");
    sc_trace(mVcdFile, res_3_V_write_assign_cast_fu_358_p1, "res_3_V_write_assign_cast_fu_358_p1");
    sc_trace(mVcdFile, res_4_V_write_assign_cast_fu_380_p1, "res_4_V_write_assign_cast_fu_380_p1");
    sc_trace(mVcdFile, res_5_V_write_assign_cast_fu_402_p1, "res_5_V_write_assign_cast_fu_402_p1");
    sc_trace(mVcdFile, res_6_V_write_assign_cast_fu_424_p1, "res_6_V_write_assign_cast_fu_424_p1");
    sc_trace(mVcdFile, res_7_V_write_assign_cast_fu_446_p1, "res_7_V_write_assign_cast_fu_446_p1");
    sc_trace(mVcdFile, res_8_V_write_assign_cast_fu_468_p1, "res_8_V_write_assign_cast_fu_468_p1");
    sc_trace(mVcdFile, res_9_V_write_assign_cast_fu_490_p1, "res_9_V_write_assign_cast_fu_490_p1");
    sc_trace(mVcdFile, res_10_V_write_assign_cast_fu_512_p1, "res_10_V_write_assign_cast_fu_512_p1");
    sc_trace(mVcdFile, res_11_V_write_assign_cast_fu_534_p1, "res_11_V_write_assign_cast_fu_534_p1");
    sc_trace(mVcdFile, res_12_V_write_assign_cast_fu_556_p1, "res_12_V_write_assign_cast_fu_556_p1");
    sc_trace(mVcdFile, res_13_V_write_assign_cast_fu_578_p1, "res_13_V_write_assign_cast_fu_578_p1");
    sc_trace(mVcdFile, res_14_V_write_assign_cast_fu_600_p1, "res_14_V_write_assign_cast_fu_600_p1");
    sc_trace(mVcdFile, res_15_V_write_assign_cast_fu_622_p1, "res_15_V_write_assign_cast_fu_622_p1");
    sc_trace(mVcdFile, res_16_V_write_assign_cast_fu_644_p1, "res_16_V_write_assign_cast_fu_644_p1");
    sc_trace(mVcdFile, res_17_V_write_assign_cast_fu_666_p1, "res_17_V_write_assign_cast_fu_666_p1");
    sc_trace(mVcdFile, res_18_V_write_assign_cast_fu_688_p1, "res_18_V_write_assign_cast_fu_688_p1");
    sc_trace(mVcdFile, res_19_V_write_assign_cast_fu_710_p1, "res_19_V_write_assign_cast_fu_710_p1");
    sc_trace(mVcdFile, res_20_V_write_assign_cast_fu_732_p1, "res_20_V_write_assign_cast_fu_732_p1");
    sc_trace(mVcdFile, res_21_V_write_assign_cast_fu_754_p1, "res_21_V_write_assign_cast_fu_754_p1");
    sc_trace(mVcdFile, res_22_V_write_assign_cast_fu_776_p1, "res_22_V_write_assign_cast_fu_776_p1");
    sc_trace(mVcdFile, res_23_V_write_assign_cast_fu_798_p1, "res_23_V_write_assign_cast_fu_798_p1");
    sc_trace(mVcdFile, res_24_V_write_assign_cast_fu_820_p1, "res_24_V_write_assign_cast_fu_820_p1");
    sc_trace(mVcdFile, res_25_V_write_assign_cast_fu_842_p1, "res_25_V_write_assign_cast_fu_842_p1");
    sc_trace(mVcdFile, res_26_V_write_assign_cast_fu_864_p1, "res_26_V_write_assign_cast_fu_864_p1");
    sc_trace(mVcdFile, res_27_V_write_assign_cast_fu_886_p1, "res_27_V_write_assign_cast_fu_886_p1");
    sc_trace(mVcdFile, res_28_V_write_assign_cast_fu_908_p1, "res_28_V_write_assign_cast_fu_908_p1");
    sc_trace(mVcdFile, res_29_V_write_assign_cast_fu_930_p1, "res_29_V_write_assign_cast_fu_930_p1");
    sc_trace(mVcdFile, res_30_V_write_assign_cast_fu_952_p1, "res_30_V_write_assign_cast_fu_952_p1");
    sc_trace(mVcdFile, res_31_V_write_assign_cast_fu_974_p1, "res_31_V_write_assign_cast_fu_974_p1");
#endif

    }
}

relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::~relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_0() {
    ap_return_0 = res_0_V_write_assign_cast_fu_292_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_1() {
    ap_return_1 = res_1_V_write_assign_cast_fu_314_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_10() {
    ap_return_10 = res_10_V_write_assign_cast_fu_512_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_11() {
    ap_return_11 = res_11_V_write_assign_cast_fu_534_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_12() {
    ap_return_12 = res_12_V_write_assign_cast_fu_556_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_13() {
    ap_return_13 = res_13_V_write_assign_cast_fu_578_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_14() {
    ap_return_14 = res_14_V_write_assign_cast_fu_600_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_15() {
    ap_return_15 = res_15_V_write_assign_cast_fu_622_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_16() {
    ap_return_16 = res_16_V_write_assign_cast_fu_644_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_17() {
    ap_return_17 = res_17_V_write_assign_cast_fu_666_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_18() {
    ap_return_18 = res_18_V_write_assign_cast_fu_688_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_19() {
    ap_return_19 = res_19_V_write_assign_cast_fu_710_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_2() {
    ap_return_2 = res_2_V_write_assign_cast_fu_336_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_20() {
    ap_return_20 = res_20_V_write_assign_cast_fu_732_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_21() {
    ap_return_21 = res_21_V_write_assign_cast_fu_754_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_22() {
    ap_return_22 = res_22_V_write_assign_cast_fu_776_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_23() {
    ap_return_23 = res_23_V_write_assign_cast_fu_798_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_24() {
    ap_return_24 = res_24_V_write_assign_cast_fu_820_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_25() {
    ap_return_25 = res_25_V_write_assign_cast_fu_842_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_26() {
    ap_return_26 = res_26_V_write_assign_cast_fu_864_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_27() {
    ap_return_27 = res_27_V_write_assign_cast_fu_886_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_28() {
    ap_return_28 = res_28_V_write_assign_cast_fu_908_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_29() {
    ap_return_29 = res_29_V_write_assign_cast_fu_930_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_3() {
    ap_return_3 = res_3_V_write_assign_cast_fu_358_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_30() {
    ap_return_30 = res_30_V_write_assign_cast_fu_952_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_31() {
    ap_return_31 = res_31_V_write_assign_cast_fu_974_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_4() {
    ap_return_4 = res_4_V_write_assign_cast_fu_380_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_5() {
    ap_return_5 = res_5_V_write_assign_cast_fu_402_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_6() {
    ap_return_6 = res_6_V_write_assign_cast_fu_424_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_7() {
    ap_return_7 = res_7_V_write_assign_cast_fu_446_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_8() {
    ap_return_8 = res_8_V_write_assign_cast_fu_468_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_ap_return_9() {
    ap_return_9 = res_9_V_write_assign_cast_fu_490_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_0_V_write_assign_cast_fu_292_p1() {
    res_0_V_write_assign_cast_fu_292_p1 = esl_zext<16,15>(res_0_V_write_assign_fu_284_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_0_V_write_assign_fu_284_p3() {
    res_0_V_write_assign_fu_284_p3 = (!tmp_2_fu_274_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_fu_274_p2.read()[0].to_bool())? tmp_fu_280_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_10_V_write_assign_cast_fu_512_p1() {
    res_10_V_write_assign_cast_fu_512_p1 = esl_zext<16,15>(res_10_V_write_assign_fu_504_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_10_V_write_assign_fu_504_p3() {
    res_10_V_write_assign_fu_504_p3 = (!tmp_2_s_fu_494_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_s_fu_494_p2.read()[0].to_bool())? tmp_31_fu_500_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_11_V_write_assign_cast_fu_534_p1() {
    res_11_V_write_assign_cast_fu_534_p1 = esl_zext<16,15>(res_11_V_write_assign_fu_526_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_11_V_write_assign_fu_526_p3() {
    res_11_V_write_assign_fu_526_p3 = (!tmp_2_10_fu_516_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_10_fu_516_p2.read()[0].to_bool())? tmp_32_fu_522_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_12_V_write_assign_cast_fu_556_p1() {
    res_12_V_write_assign_cast_fu_556_p1 = esl_zext<16,15>(res_12_V_write_assign_fu_548_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_12_V_write_assign_fu_548_p3() {
    res_12_V_write_assign_fu_548_p3 = (!tmp_2_11_fu_538_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_11_fu_538_p2.read()[0].to_bool())? tmp_33_fu_544_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_13_V_write_assign_cast_fu_578_p1() {
    res_13_V_write_assign_cast_fu_578_p1 = esl_zext<16,15>(res_13_V_write_assign_fu_570_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_13_V_write_assign_fu_570_p3() {
    res_13_V_write_assign_fu_570_p3 = (!tmp_2_12_fu_560_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_12_fu_560_p2.read()[0].to_bool())? tmp_34_fu_566_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_14_V_write_assign_cast_fu_600_p1() {
    res_14_V_write_assign_cast_fu_600_p1 = esl_zext<16,15>(res_14_V_write_assign_fu_592_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_14_V_write_assign_fu_592_p3() {
    res_14_V_write_assign_fu_592_p3 = (!tmp_2_13_fu_582_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_13_fu_582_p2.read()[0].to_bool())? tmp_35_fu_588_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_15_V_write_assign_cast_fu_622_p1() {
    res_15_V_write_assign_cast_fu_622_p1 = esl_zext<16,15>(res_15_V_write_assign_fu_614_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_15_V_write_assign_fu_614_p3() {
    res_15_V_write_assign_fu_614_p3 = (!tmp_2_14_fu_604_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_14_fu_604_p2.read()[0].to_bool())? tmp_36_fu_610_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_16_V_write_assign_cast_fu_644_p1() {
    res_16_V_write_assign_cast_fu_644_p1 = esl_zext<16,15>(res_16_V_write_assign_fu_636_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_16_V_write_assign_fu_636_p3() {
    res_16_V_write_assign_fu_636_p3 = (!tmp_2_15_fu_626_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_15_fu_626_p2.read()[0].to_bool())? tmp_37_fu_632_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_17_V_write_assign_cast_fu_666_p1() {
    res_17_V_write_assign_cast_fu_666_p1 = esl_zext<16,15>(res_17_V_write_assign_fu_658_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_17_V_write_assign_fu_658_p3() {
    res_17_V_write_assign_fu_658_p3 = (!tmp_2_16_fu_648_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_16_fu_648_p2.read()[0].to_bool())? tmp_38_fu_654_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_18_V_write_assign_cast_fu_688_p1() {
    res_18_V_write_assign_cast_fu_688_p1 = esl_zext<16,15>(res_18_V_write_assign_fu_680_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_18_V_write_assign_fu_680_p3() {
    res_18_V_write_assign_fu_680_p3 = (!tmp_2_17_fu_670_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_17_fu_670_p2.read()[0].to_bool())? tmp_39_fu_676_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_19_V_write_assign_cast_fu_710_p1() {
    res_19_V_write_assign_cast_fu_710_p1 = esl_zext<16,15>(res_19_V_write_assign_fu_702_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_19_V_write_assign_fu_702_p3() {
    res_19_V_write_assign_fu_702_p3 = (!tmp_2_18_fu_692_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_18_fu_692_p2.read()[0].to_bool())? tmp_40_fu_698_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_1_V_write_assign_cast_fu_314_p1() {
    res_1_V_write_assign_cast_fu_314_p1 = esl_zext<16,15>(res_1_V_write_assign_fu_306_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_1_V_write_assign_fu_306_p3() {
    res_1_V_write_assign_fu_306_p3 = (!tmp_2_1_fu_296_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_1_fu_296_p2.read()[0].to_bool())? tmp_22_fu_302_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_20_V_write_assign_cast_fu_732_p1() {
    res_20_V_write_assign_cast_fu_732_p1 = esl_zext<16,15>(res_20_V_write_assign_fu_724_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_20_V_write_assign_fu_724_p3() {
    res_20_V_write_assign_fu_724_p3 = (!tmp_2_19_fu_714_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_19_fu_714_p2.read()[0].to_bool())? tmp_41_fu_720_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_21_V_write_assign_cast_fu_754_p1() {
    res_21_V_write_assign_cast_fu_754_p1 = esl_zext<16,15>(res_21_V_write_assign_fu_746_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_21_V_write_assign_fu_746_p3() {
    res_21_V_write_assign_fu_746_p3 = (!tmp_2_20_fu_736_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_20_fu_736_p2.read()[0].to_bool())? tmp_42_fu_742_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_22_V_write_assign_cast_fu_776_p1() {
    res_22_V_write_assign_cast_fu_776_p1 = esl_zext<16,15>(res_22_V_write_assign_fu_768_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_22_V_write_assign_fu_768_p3() {
    res_22_V_write_assign_fu_768_p3 = (!tmp_2_21_fu_758_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_21_fu_758_p2.read()[0].to_bool())? tmp_43_fu_764_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_23_V_write_assign_cast_fu_798_p1() {
    res_23_V_write_assign_cast_fu_798_p1 = esl_zext<16,15>(res_23_V_write_assign_fu_790_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_23_V_write_assign_fu_790_p3() {
    res_23_V_write_assign_fu_790_p3 = (!tmp_2_22_fu_780_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_22_fu_780_p2.read()[0].to_bool())? tmp_44_fu_786_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_24_V_write_assign_cast_fu_820_p1() {
    res_24_V_write_assign_cast_fu_820_p1 = esl_zext<16,15>(res_24_V_write_assign_fu_812_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_24_V_write_assign_fu_812_p3() {
    res_24_V_write_assign_fu_812_p3 = (!tmp_2_23_fu_802_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_23_fu_802_p2.read()[0].to_bool())? tmp_45_fu_808_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_25_V_write_assign_cast_fu_842_p1() {
    res_25_V_write_assign_cast_fu_842_p1 = esl_zext<16,15>(res_25_V_write_assign_fu_834_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_25_V_write_assign_fu_834_p3() {
    res_25_V_write_assign_fu_834_p3 = (!tmp_2_24_fu_824_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_24_fu_824_p2.read()[0].to_bool())? tmp_46_fu_830_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_26_V_write_assign_cast_fu_864_p1() {
    res_26_V_write_assign_cast_fu_864_p1 = esl_zext<16,15>(res_26_V_write_assign_fu_856_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_26_V_write_assign_fu_856_p3() {
    res_26_V_write_assign_fu_856_p3 = (!tmp_2_25_fu_846_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_25_fu_846_p2.read()[0].to_bool())? tmp_47_fu_852_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_27_V_write_assign_cast_fu_886_p1() {
    res_27_V_write_assign_cast_fu_886_p1 = esl_zext<16,15>(res_27_V_write_assign_fu_878_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_27_V_write_assign_fu_878_p3() {
    res_27_V_write_assign_fu_878_p3 = (!tmp_2_26_fu_868_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_26_fu_868_p2.read()[0].to_bool())? tmp_48_fu_874_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_28_V_write_assign_cast_fu_908_p1() {
    res_28_V_write_assign_cast_fu_908_p1 = esl_zext<16,15>(res_28_V_write_assign_fu_900_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_28_V_write_assign_fu_900_p3() {
    res_28_V_write_assign_fu_900_p3 = (!tmp_2_27_fu_890_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_27_fu_890_p2.read()[0].to_bool())? tmp_49_fu_896_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_29_V_write_assign_cast_fu_930_p1() {
    res_29_V_write_assign_cast_fu_930_p1 = esl_zext<16,15>(res_29_V_write_assign_fu_922_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_29_V_write_assign_fu_922_p3() {
    res_29_V_write_assign_fu_922_p3 = (!tmp_2_28_fu_912_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_28_fu_912_p2.read()[0].to_bool())? tmp_50_fu_918_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_2_V_write_assign_cast_fu_336_p1() {
    res_2_V_write_assign_cast_fu_336_p1 = esl_zext<16,15>(res_2_V_write_assign_fu_328_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_2_V_write_assign_fu_328_p3() {
    res_2_V_write_assign_fu_328_p3 = (!tmp_2_2_fu_318_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_2_fu_318_p2.read()[0].to_bool())? tmp_23_fu_324_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_30_V_write_assign_cast_fu_952_p1() {
    res_30_V_write_assign_cast_fu_952_p1 = esl_zext<16,15>(res_30_V_write_assign_fu_944_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_30_V_write_assign_fu_944_p3() {
    res_30_V_write_assign_fu_944_p3 = (!tmp_2_29_fu_934_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_29_fu_934_p2.read()[0].to_bool())? tmp_51_fu_940_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_31_V_write_assign_cast_fu_974_p1() {
    res_31_V_write_assign_cast_fu_974_p1 = esl_zext<16,15>(res_31_V_write_assign_fu_966_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_31_V_write_assign_fu_966_p3() {
    res_31_V_write_assign_fu_966_p3 = (!tmp_2_30_fu_956_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_30_fu_956_p2.read()[0].to_bool())? tmp_52_fu_962_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_3_V_write_assign_cast_fu_358_p1() {
    res_3_V_write_assign_cast_fu_358_p1 = esl_zext<16,15>(res_3_V_write_assign_fu_350_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_3_V_write_assign_fu_350_p3() {
    res_3_V_write_assign_fu_350_p3 = (!tmp_2_3_fu_340_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_3_fu_340_p2.read()[0].to_bool())? tmp_24_fu_346_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_4_V_write_assign_cast_fu_380_p1() {
    res_4_V_write_assign_cast_fu_380_p1 = esl_zext<16,15>(res_4_V_write_assign_fu_372_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_4_V_write_assign_fu_372_p3() {
    res_4_V_write_assign_fu_372_p3 = (!tmp_2_4_fu_362_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_4_fu_362_p2.read()[0].to_bool())? tmp_25_fu_368_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_5_V_write_assign_cast_fu_402_p1() {
    res_5_V_write_assign_cast_fu_402_p1 = esl_zext<16,15>(res_5_V_write_assign_fu_394_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_5_V_write_assign_fu_394_p3() {
    res_5_V_write_assign_fu_394_p3 = (!tmp_2_5_fu_384_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_5_fu_384_p2.read()[0].to_bool())? tmp_26_fu_390_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_6_V_write_assign_cast_fu_424_p1() {
    res_6_V_write_assign_cast_fu_424_p1 = esl_zext<16,15>(res_6_V_write_assign_fu_416_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_6_V_write_assign_fu_416_p3() {
    res_6_V_write_assign_fu_416_p3 = (!tmp_2_6_fu_406_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_6_fu_406_p2.read()[0].to_bool())? tmp_27_fu_412_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_7_V_write_assign_cast_fu_446_p1() {
    res_7_V_write_assign_cast_fu_446_p1 = esl_zext<16,15>(res_7_V_write_assign_fu_438_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_7_V_write_assign_fu_438_p3() {
    res_7_V_write_assign_fu_438_p3 = (!tmp_2_7_fu_428_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_7_fu_428_p2.read()[0].to_bool())? tmp_28_fu_434_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_8_V_write_assign_cast_fu_468_p1() {
    res_8_V_write_assign_cast_fu_468_p1 = esl_zext<16,15>(res_8_V_write_assign_fu_460_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_8_V_write_assign_fu_460_p3() {
    res_8_V_write_assign_fu_460_p3 = (!tmp_2_8_fu_450_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_8_fu_450_p2.read()[0].to_bool())? tmp_29_fu_456_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_9_V_write_assign_cast_fu_490_p1() {
    res_9_V_write_assign_cast_fu_490_p1 = esl_zext<16,15>(res_9_V_write_assign_fu_482_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_res_9_V_write_assign_fu_482_p3() {
    res_9_V_write_assign_fu_482_p3 = (!tmp_2_9_fu_472_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_2_9_fu_472_p2.read()[0].to_bool())? tmp_30_fu_478_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_22_fu_302_p1() {
    tmp_22_fu_302_p1 = data_1_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_23_fu_324_p1() {
    tmp_23_fu_324_p1 = data_2_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_24_fu_346_p1() {
    tmp_24_fu_346_p1 = data_3_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_25_fu_368_p1() {
    tmp_25_fu_368_p1 = data_4_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_26_fu_390_p1() {
    tmp_26_fu_390_p1 = data_5_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_27_fu_412_p1() {
    tmp_27_fu_412_p1 = data_6_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_28_fu_434_p1() {
    tmp_28_fu_434_p1 = data_7_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_29_fu_456_p1() {
    tmp_29_fu_456_p1 = data_8_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_10_fu_516_p2() {
    tmp_2_10_fu_516_p2 = (!data_11_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_11_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_11_fu_538_p2() {
    tmp_2_11_fu_538_p2 = (!data_12_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_12_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_12_fu_560_p2() {
    tmp_2_12_fu_560_p2 = (!data_13_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_13_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_13_fu_582_p2() {
    tmp_2_13_fu_582_p2 = (!data_14_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_14_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_14_fu_604_p2() {
    tmp_2_14_fu_604_p2 = (!data_15_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_15_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_15_fu_626_p2() {
    tmp_2_15_fu_626_p2 = (!data_16_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_16_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_16_fu_648_p2() {
    tmp_2_16_fu_648_p2 = (!data_17_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_17_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_17_fu_670_p2() {
    tmp_2_17_fu_670_p2 = (!data_18_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_18_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_18_fu_692_p2() {
    tmp_2_18_fu_692_p2 = (!data_19_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_19_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_19_fu_714_p2() {
    tmp_2_19_fu_714_p2 = (!data_20_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_20_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_1_fu_296_p2() {
    tmp_2_1_fu_296_p2 = (!data_1_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_1_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_20_fu_736_p2() {
    tmp_2_20_fu_736_p2 = (!data_21_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_21_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_21_fu_758_p2() {
    tmp_2_21_fu_758_p2 = (!data_22_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_22_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_22_fu_780_p2() {
    tmp_2_22_fu_780_p2 = (!data_23_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_23_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_23_fu_802_p2() {
    tmp_2_23_fu_802_p2 = (!data_24_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_24_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_24_fu_824_p2() {
    tmp_2_24_fu_824_p2 = (!data_25_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_25_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_25_fu_846_p2() {
    tmp_2_25_fu_846_p2 = (!data_26_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_26_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_26_fu_868_p2() {
    tmp_2_26_fu_868_p2 = (!data_27_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_27_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_27_fu_890_p2() {
    tmp_2_27_fu_890_p2 = (!data_28_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_28_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_28_fu_912_p2() {
    tmp_2_28_fu_912_p2 = (!data_29_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_29_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_29_fu_934_p2() {
    tmp_2_29_fu_934_p2 = (!data_30_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_30_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_2_fu_318_p2() {
    tmp_2_2_fu_318_p2 = (!data_2_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_2_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_30_fu_956_p2() {
    tmp_2_30_fu_956_p2 = (!data_31_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_31_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_3_fu_340_p2() {
    tmp_2_3_fu_340_p2 = (!data_3_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_3_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_4_fu_362_p2() {
    tmp_2_4_fu_362_p2 = (!data_4_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_4_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_5_fu_384_p2() {
    tmp_2_5_fu_384_p2 = (!data_5_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_5_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_6_fu_406_p2() {
    tmp_2_6_fu_406_p2 = (!data_6_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_6_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_7_fu_428_p2() {
    tmp_2_7_fu_428_p2 = (!data_7_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_7_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_8_fu_450_p2() {
    tmp_2_8_fu_450_p2 = (!data_8_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_8_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_9_fu_472_p2() {
    tmp_2_9_fu_472_p2 = (!data_9_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_9_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_fu_274_p2() {
    tmp_2_fu_274_p2 = (!data_0_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_0_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_2_s_fu_494_p2() {
    tmp_2_s_fu_494_p2 = (!data_10_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_10_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_30_fu_478_p1() {
    tmp_30_fu_478_p1 = data_9_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_31_fu_500_p1() {
    tmp_31_fu_500_p1 = data_10_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_32_fu_522_p1() {
    tmp_32_fu_522_p1 = data_11_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_33_fu_544_p1() {
    tmp_33_fu_544_p1 = data_12_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_34_fu_566_p1() {
    tmp_34_fu_566_p1 = data_13_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_35_fu_588_p1() {
    tmp_35_fu_588_p1 = data_14_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_36_fu_610_p1() {
    tmp_36_fu_610_p1 = data_15_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_37_fu_632_p1() {
    tmp_37_fu_632_p1 = data_16_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_38_fu_654_p1() {
    tmp_38_fu_654_p1 = data_17_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_39_fu_676_p1() {
    tmp_39_fu_676_p1 = data_18_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_40_fu_698_p1() {
    tmp_40_fu_698_p1 = data_19_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_41_fu_720_p1() {
    tmp_41_fu_720_p1 = data_20_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_42_fu_742_p1() {
    tmp_42_fu_742_p1 = data_21_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_43_fu_764_p1() {
    tmp_43_fu_764_p1 = data_22_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_44_fu_786_p1() {
    tmp_44_fu_786_p1 = data_23_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_45_fu_808_p1() {
    tmp_45_fu_808_p1 = data_24_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_46_fu_830_p1() {
    tmp_46_fu_830_p1 = data_25_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_47_fu_852_p1() {
    tmp_47_fu_852_p1 = data_26_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_48_fu_874_p1() {
    tmp_48_fu_874_p1 = data_27_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_49_fu_896_p1() {
    tmp_49_fu_896_p1 = data_28_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_50_fu_918_p1() {
    tmp_50_fu_918_p1 = data_29_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_51_fu_940_p1() {
    tmp_51_fu_940_p1 = data_30_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_52_fu_962_p1() {
    tmp_52_fu_962_p1 = data_31_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s::thread_tmp_fu_280_p1() {
    tmp_fu_280_p1 = data_0_V_read.read().range(15-1, 0);
}

}

