// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_logic_0 = sc_dt::Log_0;
const bool dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_boolean_1 = true;
const bool dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_boolean_0 = false;
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_3F43B = "111111010000111011";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_3EDF4 = "111110110111110100";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_3E12E = "111110000100101110";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_1960 = "1100101100000";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_1FE5 = "1111111100101";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_3F07D = "111111000001111101";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_365E = "11011001011110";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_13FD = "1001111111101";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_15A3 = "1010110100011";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_1308 = "1001100001000";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_3ED92 = "111110110110010010";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_3D6C9 = "111101011011001001";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_2452 = "10010001010010";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_7DF = "11111011111";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_3EA8D = "111110101010001101";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_3E06D = "111110000001101101";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv32_20 = "100000";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv32_31 = "110001";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_9D9 = "100111011001";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_6FA = "11011111010";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_F08 = "111100001000";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_145D = "1010001011101";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_3F5A9 = "111111010110101001";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_3FCF6 = "111111110011110110";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_26C = "1001101100";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv18_3FA86 = "111111101010000110";

dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_1_V_fu_1297_p2);
    sensitive << ( r_V_6_0_1_reg_1188 );
    sensitive << ( tmp1_fu_1291_p2 );

    SC_METHOD(thread_acc_2_V_fu_1309_p2);
    sensitive << ( r_V_6_0_2_reg_1192 );
    sensitive << ( tmp2_fu_1303_p2 );

    SC_METHOD(thread_acc_3_V_fu_1321_p2);
    sensitive << ( r_V_6_0_3_reg_1196 );
    sensitive << ( tmp3_fu_1315_p2 );

    SC_METHOD(thread_acc_4_V_fu_1333_p2);
    sensitive << ( r_V_6_0_4_reg_1200 );
    sensitive << ( tmp4_fu_1327_p2 );

    SC_METHOD(thread_acc_5_V_fu_1345_p2);
    sensitive << ( r_V_6_0_5_reg_1204 );
    sensitive << ( tmp5_fu_1339_p2 );

    SC_METHOD(thread_acc_6_V_fu_1357_p2);
    sensitive << ( r_V_6_0_6_reg_1208 );
    sensitive << ( tmp6_fu_1351_p2 );

    SC_METHOD(thread_acc_7_V_fu_1369_p2);
    sensitive << ( r_V_6_0_7_reg_1212 );
    sensitive << ( tmp7_fu_1363_p2 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( res_0_V_write_assign_fu_1285_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_0_int_reg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( acc_1_V_fu_1297_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_1_int_reg );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( acc_2_V_fu_1309_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_2_int_reg );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( acc_3_V_fu_1321_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_3_int_reg );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( acc_4_V_fu_1333_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_4_int_reg );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( acc_5_V_fu_1345_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_5_int_reg );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( acc_6_V_fu_1357_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_6_int_reg );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( acc_7_V_fu_1369_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_7_int_reg );

    SC_METHOD(thread_r_V_1_fu_1261_p4);
    sensitive << ( data_V_read );

    SC_METHOD(thread_r_V_6_0_1_fu_85_p2);
    sensitive << ( tmp_28_fu_1249_p1 );

    SC_METHOD(thread_r_V_6_0_2_fu_95_p2);
    sensitive << ( tmp_28_fu_1249_p1 );

    SC_METHOD(thread_r_V_6_0_3_fu_88_p2);
    sensitive << ( tmp_28_fu_1249_p1 );

    SC_METHOD(thread_r_V_6_0_4_fu_83_p2);
    sensitive << ( tmp_28_fu_1249_p1 );

    SC_METHOD(thread_r_V_6_0_5_fu_84_p2);
    sensitive << ( tmp_28_fu_1249_p1 );

    SC_METHOD(thread_r_V_6_0_6_fu_86_p2);
    sensitive << ( tmp_28_fu_1249_p1 );

    SC_METHOD(thread_r_V_6_0_7_fu_92_p2);
    sensitive << ( tmp_28_fu_1249_p1 );

    SC_METHOD(thread_r_V_6_1_1_fu_82_p2);
    sensitive << ( r_V_1_fu_1261_p4 );

    SC_METHOD(thread_r_V_6_1_2_fu_90_p2);
    sensitive << ( r_V_1_fu_1261_p4 );

    SC_METHOD(thread_r_V_6_1_3_fu_87_p2);
    sensitive << ( r_V_1_fu_1261_p4 );

    SC_METHOD(thread_r_V_6_1_4_fu_91_p2);
    sensitive << ( r_V_1_fu_1261_p4 );

    SC_METHOD(thread_r_V_6_1_5_fu_93_p2);
    sensitive << ( r_V_1_fu_1261_p4 );

    SC_METHOD(thread_r_V_6_1_6_fu_94_p2);
    sensitive << ( r_V_1_fu_1261_p4 );

    SC_METHOD(thread_r_V_6_1_7_fu_80_p2);
    sensitive << ( r_V_1_fu_1261_p4 );

    SC_METHOD(thread_r_V_6_1_fu_89_p2);
    sensitive << ( r_V_1_fu_1261_p4 );

    SC_METHOD(thread_r_V_6_fu_81_p2);
    sensitive << ( tmp_28_fu_1249_p1 );

    SC_METHOD(thread_res_0_V_write_assign_fu_1285_p2);
    sensitive << ( r_V_6_reg_1184 );
    sensitive << ( tmp_fu_1279_p2 );

    SC_METHOD(thread_tmp1_fu_1291_p2);
    sensitive << ( r_V_6_1_1_reg_1220 );

    SC_METHOD(thread_tmp2_fu_1303_p2);
    sensitive << ( r_V_6_1_2_reg_1224 );

    SC_METHOD(thread_tmp3_fu_1315_p2);
    sensitive << ( r_V_6_1_3_reg_1228 );

    SC_METHOD(thread_tmp4_fu_1327_p2);
    sensitive << ( r_V_6_1_4_reg_1232 );

    SC_METHOD(thread_tmp5_fu_1339_p2);
    sensitive << ( r_V_6_1_5_reg_1236 );

    SC_METHOD(thread_tmp6_fu_1351_p2);
    sensitive << ( r_V_6_1_6_reg_1240 );

    SC_METHOD(thread_tmp7_fu_1363_p2);
    sensitive << ( r_V_6_1_7_reg_1244 );

    SC_METHOD(thread_tmp_28_fu_1249_p1);
    sensitive << ( data_V_read );

    SC_METHOD(thread_tmp_fu_1279_p2);
    sensitive << ( r_V_6_1_reg_1216 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, data_V_read, "(port)data_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, r_V_6_fu_81_p2, "r_V_6_fu_81_p2");
    sc_trace(mVcdFile, r_V_6_reg_1184, "r_V_6_reg_1184");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, r_V_6_0_1_fu_85_p2, "r_V_6_0_1_fu_85_p2");
    sc_trace(mVcdFile, r_V_6_0_1_reg_1188, "r_V_6_0_1_reg_1188");
    sc_trace(mVcdFile, r_V_6_0_2_fu_95_p2, "r_V_6_0_2_fu_95_p2");
    sc_trace(mVcdFile, r_V_6_0_2_reg_1192, "r_V_6_0_2_reg_1192");
    sc_trace(mVcdFile, r_V_6_0_3_fu_88_p2, "r_V_6_0_3_fu_88_p2");
    sc_trace(mVcdFile, r_V_6_0_3_reg_1196, "r_V_6_0_3_reg_1196");
    sc_trace(mVcdFile, r_V_6_0_4_fu_83_p2, "r_V_6_0_4_fu_83_p2");
    sc_trace(mVcdFile, r_V_6_0_4_reg_1200, "r_V_6_0_4_reg_1200");
    sc_trace(mVcdFile, r_V_6_0_5_fu_84_p2, "r_V_6_0_5_fu_84_p2");
    sc_trace(mVcdFile, r_V_6_0_5_reg_1204, "r_V_6_0_5_reg_1204");
    sc_trace(mVcdFile, r_V_6_0_6_fu_86_p2, "r_V_6_0_6_fu_86_p2");
    sc_trace(mVcdFile, r_V_6_0_6_reg_1208, "r_V_6_0_6_reg_1208");
    sc_trace(mVcdFile, r_V_6_0_7_fu_92_p2, "r_V_6_0_7_fu_92_p2");
    sc_trace(mVcdFile, r_V_6_0_7_reg_1212, "r_V_6_0_7_reg_1212");
    sc_trace(mVcdFile, r_V_6_1_fu_89_p2, "r_V_6_1_fu_89_p2");
    sc_trace(mVcdFile, r_V_6_1_reg_1216, "r_V_6_1_reg_1216");
    sc_trace(mVcdFile, r_V_6_1_1_fu_82_p2, "r_V_6_1_1_fu_82_p2");
    sc_trace(mVcdFile, r_V_6_1_1_reg_1220, "r_V_6_1_1_reg_1220");
    sc_trace(mVcdFile, r_V_6_1_2_fu_90_p2, "r_V_6_1_2_fu_90_p2");
    sc_trace(mVcdFile, r_V_6_1_2_reg_1224, "r_V_6_1_2_reg_1224");
    sc_trace(mVcdFile, r_V_6_1_3_fu_87_p2, "r_V_6_1_3_fu_87_p2");
    sc_trace(mVcdFile, r_V_6_1_3_reg_1228, "r_V_6_1_3_reg_1228");
    sc_trace(mVcdFile, r_V_6_1_4_fu_91_p2, "r_V_6_1_4_fu_91_p2");
    sc_trace(mVcdFile, r_V_6_1_4_reg_1232, "r_V_6_1_4_reg_1232");
    sc_trace(mVcdFile, r_V_6_1_5_fu_93_p2, "r_V_6_1_5_fu_93_p2");
    sc_trace(mVcdFile, r_V_6_1_5_reg_1236, "r_V_6_1_5_reg_1236");
    sc_trace(mVcdFile, r_V_6_1_6_fu_94_p2, "r_V_6_1_6_fu_94_p2");
    sc_trace(mVcdFile, r_V_6_1_6_reg_1240, "r_V_6_1_6_reg_1240");
    sc_trace(mVcdFile, r_V_6_1_7_fu_80_p2, "r_V_6_1_7_fu_80_p2");
    sc_trace(mVcdFile, r_V_6_1_7_reg_1244, "r_V_6_1_7_reg_1244");
    sc_trace(mVcdFile, r_V_1_fu_1261_p4, "r_V_1_fu_1261_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_28_fu_1249_p1, "tmp_28_fu_1249_p1");
    sc_trace(mVcdFile, tmp_fu_1279_p2, "tmp_fu_1279_p2");
    sc_trace(mVcdFile, tmp1_fu_1291_p2, "tmp1_fu_1291_p2");
    sc_trace(mVcdFile, tmp2_fu_1303_p2, "tmp2_fu_1303_p2");
    sc_trace(mVcdFile, tmp3_fu_1315_p2, "tmp3_fu_1315_p2");
    sc_trace(mVcdFile, tmp4_fu_1327_p2, "tmp4_fu_1327_p2");
    sc_trace(mVcdFile, tmp5_fu_1339_p2, "tmp5_fu_1339_p2");
    sc_trace(mVcdFile, tmp6_fu_1351_p2, "tmp6_fu_1351_p2");
    sc_trace(mVcdFile, tmp7_fu_1363_p2, "tmp7_fu_1363_p2");
    sc_trace(mVcdFile, res_0_V_write_assign_fu_1285_p2, "res_0_V_write_assign_fu_1285_p2");
    sc_trace(mVcdFile, acc_1_V_fu_1297_p2, "acc_1_V_fu_1297_p2");
    sc_trace(mVcdFile, acc_2_V_fu_1309_p2, "acc_2_V_fu_1309_p2");
    sc_trace(mVcdFile, acc_3_V_fu_1321_p2, "acc_3_V_fu_1321_p2");
    sc_trace(mVcdFile, acc_4_V_fu_1333_p2, "acc_4_V_fu_1333_p2");
    sc_trace(mVcdFile, acc_5_V_fu_1345_p2, "acc_5_V_fu_1345_p2");
    sc_trace(mVcdFile, acc_6_V_fu_1357_p2, "acc_6_V_fu_1357_p2");
    sc_trace(mVcdFile, acc_7_V_fu_1369_p2, "acc_7_V_fu_1369_p2");
    sc_trace(mVcdFile, ap_ce_reg, "ap_ce_reg");
    sc_trace(mVcdFile, ap_return_0_int_reg, "ap_return_0_int_reg");
    sc_trace(mVcdFile, ap_return_1_int_reg, "ap_return_1_int_reg");
    sc_trace(mVcdFile, ap_return_2_int_reg, "ap_return_2_int_reg");
    sc_trace(mVcdFile, ap_return_3_int_reg, "ap_return_3_int_reg");
    sc_trace(mVcdFile, ap_return_4_int_reg, "ap_return_4_int_reg");
    sc_trace(mVcdFile, ap_return_5_int_reg, "ap_return_5_int_reg");
    sc_trace(mVcdFile, ap_return_6_int_reg, "ap_return_6_int_reg");
    sc_trace(mVcdFile, ap_return_7_int_reg, "ap_return_7_int_reg");
#endif

    }
}

dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::~dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_clk_no_reset_() {
    ap_ce_reg = ap_ce.read();
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0_int_reg = res_0_V_write_assign_fu_1285_p2.read();
        ap_return_1_int_reg = acc_1_V_fu_1297_p2.read();
        ap_return_2_int_reg = acc_2_V_fu_1309_p2.read();
        ap_return_3_int_reg = acc_3_V_fu_1321_p2.read();
        ap_return_4_int_reg = acc_4_V_fu_1333_p2.read();
        ap_return_5_int_reg = acc_5_V_fu_1345_p2.read();
        ap_return_6_int_reg = acc_6_V_fu_1357_p2.read();
        ap_return_7_int_reg = acc_7_V_fu_1369_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1))) {
        r_V_6_0_1_reg_1188 = r_V_6_0_1_fu_85_p2.read();
        r_V_6_0_2_reg_1192 = r_V_6_0_2_fu_95_p2.read();
        r_V_6_0_3_reg_1196 = r_V_6_0_3_fu_88_p2.read();
        r_V_6_0_4_reg_1200 = r_V_6_0_4_fu_83_p2.read();
        r_V_6_0_5_reg_1204 = r_V_6_0_5_fu_84_p2.read();
        r_V_6_0_6_reg_1208 = r_V_6_0_6_fu_86_p2.read();
        r_V_6_0_7_reg_1212 = r_V_6_0_7_fu_92_p2.read();
        r_V_6_1_1_reg_1220 = r_V_6_1_1_fu_82_p2.read();
        r_V_6_1_2_reg_1224 = r_V_6_1_2_fu_90_p2.read();
        r_V_6_1_3_reg_1228 = r_V_6_1_3_fu_87_p2.read();
        r_V_6_1_4_reg_1232 = r_V_6_1_4_fu_91_p2.read();
        r_V_6_1_5_reg_1236 = r_V_6_1_5_fu_93_p2.read();
        r_V_6_1_6_reg_1240 = r_V_6_1_6_fu_94_p2.read();
        r_V_6_1_7_reg_1244 = r_V_6_1_7_fu_80_p2.read();
        r_V_6_1_reg_1216 = r_V_6_1_fu_89_p2.read();
        r_V_6_reg_1184 = r_V_6_fu_81_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_1_V_fu_1297_p2() {
    acc_1_V_fu_1297_p2 = (!r_V_6_0_1_reg_1188.read().is_01() || !tmp1_fu_1291_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(r_V_6_0_1_reg_1188.read()) + sc_biguint<18>(tmp1_fu_1291_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_2_V_fu_1309_p2() {
    acc_2_V_fu_1309_p2 = (!r_V_6_0_2_reg_1192.read().is_01() || !tmp2_fu_1303_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(r_V_6_0_2_reg_1192.read()) + sc_biguint<18>(tmp2_fu_1303_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_3_V_fu_1321_p2() {
    acc_3_V_fu_1321_p2 = (!r_V_6_0_3_reg_1196.read().is_01() || !tmp3_fu_1315_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(r_V_6_0_3_reg_1196.read()) + sc_biguint<18>(tmp3_fu_1315_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_4_V_fu_1333_p2() {
    acc_4_V_fu_1333_p2 = (!r_V_6_0_4_reg_1200.read().is_01() || !tmp4_fu_1327_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(r_V_6_0_4_reg_1200.read()) + sc_biguint<18>(tmp4_fu_1327_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_5_V_fu_1345_p2() {
    acc_5_V_fu_1345_p2 = (!r_V_6_0_5_reg_1204.read().is_01() || !tmp5_fu_1339_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(r_V_6_0_5_reg_1204.read()) + sc_biguint<18>(tmp5_fu_1339_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_6_V_fu_1357_p2() {
    acc_6_V_fu_1357_p2 = (!r_V_6_0_6_reg_1208.read().is_01() || !tmp6_fu_1351_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(r_V_6_0_6_reg_1208.read()) + sc_biguint<18>(tmp6_fu_1351_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_7_V_fu_1369_p2() {
    acc_7_V_fu_1369_p2 = (!r_V_6_0_7_reg_1212.read().is_01() || !tmp7_fu_1363_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(r_V_6_0_7_reg_1212.read()) + sc_biguint<18>(tmp7_fu_1363_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_0() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_0 = ap_return_0_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0 = res_0_V_write_assign_fu_1285_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_1() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_1 = ap_return_1_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_1 = acc_1_V_fu_1297_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_2() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_2 = ap_return_2_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_2 = acc_2_V_fu_1309_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_3() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_3 = ap_return_3_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_3 = acc_3_V_fu_1321_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_4() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_4 = ap_return_4_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_4 = acc_4_V_fu_1333_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_5() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_5 = ap_return_5_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_5 = acc_5_V_fu_1345_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_6() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_6 = ap_return_6_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_6 = acc_6_V_fu_1357_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_7() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_7 = ap_return_7_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_7 = acc_7_V_fu_1369_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_1_fu_1261_p4() {
    r_V_1_fu_1261_p4 = data_V_read.read().range(49, 32);
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_0_1_fu_85_p2() {
    r_V_6_0_1_fu_85_p2 = (!ap_const_lv18_3F07D.is_01() || !tmp_28_fu_1249_p1.read().is_01())? sc_lv<18>(): sc_bigint<18>(ap_const_lv18_3F07D) * sc_bigint<18>(tmp_28_fu_1249_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_0_2_fu_95_p2() {
    r_V_6_0_2_fu_95_p2 = (!ap_const_lv18_3E06D.is_01() || !tmp_28_fu_1249_p1.read().is_01())? sc_lv<18>(): sc_bigint<18>(ap_const_lv18_3E06D) * sc_bigint<18>(tmp_28_fu_1249_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_0_3_fu_88_p2() {
    r_V_6_0_3_fu_88_p2 = (!ap_const_lv18_15A3.is_01() || !tmp_28_fu_1249_p1.read().is_01())? sc_lv<18>(): sc_biguint<18>(ap_const_lv18_15A3) * sc_bigint<18>(tmp_28_fu_1249_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_0_4_fu_83_p2() {
    r_V_6_0_4_fu_83_p2 = (!ap_const_lv18_1960.is_01() || !tmp_28_fu_1249_p1.read().is_01())? sc_lv<18>(): sc_biguint<18>(ap_const_lv18_1960) * sc_bigint<18>(tmp_28_fu_1249_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_0_5_fu_84_p2() {
    r_V_6_0_5_fu_84_p2 = (!ap_const_lv18_1FE5.is_01() || !tmp_28_fu_1249_p1.read().is_01())? sc_lv<18>(): sc_biguint<18>(ap_const_lv18_1FE5) * sc_bigint<18>(tmp_28_fu_1249_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_0_6_fu_86_p2() {
    r_V_6_0_6_fu_86_p2 = (!ap_const_lv18_365E.is_01() || !tmp_28_fu_1249_p1.read().is_01())? sc_lv<18>(): sc_biguint<18>(ap_const_lv18_365E) * sc_bigint<18>(tmp_28_fu_1249_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_0_7_fu_92_p2() {
    r_V_6_0_7_fu_92_p2 = (!ap_const_lv18_2452.is_01() || !tmp_28_fu_1249_p1.read().is_01())? sc_lv<18>(): sc_biguint<18>(ap_const_lv18_2452) * sc_bigint<18>(tmp_28_fu_1249_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_1_1_fu_82_p2() {
    r_V_6_1_1_fu_82_p2 = (!ap_const_lv18_3E12E.is_01() || !r_V_1_fu_1261_p4.read().is_01())? sc_lv<18>(): sc_bigint<18>(ap_const_lv18_3E12E) * sc_bigint<18>(r_V_1_fu_1261_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_1_2_fu_90_p2() {
    r_V_6_1_2_fu_90_p2 = (!ap_const_lv18_3ED92.is_01() || !r_V_1_fu_1261_p4.read().is_01())? sc_lv<18>(): sc_bigint<18>(ap_const_lv18_3ED92) * sc_bigint<18>(r_V_1_fu_1261_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_1_3_fu_87_p2() {
    r_V_6_1_3_fu_87_p2 = (!ap_const_lv18_13FD.is_01() || !r_V_1_fu_1261_p4.read().is_01())? sc_lv<18>(): sc_biguint<18>(ap_const_lv18_13FD) * sc_bigint<18>(r_V_1_fu_1261_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_1_4_fu_91_p2() {
    r_V_6_1_4_fu_91_p2 = (!ap_const_lv18_3D6C9.is_01() || !r_V_1_fu_1261_p4.read().is_01())? sc_lv<18>(): sc_bigint<18>(ap_const_lv18_3D6C9) * sc_bigint<18>(r_V_1_fu_1261_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_1_5_fu_93_p2() {
    r_V_6_1_5_fu_93_p2 = (!ap_const_lv18_7DF.is_01() || !r_V_1_fu_1261_p4.read().is_01())? sc_lv<18>(): sc_biguint<18>(ap_const_lv18_7DF) * sc_bigint<18>(r_V_1_fu_1261_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_1_6_fu_94_p2() {
    r_V_6_1_6_fu_94_p2 = (!ap_const_lv18_3EA8D.is_01() || !r_V_1_fu_1261_p4.read().is_01())? sc_lv<18>(): sc_bigint<18>(ap_const_lv18_3EA8D) * sc_bigint<18>(r_V_1_fu_1261_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_1_7_fu_80_p2() {
    r_V_6_1_7_fu_80_p2 = (!ap_const_lv18_3F43B.is_01() || !r_V_1_fu_1261_p4.read().is_01())? sc_lv<18>(): sc_bigint<18>(ap_const_lv18_3F43B) * sc_bigint<18>(r_V_1_fu_1261_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_1_fu_89_p2() {
    r_V_6_1_fu_89_p2 = (!ap_const_lv18_1308.is_01() || !r_V_1_fu_1261_p4.read().is_01())? sc_lv<18>(): sc_biguint<18>(ap_const_lv18_1308) * sc_bigint<18>(r_V_1_fu_1261_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_6_fu_81_p2() {
    r_V_6_fu_81_p2 = (!ap_const_lv18_3EDF4.is_01() || !tmp_28_fu_1249_p1.read().is_01())? sc_lv<18>(): sc_bigint<18>(ap_const_lv18_3EDF4) * sc_bigint<18>(tmp_28_fu_1249_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_res_0_V_write_assign_fu_1285_p2() {
    res_0_V_write_assign_fu_1285_p2 = (!r_V_6_reg_1184.read().is_01() || !tmp_fu_1279_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(r_V_6_reg_1184.read()) + sc_biguint<18>(tmp_fu_1279_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp1_fu_1291_p2() {
    tmp1_fu_1291_p2 = (!ap_const_lv18_6FA.is_01() || !r_V_6_1_1_reg_1220.read().is_01())? sc_lv<18>(): (sc_biguint<18>(ap_const_lv18_6FA) + sc_biguint<18>(r_V_6_1_1_reg_1220.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp2_fu_1303_p2() {
    tmp2_fu_1303_p2 = (!ap_const_lv18_F08.is_01() || !r_V_6_1_2_reg_1224.read().is_01())? sc_lv<18>(): (sc_biguint<18>(ap_const_lv18_F08) + sc_biguint<18>(r_V_6_1_2_reg_1224.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp3_fu_1315_p2() {
    tmp3_fu_1315_p2 = (!ap_const_lv18_145D.is_01() || !r_V_6_1_3_reg_1228.read().is_01())? sc_lv<18>(): (sc_biguint<18>(ap_const_lv18_145D) + sc_biguint<18>(r_V_6_1_3_reg_1228.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp4_fu_1327_p2() {
    tmp4_fu_1327_p2 = (!ap_const_lv18_3F5A9.is_01() || !r_V_6_1_4_reg_1232.read().is_01())? sc_lv<18>(): (sc_bigint<18>(ap_const_lv18_3F5A9) + sc_biguint<18>(r_V_6_1_4_reg_1232.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp5_fu_1339_p2() {
    tmp5_fu_1339_p2 = (!ap_const_lv18_3FCF6.is_01() || !r_V_6_1_5_reg_1236.read().is_01())? sc_lv<18>(): (sc_bigint<18>(ap_const_lv18_3FCF6) + sc_biguint<18>(r_V_6_1_5_reg_1236.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp6_fu_1351_p2() {
    tmp6_fu_1351_p2 = (!ap_const_lv18_26C.is_01() || !r_V_6_1_6_reg_1240.read().is_01())? sc_lv<18>(): (sc_biguint<18>(ap_const_lv18_26C) + sc_biguint<18>(r_V_6_1_6_reg_1240.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp7_fu_1363_p2() {
    tmp7_fu_1363_p2 = (!ap_const_lv18_3FA86.is_01() || !r_V_6_1_7_reg_1244.read().is_01())? sc_lv<18>(): (sc_bigint<18>(ap_const_lv18_3FA86) + sc_biguint<18>(r_V_6_1_7_reg_1244.read()));
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp_28_fu_1249_p1() {
    tmp_28_fu_1249_p1 = data_V_read.read().range(18-1, 0);
}

void dense_latency_ap_fixed_ap_fixed_18_4_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp_fu_1279_p2() {
    tmp_fu_1279_p2 = (!ap_const_lv18_9D9.is_01() || !r_V_6_1_reg_1216.read().is_01())? sc_lv<18>(): (sc_biguint<18>(ap_const_lv18_9D9) + sc_biguint<18>(r_V_6_1_reg_1216.read()));
}

}

