// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_logic_0 = sc_dt::Log_0;
const bool dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_boolean_1 = true;
const bool dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_boolean_0 = false;
const sc_lv<26> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv26_3FFFD6C = "11111111111111110101101100";
const sc_lv<26> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv26_3FFFE12 = "11111111111111111000010010";
const sc_lv<26> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv26_15A = "101011010";
const sc_lv<26> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv26_245 = "1001000101";
const sc_lv<26> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv26_196 = "110010110";
const sc_lv<25> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv25_1FFFF07 = "1111111111111111100000111";
const sc_lv<26> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv26_365 = "1101100101";
const sc_lv<26> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv26_13F = "100111111";
const sc_lv<26> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv26_3FFFE06 = "11111111111111111000000110";
const sc_lv<26> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv26_130 = "100110000";
const sc_lv<26> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv26_3FFFED9 = "11111111111111111011011001";
const sc_lv<26> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv26_3FFFEDF = "11111111111111111011011111";
const sc_lv<26> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv26_3FFFEA8 = "11111111111111111010101000";
const sc_lv<25> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv25_1FFFF43 = "1111111111111111101000011";
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv24_7D = "1111101";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv32_A = "1010";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv32_19 = "11001";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv32_18 = "11000";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv32_10 = "10000";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv32_1F = "11111";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv32_17 = "10111";
const sc_lv<9> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv9_0 = "000000000";
const sc_lv<1> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv1_0 = "0";
const sc_lv<16> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv16_9D = "10011101";
const sc_lv<16> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv16_6F = "1101111";
const sc_lv<16> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv16_F0 = "11110000";
const sc_lv<16> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv16_145 = "101000101";
const sc_lv<16> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv16_FF5A = "1111111101011010";
const sc_lv<15> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv15_7FCF = "111111111001111";
const sc_lv<16> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv16_26 = "100110";
const sc_lv<16> dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::ap_const_lv16_FFA8 = "1111111110101000";

dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_1_V_fu_1441_p2);
    sensitive << ( tmp_28_fu_1379_p1 );
    sensitive << ( tmp3_fu_1436_p2 );

    SC_METHOD(thread_acc_2_V_fu_1452_p2);
    sensitive << ( tmp_33_0_2_reg_1578 );
    sensitive << ( tmp4_fu_1447_p2 );

    SC_METHOD(thread_acc_3_V_fu_1462_p2);
    sensitive << ( tmp_33_0_3_reg_1583 );
    sensitive << ( tmp5_fu_1457_p2 );

    SC_METHOD(thread_acc_4_V_fu_1472_p2);
    sensitive << ( tmp_33_0_4_reg_1588 );
    sensitive << ( tmp6_fu_1467_p2 );

    SC_METHOD(thread_acc_5_V_fu_1487_p2);
    sensitive << ( tmp_33_0_5_fu_1410_p4 );
    sensitive << ( tmp7_cast_fu_1483_p1 );

    SC_METHOD(thread_acc_6_V_fu_1498_p2);
    sensitive << ( tmp_33_0_6_reg_1593 );
    sensitive << ( tmp8_fu_1493_p2 );

    SC_METHOD(thread_acc_7_V_fu_1509_p2);
    sensitive << ( tmp_33_0_7_reg_1598 );
    sensitive << ( tmp9_fu_1503_p2 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( res_0_V_write_assign_fu_1431_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_0_int_reg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( acc_1_V_fu_1441_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_1_int_reg );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( acc_2_V_fu_1452_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_2_int_reg );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( acc_3_V_fu_1462_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_3_int_reg );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( acc_4_V_fu_1472_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_4_int_reg );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( acc_5_V_fu_1487_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_5_int_reg );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( acc_6_V_fu_1498_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_6_int_reg );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( acc_7_V_fu_1509_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_7_int_reg );

    SC_METHOD(thread_p_shl1_cast_fu_1400_p1);
    sensitive << ( p_shl1_fu_1393_p3 );

    SC_METHOD(thread_p_shl1_fu_1393_p3);
    sensitive << ( tmp_reg_1562 );

    SC_METHOD(thread_p_shl_cast_fu_1389_p1);
    sensitive << ( p_shl_fu_1382_p3 );

    SC_METHOD(thread_p_shl_fu_1382_p3);
    sensitive << ( tmp_reg_1562 );

    SC_METHOD(thread_r_V_10_0_1_fu_104_p1);
    sensitive << ( tmp_fu_1180_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_r_V_10_0_1_fu_104_p2);
    sensitive << ( r_V_10_0_1_fu_104_p1 );

    SC_METHOD(thread_r_V_10_0_2_fu_107_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( r_V_cast3_fu_1184_p1 );

    SC_METHOD(thread_r_V_10_0_2_fu_107_p2);
    sensitive << ( r_V_10_0_2_fu_107_p1 );

    SC_METHOD(thread_r_V_10_0_3_fu_101_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( r_V_cast3_fu_1184_p1 );

    SC_METHOD(thread_r_V_10_0_3_fu_101_p2);
    sensitive << ( r_V_10_0_3_fu_101_p1 );

    SC_METHOD(thread_r_V_10_0_4_fu_103_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( r_V_cast3_fu_1184_p1 );

    SC_METHOD(thread_r_V_10_0_4_fu_103_p2);
    sensitive << ( r_V_10_0_4_fu_103_p1 );

    SC_METHOD(thread_r_V_10_0_5_fu_1404_p2);
    sensitive << ( p_shl_cast_fu_1389_p1 );
    sensitive << ( p_shl1_cast_fu_1400_p1 );

    SC_METHOD(thread_r_V_10_0_6_fu_105_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( r_V_cast3_fu_1184_p1 );

    SC_METHOD(thread_r_V_10_0_6_fu_105_p2);
    sensitive << ( r_V_10_0_6_fu_105_p1 );

    SC_METHOD(thread_r_V_10_0_7_fu_102_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( r_V_cast3_fu_1184_p1 );

    SC_METHOD(thread_r_V_10_0_7_fu_102_p2);
    sensitive << ( r_V_10_0_7_fu_102_p1 );

    SC_METHOD(thread_r_V_10_1_1_fu_99_p1);
    sensitive << ( r_V_1_cast_fu_1289_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_r_V_10_1_1_fu_99_p2);
    sensitive << ( r_V_10_1_1_fu_99_p1 );

    SC_METHOD(thread_r_V_10_1_2_fu_109_p1);
    sensitive << ( r_V_1_cast_fu_1289_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_r_V_10_1_2_fu_109_p2);
    sensitive << ( r_V_10_1_2_fu_109_p1 );

    SC_METHOD(thread_r_V_10_1_3_fu_106_p1);
    sensitive << ( r_V_1_cast_fu_1289_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_r_V_10_1_3_fu_106_p2);
    sensitive << ( r_V_10_1_3_fu_106_p1 );

    SC_METHOD(thread_r_V_10_1_4_fu_98_p1);
    sensitive << ( r_V_1_cast_fu_1289_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_r_V_10_1_4_fu_98_p2);
    sensitive << ( r_V_10_1_4_fu_98_p1 );

    SC_METHOD(thread_r_V_10_1_5_fu_113_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_fu_1269_p4 );

    SC_METHOD(thread_r_V_10_1_5_fu_113_p2);
    sensitive << ( r_V_10_1_5_fu_113_p1 );

    SC_METHOD(thread_r_V_10_1_6_fu_111_p1);
    sensitive << ( r_V_1_cast_fu_1289_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_r_V_10_1_6_fu_111_p2);
    sensitive << ( r_V_10_1_6_fu_111_p1 );

    SC_METHOD(thread_r_V_10_1_7_fu_112_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_fu_1269_p4 );

    SC_METHOD(thread_r_V_10_1_7_fu_112_p2);
    sensitive << ( r_V_10_1_7_fu_112_p1 );

    SC_METHOD(thread_r_V_10_1_fu_108_p1);
    sensitive << ( r_V_1_cast_fu_1289_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_r_V_10_1_fu_108_p2);
    sensitive << ( r_V_10_1_fu_108_p1 );

    SC_METHOD(thread_r_V_1_cast_fu_1289_p1);
    sensitive << ( tmp_2_fu_1269_p4 );

    SC_METHOD(thread_r_V_cast3_fu_1184_p1);
    sensitive << ( tmp_fu_1180_p1 );

    SC_METHOD(thread_r_V_s_fu_110_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( r_V_cast3_fu_1184_p1 );

    SC_METHOD(thread_r_V_s_fu_110_p2);
    sensitive << ( r_V_s_fu_110_p1 );

    SC_METHOD(thread_res_0_V_write_assign_fu_1431_p2);
    sensitive << ( tmp_3_reg_1568 );
    sensitive << ( tmp2_fu_1426_p2 );

    SC_METHOD(thread_tmp2_fu_1426_p2);
    sensitive << ( tmp_33_1_reg_1603 );

    SC_METHOD(thread_tmp3_fu_1436_p2);
    sensitive << ( tmp_33_1_1_reg_1608 );

    SC_METHOD(thread_tmp4_fu_1447_p2);
    sensitive << ( tmp_33_1_2_reg_1613 );

    SC_METHOD(thread_tmp5_fu_1457_p2);
    sensitive << ( tmp_33_1_3_reg_1618 );

    SC_METHOD(thread_tmp6_fu_1467_p2);
    sensitive << ( tmp_33_1_4_reg_1623 );

    SC_METHOD(thread_tmp7_cast_fu_1483_p1);
    sensitive << ( tmp7_fu_1477_p2 );

    SC_METHOD(thread_tmp7_fu_1477_p2);
    sensitive << ( tmp_32_cast_fu_1420_p1 );

    SC_METHOD(thread_tmp8_fu_1493_p2);
    sensitive << ( tmp_33_1_6_reg_1633 );

    SC_METHOD(thread_tmp9_fu_1503_p2);
    sensitive << ( tmp_30_fu_1423_p1 );

    SC_METHOD(thread_tmp_28_fu_1379_p1);
    sensitive << ( tmp_s_reg_1573 );

    SC_METHOD(thread_tmp_2_fu_1269_p4);
    sensitive << ( data_V_read );

    SC_METHOD(thread_tmp_30_fu_1423_p1);
    sensitive << ( tmp_29_reg_1638 );

    SC_METHOD(thread_tmp_32_cast_fu_1420_p1);
    sensitive << ( tmp_36_reg_1628 );

    SC_METHOD(thread_tmp_33_0_5_fu_1410_p4);
    sensitive << ( r_V_10_0_5_fu_1404_p2 );

    SC_METHOD(thread_tmp_fu_1180_p1);
    sensitive << ( data_V_read );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, data_V_read, "(port)data_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, tmp_fu_1180_p1, "tmp_fu_1180_p1");
    sc_trace(mVcdFile, tmp_reg_1562, "tmp_reg_1562");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, tmp_3_reg_1568, "tmp_3_reg_1568");
    sc_trace(mVcdFile, tmp_s_reg_1573, "tmp_s_reg_1573");
    sc_trace(mVcdFile, tmp_33_0_2_reg_1578, "tmp_33_0_2_reg_1578");
    sc_trace(mVcdFile, tmp_33_0_3_reg_1583, "tmp_33_0_3_reg_1583");
    sc_trace(mVcdFile, tmp_33_0_4_reg_1588, "tmp_33_0_4_reg_1588");
    sc_trace(mVcdFile, tmp_33_0_6_reg_1593, "tmp_33_0_6_reg_1593");
    sc_trace(mVcdFile, tmp_33_0_7_reg_1598, "tmp_33_0_7_reg_1598");
    sc_trace(mVcdFile, tmp_33_1_reg_1603, "tmp_33_1_reg_1603");
    sc_trace(mVcdFile, tmp_33_1_1_reg_1608, "tmp_33_1_1_reg_1608");
    sc_trace(mVcdFile, tmp_33_1_2_reg_1613, "tmp_33_1_2_reg_1613");
    sc_trace(mVcdFile, tmp_33_1_3_reg_1618, "tmp_33_1_3_reg_1618");
    sc_trace(mVcdFile, tmp_33_1_4_reg_1623, "tmp_33_1_4_reg_1623");
    sc_trace(mVcdFile, tmp_36_reg_1628, "tmp_36_reg_1628");
    sc_trace(mVcdFile, tmp_33_1_6_reg_1633, "tmp_33_1_6_reg_1633");
    sc_trace(mVcdFile, tmp_29_reg_1638, "tmp_29_reg_1638");
    sc_trace(mVcdFile, r_V_10_1_4_fu_98_p1, "r_V_10_1_4_fu_98_p1");
    sc_trace(mVcdFile, r_V_1_cast_fu_1289_p1, "r_V_1_cast_fu_1289_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, r_V_10_1_1_fu_99_p1, "r_V_10_1_1_fu_99_p1");
    sc_trace(mVcdFile, r_V_10_0_3_fu_101_p1, "r_V_10_0_3_fu_101_p1");
    sc_trace(mVcdFile, r_V_cast3_fu_1184_p1, "r_V_cast3_fu_1184_p1");
    sc_trace(mVcdFile, r_V_10_0_7_fu_102_p1, "r_V_10_0_7_fu_102_p1");
    sc_trace(mVcdFile, r_V_10_0_4_fu_103_p1, "r_V_10_0_4_fu_103_p1");
    sc_trace(mVcdFile, r_V_10_0_1_fu_104_p1, "r_V_10_0_1_fu_104_p1");
    sc_trace(mVcdFile, r_V_10_0_6_fu_105_p1, "r_V_10_0_6_fu_105_p1");
    sc_trace(mVcdFile, r_V_10_1_3_fu_106_p1, "r_V_10_1_3_fu_106_p1");
    sc_trace(mVcdFile, r_V_10_0_2_fu_107_p1, "r_V_10_0_2_fu_107_p1");
    sc_trace(mVcdFile, r_V_10_1_fu_108_p1, "r_V_10_1_fu_108_p1");
    sc_trace(mVcdFile, r_V_10_1_2_fu_109_p1, "r_V_10_1_2_fu_109_p1");
    sc_trace(mVcdFile, r_V_s_fu_110_p1, "r_V_s_fu_110_p1");
    sc_trace(mVcdFile, r_V_10_1_6_fu_111_p1, "r_V_10_1_6_fu_111_p1");
    sc_trace(mVcdFile, r_V_10_1_7_fu_112_p1, "r_V_10_1_7_fu_112_p1");
    sc_trace(mVcdFile, r_V_10_1_5_fu_113_p1, "r_V_10_1_5_fu_113_p1");
    sc_trace(mVcdFile, r_V_s_fu_110_p2, "r_V_s_fu_110_p2");
    sc_trace(mVcdFile, r_V_10_0_1_fu_104_p2, "r_V_10_0_1_fu_104_p2");
    sc_trace(mVcdFile, r_V_10_0_2_fu_107_p2, "r_V_10_0_2_fu_107_p2");
    sc_trace(mVcdFile, r_V_10_0_3_fu_101_p2, "r_V_10_0_3_fu_101_p2");
    sc_trace(mVcdFile, r_V_10_0_4_fu_103_p2, "r_V_10_0_4_fu_103_p2");
    sc_trace(mVcdFile, r_V_10_0_6_fu_105_p2, "r_V_10_0_6_fu_105_p2");
    sc_trace(mVcdFile, r_V_10_0_7_fu_102_p2, "r_V_10_0_7_fu_102_p2");
    sc_trace(mVcdFile, tmp_2_fu_1269_p4, "tmp_2_fu_1269_p4");
    sc_trace(mVcdFile, r_V_10_1_fu_108_p2, "r_V_10_1_fu_108_p2");
    sc_trace(mVcdFile, r_V_10_1_1_fu_99_p2, "r_V_10_1_1_fu_99_p2");
    sc_trace(mVcdFile, r_V_10_1_2_fu_109_p2, "r_V_10_1_2_fu_109_p2");
    sc_trace(mVcdFile, r_V_10_1_3_fu_106_p2, "r_V_10_1_3_fu_106_p2");
    sc_trace(mVcdFile, r_V_10_1_4_fu_98_p2, "r_V_10_1_4_fu_98_p2");
    sc_trace(mVcdFile, r_V_10_1_5_fu_113_p2, "r_V_10_1_5_fu_113_p2");
    sc_trace(mVcdFile, r_V_10_1_6_fu_111_p2, "r_V_10_1_6_fu_111_p2");
    sc_trace(mVcdFile, r_V_10_1_7_fu_112_p2, "r_V_10_1_7_fu_112_p2");
    sc_trace(mVcdFile, p_shl_fu_1382_p3, "p_shl_fu_1382_p3");
    sc_trace(mVcdFile, p_shl1_fu_1393_p3, "p_shl1_fu_1393_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_1389_p1, "p_shl_cast_fu_1389_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_1400_p1, "p_shl1_cast_fu_1400_p1");
    sc_trace(mVcdFile, r_V_10_0_5_fu_1404_p2, "r_V_10_0_5_fu_1404_p2");
    sc_trace(mVcdFile, tmp2_fu_1426_p2, "tmp2_fu_1426_p2");
    sc_trace(mVcdFile, tmp_28_fu_1379_p1, "tmp_28_fu_1379_p1");
    sc_trace(mVcdFile, tmp3_fu_1436_p2, "tmp3_fu_1436_p2");
    sc_trace(mVcdFile, tmp4_fu_1447_p2, "tmp4_fu_1447_p2");
    sc_trace(mVcdFile, tmp5_fu_1457_p2, "tmp5_fu_1457_p2");
    sc_trace(mVcdFile, tmp6_fu_1467_p2, "tmp6_fu_1467_p2");
    sc_trace(mVcdFile, tmp_32_cast_fu_1420_p1, "tmp_32_cast_fu_1420_p1");
    sc_trace(mVcdFile, tmp7_fu_1477_p2, "tmp7_fu_1477_p2");
    sc_trace(mVcdFile, tmp_33_0_5_fu_1410_p4, "tmp_33_0_5_fu_1410_p4");
    sc_trace(mVcdFile, tmp7_cast_fu_1483_p1, "tmp7_cast_fu_1483_p1");
    sc_trace(mVcdFile, tmp8_fu_1493_p2, "tmp8_fu_1493_p2");
    sc_trace(mVcdFile, tmp_30_fu_1423_p1, "tmp_30_fu_1423_p1");
    sc_trace(mVcdFile, tmp9_fu_1503_p2, "tmp9_fu_1503_p2");
    sc_trace(mVcdFile, res_0_V_write_assign_fu_1431_p2, "res_0_V_write_assign_fu_1431_p2");
    sc_trace(mVcdFile, acc_1_V_fu_1441_p2, "acc_1_V_fu_1441_p2");
    sc_trace(mVcdFile, acc_2_V_fu_1452_p2, "acc_2_V_fu_1452_p2");
    sc_trace(mVcdFile, acc_3_V_fu_1462_p2, "acc_3_V_fu_1462_p2");
    sc_trace(mVcdFile, acc_4_V_fu_1472_p2, "acc_4_V_fu_1472_p2");
    sc_trace(mVcdFile, acc_5_V_fu_1487_p2, "acc_5_V_fu_1487_p2");
    sc_trace(mVcdFile, acc_6_V_fu_1498_p2, "acc_6_V_fu_1498_p2");
    sc_trace(mVcdFile, acc_7_V_fu_1509_p2, "acc_7_V_fu_1509_p2");
    sc_trace(mVcdFile, ap_ce_reg, "ap_ce_reg");
    sc_trace(mVcdFile, ap_return_0_int_reg, "ap_return_0_int_reg");
    sc_trace(mVcdFile, ap_return_1_int_reg, "ap_return_1_int_reg");
    sc_trace(mVcdFile, ap_return_2_int_reg, "ap_return_2_int_reg");
    sc_trace(mVcdFile, ap_return_3_int_reg, "ap_return_3_int_reg");
    sc_trace(mVcdFile, ap_return_4_int_reg, "ap_return_4_int_reg");
    sc_trace(mVcdFile, ap_return_5_int_reg, "ap_return_5_int_reg");
    sc_trace(mVcdFile, ap_return_6_int_reg, "ap_return_6_int_reg");
    sc_trace(mVcdFile, ap_return_7_int_reg, "ap_return_7_int_reg");
#endif

    }
}

dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::~dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_clk_no_reset_() {
    ap_ce_reg = ap_ce.read();
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0_int_reg = res_0_V_write_assign_fu_1431_p2.read();
        ap_return_1_int_reg = acc_1_V_fu_1441_p2.read();
        ap_return_2_int_reg = acc_2_V_fu_1452_p2.read();
        ap_return_3_int_reg = acc_3_V_fu_1462_p2.read();
        ap_return_4_int_reg = acc_4_V_fu_1472_p2.read();
        ap_return_5_int_reg = acc_5_V_fu_1487_p2.read();
        ap_return_6_int_reg = acc_6_V_fu_1498_p2.read();
        ap_return_7_int_reg = acc_7_V_fu_1509_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1))) {
        tmp_29_reg_1638 = r_V_10_1_7_fu_112_p2.read().range(24, 10);
        tmp_33_0_2_reg_1578 = r_V_10_0_2_fu_107_p2.read().range(25, 10);
        tmp_33_0_3_reg_1583 = r_V_10_0_3_fu_101_p2.read().range(25, 10);
        tmp_33_0_4_reg_1588 = r_V_10_0_4_fu_103_p2.read().range(25, 10);
        tmp_33_0_6_reg_1593 = r_V_10_0_6_fu_105_p2.read().range(25, 10);
        tmp_33_0_7_reg_1598 = r_V_10_0_7_fu_102_p2.read().range(25, 10);
        tmp_33_1_1_reg_1608 = r_V_10_1_1_fu_99_p2.read().range(25, 10);
        tmp_33_1_2_reg_1613 = r_V_10_1_2_fu_109_p2.read().range(25, 10);
        tmp_33_1_3_reg_1618 = r_V_10_1_3_fu_106_p2.read().range(25, 10);
        tmp_33_1_4_reg_1623 = r_V_10_1_4_fu_98_p2.read().range(25, 10);
        tmp_33_1_6_reg_1633 = r_V_10_1_6_fu_111_p2.read().range(25, 10);
        tmp_33_1_reg_1603 = r_V_10_1_fu_108_p2.read().range(25, 10);
        tmp_36_reg_1628 = r_V_10_1_5_fu_113_p2.read().range(23, 10);
        tmp_3_reg_1568 = r_V_s_fu_110_p2.read().range(25, 10);
        tmp_reg_1562 = tmp_fu_1180_p1.read();
        tmp_s_reg_1573 = r_V_10_0_1_fu_104_p2.read().range(24, 10);
    }
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_1_V_fu_1441_p2() {
    acc_1_V_fu_1441_p2 = (!tmp_28_fu_1379_p1.read().is_01() || !tmp3_fu_1436_p2.read().is_01())? sc_lv<16>(): (sc_bigint<16>(tmp_28_fu_1379_p1.read()) + sc_biguint<16>(tmp3_fu_1436_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_2_V_fu_1452_p2() {
    acc_2_V_fu_1452_p2 = (!tmp_33_0_2_reg_1578.read().is_01() || !tmp4_fu_1447_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_33_0_2_reg_1578.read()) + sc_biguint<16>(tmp4_fu_1447_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_3_V_fu_1462_p2() {
    acc_3_V_fu_1462_p2 = (!tmp_33_0_3_reg_1583.read().is_01() || !tmp5_fu_1457_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_33_0_3_reg_1583.read()) + sc_biguint<16>(tmp5_fu_1457_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_4_V_fu_1472_p2() {
    acc_4_V_fu_1472_p2 = (!tmp_33_0_4_reg_1588.read().is_01() || !tmp6_fu_1467_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_33_0_4_reg_1588.read()) + sc_biguint<16>(tmp6_fu_1467_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_5_V_fu_1487_p2() {
    acc_5_V_fu_1487_p2 = (!tmp_33_0_5_fu_1410_p4.read().is_01() || !tmp7_cast_fu_1483_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_33_0_5_fu_1410_p4.read()) + sc_bigint<16>(tmp7_cast_fu_1483_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_6_V_fu_1498_p2() {
    acc_6_V_fu_1498_p2 = (!tmp_33_0_6_reg_1593.read().is_01() || !tmp8_fu_1493_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_33_0_6_reg_1593.read()) + sc_biguint<16>(tmp8_fu_1493_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_acc_7_V_fu_1509_p2() {
    acc_7_V_fu_1509_p2 = (!tmp_33_0_7_reg_1598.read().is_01() || !tmp9_fu_1503_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_33_0_7_reg_1598.read()) + sc_biguint<16>(tmp9_fu_1503_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_0() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_0 = ap_return_0_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0 = res_0_V_write_assign_fu_1431_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_1() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_1 = ap_return_1_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_1 = acc_1_V_fu_1441_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_2() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_2 = ap_return_2_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_2 = acc_2_V_fu_1452_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_3() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_3 = ap_return_3_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_3 = acc_3_V_fu_1462_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_4() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_4 = ap_return_4_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_4 = acc_4_V_fu_1472_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_5() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_5 = ap_return_5_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_5 = acc_5_V_fu_1487_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_6() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_6 = ap_return_6_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_6 = acc_6_V_fu_1498_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_ap_return_7() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_7 = ap_return_7_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_7 = acc_7_V_fu_1509_p2.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_p_shl1_cast_fu_1400_p1() {
    p_shl1_cast_fu_1400_p1 = esl_sext<26,17>(p_shl1_fu_1393_p3.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_p_shl1_fu_1393_p3() {
    p_shl1_fu_1393_p3 = esl_concat<16,1>(tmp_reg_1562.read(), ap_const_lv1_0);
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_p_shl_cast_fu_1389_p1() {
    p_shl_cast_fu_1389_p1 = esl_sext<26,25>(p_shl_fu_1382_p3.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_p_shl_fu_1382_p3() {
    p_shl_fu_1382_p3 = esl_concat<16,9>(tmp_reg_1562.read(), ap_const_lv9_0);
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_0_1_fu_104_p1() {
    r_V_10_0_1_fu_104_p1 = tmp_fu_1180_p1.read();
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_0_1_fu_104_p2() {
    r_V_10_0_1_fu_104_p2 = (!ap_const_lv25_1FFFF07.is_01() || !r_V_10_0_1_fu_104_p1.read().is_01())? sc_lv<25>(): sc_bigint<25>(ap_const_lv25_1FFFF07) * sc_bigint<16>(r_V_10_0_1_fu_104_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_0_2_fu_107_p1() {
    r_V_10_0_2_fu_107_p1 =  (sc_lv<16>) (r_V_cast3_fu_1184_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_0_2_fu_107_p2() {
    r_V_10_0_2_fu_107_p2 = (!ap_const_lv26_3FFFE06.is_01() || !r_V_10_0_2_fu_107_p1.read().is_01())? sc_lv<26>(): sc_bigint<26>(ap_const_lv26_3FFFE06) * sc_bigint<16>(r_V_10_0_2_fu_107_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_0_3_fu_101_p1() {
    r_V_10_0_3_fu_101_p1 =  (sc_lv<16>) (r_V_cast3_fu_1184_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_0_3_fu_101_p2() {
    r_V_10_0_3_fu_101_p2 = (!ap_const_lv26_15A.is_01() || !r_V_10_0_3_fu_101_p1.read().is_01())? sc_lv<26>(): sc_biguint<26>(ap_const_lv26_15A) * sc_bigint<16>(r_V_10_0_3_fu_101_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_0_4_fu_103_p1() {
    r_V_10_0_4_fu_103_p1 =  (sc_lv<16>) (r_V_cast3_fu_1184_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_0_4_fu_103_p2() {
    r_V_10_0_4_fu_103_p2 = (!ap_const_lv26_196.is_01() || !r_V_10_0_4_fu_103_p1.read().is_01())? sc_lv<26>(): sc_biguint<26>(ap_const_lv26_196) * sc_bigint<16>(r_V_10_0_4_fu_103_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_0_5_fu_1404_p2() {
    r_V_10_0_5_fu_1404_p2 = (!p_shl_cast_fu_1389_p1.read().is_01() || !p_shl1_cast_fu_1400_p1.read().is_01())? sc_lv<26>(): (sc_bigint<26>(p_shl_cast_fu_1389_p1.read()) - sc_bigint<26>(p_shl1_cast_fu_1400_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_0_6_fu_105_p1() {
    r_V_10_0_6_fu_105_p1 =  (sc_lv<16>) (r_V_cast3_fu_1184_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_0_6_fu_105_p2() {
    r_V_10_0_6_fu_105_p2 = (!ap_const_lv26_365.is_01() || !r_V_10_0_6_fu_105_p1.read().is_01())? sc_lv<26>(): sc_biguint<26>(ap_const_lv26_365) * sc_bigint<16>(r_V_10_0_6_fu_105_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_0_7_fu_102_p1() {
    r_V_10_0_7_fu_102_p1 =  (sc_lv<16>) (r_V_cast3_fu_1184_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_0_7_fu_102_p2() {
    r_V_10_0_7_fu_102_p2 = (!ap_const_lv26_245.is_01() || !r_V_10_0_7_fu_102_p1.read().is_01())? sc_lv<26>(): sc_biguint<26>(ap_const_lv26_245) * sc_bigint<16>(r_V_10_0_7_fu_102_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_1_fu_99_p1() {
    r_V_10_1_1_fu_99_p1 =  (sc_lv<16>) (r_V_1_cast_fu_1289_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_1_fu_99_p2() {
    r_V_10_1_1_fu_99_p2 = (!ap_const_lv26_3FFFE12.is_01() || !r_V_10_1_1_fu_99_p1.read().is_01())? sc_lv<26>(): sc_bigint<26>(ap_const_lv26_3FFFE12) * sc_bigint<16>(r_V_10_1_1_fu_99_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_2_fu_109_p1() {
    r_V_10_1_2_fu_109_p1 =  (sc_lv<16>) (r_V_1_cast_fu_1289_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_2_fu_109_p2() {
    r_V_10_1_2_fu_109_p2 = (!ap_const_lv26_3FFFED9.is_01() || !r_V_10_1_2_fu_109_p1.read().is_01())? sc_lv<26>(): sc_bigint<26>(ap_const_lv26_3FFFED9) * sc_bigint<16>(r_V_10_1_2_fu_109_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_3_fu_106_p1() {
    r_V_10_1_3_fu_106_p1 =  (sc_lv<16>) (r_V_1_cast_fu_1289_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_3_fu_106_p2() {
    r_V_10_1_3_fu_106_p2 = (!ap_const_lv26_13F.is_01() || !r_V_10_1_3_fu_106_p1.read().is_01())? sc_lv<26>(): sc_biguint<26>(ap_const_lv26_13F) * sc_bigint<16>(r_V_10_1_3_fu_106_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_4_fu_98_p1() {
    r_V_10_1_4_fu_98_p1 =  (sc_lv<16>) (r_V_1_cast_fu_1289_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_4_fu_98_p2() {
    r_V_10_1_4_fu_98_p2 = (!ap_const_lv26_3FFFD6C.is_01() || !r_V_10_1_4_fu_98_p1.read().is_01())? sc_lv<26>(): sc_bigint<26>(ap_const_lv26_3FFFD6C) * sc_bigint<16>(r_V_10_1_4_fu_98_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_5_fu_113_p1() {
    r_V_10_1_5_fu_113_p1 = tmp_2_fu_1269_p4.read();
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_5_fu_113_p2() {
    r_V_10_1_5_fu_113_p2 = (!ap_const_lv24_7D.is_01() || !r_V_10_1_5_fu_113_p1.read().is_01())? sc_lv<24>(): sc_biguint<24>(ap_const_lv24_7D) * sc_bigint<16>(r_V_10_1_5_fu_113_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_6_fu_111_p1() {
    r_V_10_1_6_fu_111_p1 =  (sc_lv<16>) (r_V_1_cast_fu_1289_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_6_fu_111_p2() {
    r_V_10_1_6_fu_111_p2 = (!ap_const_lv26_3FFFEA8.is_01() || !r_V_10_1_6_fu_111_p1.read().is_01())? sc_lv<26>(): sc_bigint<26>(ap_const_lv26_3FFFEA8) * sc_bigint<16>(r_V_10_1_6_fu_111_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_7_fu_112_p1() {
    r_V_10_1_7_fu_112_p1 = tmp_2_fu_1269_p4.read();
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_7_fu_112_p2() {
    r_V_10_1_7_fu_112_p2 = (!ap_const_lv25_1FFFF43.is_01() || !r_V_10_1_7_fu_112_p1.read().is_01())? sc_lv<25>(): sc_bigint<25>(ap_const_lv25_1FFFF43) * sc_bigint<16>(r_V_10_1_7_fu_112_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_fu_108_p1() {
    r_V_10_1_fu_108_p1 =  (sc_lv<16>) (r_V_1_cast_fu_1289_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_10_1_fu_108_p2() {
    r_V_10_1_fu_108_p2 = (!ap_const_lv26_130.is_01() || !r_V_10_1_fu_108_p1.read().is_01())? sc_lv<26>(): sc_biguint<26>(ap_const_lv26_130) * sc_bigint<16>(r_V_10_1_fu_108_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_1_cast_fu_1289_p1() {
    r_V_1_cast_fu_1289_p1 = esl_sext<26,16>(tmp_2_fu_1269_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_cast3_fu_1184_p1() {
    r_V_cast3_fu_1184_p1 = esl_sext<26,16>(tmp_fu_1180_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_s_fu_110_p1() {
    r_V_s_fu_110_p1 =  (sc_lv<16>) (r_V_cast3_fu_1184_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_r_V_s_fu_110_p2() {
    r_V_s_fu_110_p2 = (!ap_const_lv26_3FFFEDF.is_01() || !r_V_s_fu_110_p1.read().is_01())? sc_lv<26>(): sc_bigint<26>(ap_const_lv26_3FFFEDF) * sc_bigint<16>(r_V_s_fu_110_p1.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_res_0_V_write_assign_fu_1431_p2() {
    res_0_V_write_assign_fu_1431_p2 = (!tmp_3_reg_1568.read().is_01() || !tmp2_fu_1426_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_3_reg_1568.read()) + sc_biguint<16>(tmp2_fu_1426_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp2_fu_1426_p2() {
    tmp2_fu_1426_p2 = (!ap_const_lv16_9D.is_01() || !tmp_33_1_reg_1603.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_9D) + sc_biguint<16>(tmp_33_1_reg_1603.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp3_fu_1436_p2() {
    tmp3_fu_1436_p2 = (!ap_const_lv16_6F.is_01() || !tmp_33_1_1_reg_1608.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_6F) + sc_biguint<16>(tmp_33_1_1_reg_1608.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp4_fu_1447_p2() {
    tmp4_fu_1447_p2 = (!ap_const_lv16_F0.is_01() || !tmp_33_1_2_reg_1613.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_F0) + sc_biguint<16>(tmp_33_1_2_reg_1613.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp5_fu_1457_p2() {
    tmp5_fu_1457_p2 = (!ap_const_lv16_145.is_01() || !tmp_33_1_3_reg_1618.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_145) + sc_biguint<16>(tmp_33_1_3_reg_1618.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp6_fu_1467_p2() {
    tmp6_fu_1467_p2 = (!ap_const_lv16_FF5A.is_01() || !tmp_33_1_4_reg_1623.read().is_01())? sc_lv<16>(): (sc_bigint<16>(ap_const_lv16_FF5A) + sc_biguint<16>(tmp_33_1_4_reg_1623.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp7_cast_fu_1483_p1() {
    tmp7_cast_fu_1483_p1 = esl_sext<16,15>(tmp7_fu_1477_p2.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp7_fu_1477_p2() {
    tmp7_fu_1477_p2 = (!ap_const_lv15_7FCF.is_01() || !tmp_32_cast_fu_1420_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(ap_const_lv15_7FCF) + sc_bigint<15>(tmp_32_cast_fu_1420_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp8_fu_1493_p2() {
    tmp8_fu_1493_p2 = (!ap_const_lv16_26.is_01() || !tmp_33_1_6_reg_1633.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_26) + sc_biguint<16>(tmp_33_1_6_reg_1633.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp9_fu_1503_p2() {
    tmp9_fu_1503_p2 = (!ap_const_lv16_FFA8.is_01() || !tmp_30_fu_1423_p1.read().is_01())? sc_lv<16>(): (sc_bigint<16>(ap_const_lv16_FFA8) + sc_bigint<16>(tmp_30_fu_1423_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp_28_fu_1379_p1() {
    tmp_28_fu_1379_p1 = esl_sext<16,15>(tmp_s_reg_1573.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp_2_fu_1269_p4() {
    tmp_2_fu_1269_p4 = data_V_read.read().range(31, 16);
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp_30_fu_1423_p1() {
    tmp_30_fu_1423_p1 = esl_sext<16,15>(tmp_29_reg_1638.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp_32_cast_fu_1420_p1() {
    tmp_32_cast_fu_1420_p1 = esl_sext<15,14>(tmp_36_reg_1628.read());
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp_33_0_5_fu_1410_p4() {
    tmp_33_0_5_fu_1410_p4 = r_V_10_0_5_fu_1404_p2.read().range(25, 10);
}

void dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config2_0_0_0_0_0_0_0_0_0::thread_tmp_fu_1180_p1() {
    tmp_fu_1180_p1 = data_V_read.read().range(16-1, 0);
}

}

