Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    HiddenLayer1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    HiddenLayer1_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    HiddenLayer2:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    HiddenLayer2_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    OuputLayer:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    OuputLayer_sigmoid:
      Precision:
        result: fixed<16,6>
      Trace: false
    input_2:
      Precision:
        result: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: ../Data/x_test.npy
KerasModel: !keras_model '../model_1/lbnl/keras_model.h5'
OutputDir: ../model_1/lbnl
OutputPredictions: ../Data/y_test.npy
Part: xc7vx485tffg1761-2
ProjectName: myproject
Stamp: c0F359EA
