// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0 (
        ap_clk,
        ap_rst,
        data_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] data_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;
reg[15:0] ap_return_8;
reg[15:0] ap_return_9;
reg[15:0] ap_return_10;
reg[15:0] ap_return_11;
reg[15:0] ap_return_12;
reg[15:0] ap_return_13;
reg[15:0] ap_return_14;
reg[15:0] ap_return_15;
reg[15:0] ap_return_16;
reg[15:0] ap_return_17;
reg[15:0] ap_return_18;
reg[15:0] ap_return_19;
reg[15:0] ap_return_20;
reg[15:0] ap_return_21;
reg[15:0] ap_return_22;
reg[15:0] ap_return_23;
reg[15:0] ap_return_24;
reg[15:0] ap_return_25;
reg[15:0] ap_return_26;
reg[15:0] ap_return_27;
reg[15:0] ap_return_28;
reg[15:0] ap_return_29;
reg[15:0] ap_return_30;
reg[15:0] ap_return_31;

wire  signed [15:0] tmp_fu_12943_p1;
reg  signed [15:0] tmp_reg_14678;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [13:0] tmp_s_reg_14688;
reg   [12:0] tmp_370_reg_14693;
reg   [14:0] tmp_372_reg_14698;
reg   [14:0] tmp_374_reg_14703;
reg   [13:0] tmp_378_reg_14708;
reg   [13:0] tmp_659_reg_14713;
reg   [14:0] tmp_382_reg_14718;
reg   [14:0] tmp_384_reg_14723;
reg   [14:0] tmp_386_reg_14728;
reg   [12:0] tmp_660_reg_14733;
reg   [14:0] tmp_388_reg_14738;
reg   [14:0] tmp_392_reg_14743;
reg   [14:0] tmp_394_reg_14748;
reg   [13:0] tmp_396_reg_14753;
reg   [11:0] tmp_398_reg_14758;
reg   [15:0] tmp_33_0_s_reg_14763;
reg   [15:0] tmp_33_0_1_reg_14768;
reg   [15:0] tmp_33_0_2_reg_14773;
wire   [23:0] p_neg_fu_13183_p2;
reg   [23:0] p_neg_reg_14778;
reg   [13:0] tmp_400_reg_14784;
reg   [15:0] tmp_33_0_3_reg_14789;
reg   [14:0] tmp_402_reg_14794;
reg   [15:0] tmp_33_0_4_reg_14799;
reg   [13:0] tmp_404_reg_14804;
reg   [13:0] tmp_406_reg_14809;
reg   [11:0] tmp_662_reg_14814;
reg   [13:0] tmp_412_reg_14819;
wire  signed [15:0] tmp_2_fu_13281_p4;
reg  signed [15:0] tmp_2_reg_14824;
reg   [14:0] tmp_414_reg_14834;
reg   [15:0] tmp_33_1_1_reg_14839;
reg   [15:0] tmp_33_1_2_reg_14844;
reg   [15:0] tmp_33_1_3_reg_14849;
reg   [14:0] tmp_416_reg_14854;
reg   [14:0] tmp_418_reg_14859;
reg   [15:0] tmp_33_1_7_reg_14864;
reg   [14:0] tmp_420_reg_14869;
reg   [15:0] tmp_33_1_9_reg_14874;
reg   [15:0] tmp_33_1_s_reg_14879;
wire  signed [16:0] p_shl10_fu_13427_p3;
reg  signed [16:0] p_shl10_reg_14884;
reg   [14:0] tmp_422_reg_14890;
reg   [15:0] tmp_33_1_4_reg_14895;
reg   [13:0] tmp_666_reg_14900;
reg   [14:0] tmp_425_reg_14905;
reg   [14:0] tmp_427_reg_14910;
reg   [9:0] tmp_667_reg_14915;
reg   [13:0] tmp_668_reg_14920;
reg   [13:0] tmp_669_reg_14925;
reg   [13:0] tmp_670_reg_14930;
reg   [15:0] tmp_33_1_5_reg_14935;
reg   [15:0] tmp_33_1_6_reg_14940;
reg   [13:0] tmp_672_reg_14945;
reg   [14:0] tmp_429_reg_14950;
reg   [14:0] tmp_433_reg_14955;
reg   [14:0] tmp_435_reg_14960;
wire  signed [15:0] r_V_10_0_26_fu_255_p1;
wire  signed [23:0] r_V_cast9_fu_12975_p1;
wire    ap_block_pp0_stage0;
wire  signed [15:0] r_V_10_0_15_fu_256_p1;
wire  signed [15:0] r_V_10_0_13_fu_257_p1;
wire  signed [24:0] r_V_cast4_fu_12956_p1;
wire  signed [15:0] r_V_10_1_1_fu_259_p1;
wire  signed [25:0] r_V_1_cast8_fu_13291_p1;
wire  signed [15:0] r_V_10_1_11_fu_260_p1;
wire  signed [24:0] r_V_1_cast9_fu_13304_p1;
wire  signed [15:0] r_V_10_1_fu_261_p1;
wire  signed [15:0] r_V_10_0_16_fu_262_p1;
wire  signed [21:0] r_V_cast6_fu_12969_p1;
wire  signed [15:0] r_V_10_0_23_fu_264_p1;
wire  signed [25:0] r_V_cast_fu_12947_p1;
wire  signed [15:0] r_V_10_0_22_fu_265_p1;
wire  signed [15:0] r_V_10_1_9_fu_266_p1;
wire  signed [15:0] r_V_10_1_24_fu_267_p1;
wire  signed [23:0] r_V_1_cast1_fu_13318_p1;
wire  signed [15:0] r_V_10_1_5_fu_268_p1;
wire  signed [15:0] r_V_10_0_11_fu_269_p1;
wire  signed [15:0] r_V_10_1_14_fu_270_p1;
wire  signed [15:0] r_V_10_1_12_fu_271_p1;
wire  signed [15:0] r_V_10_0_2_fu_272_p1;
wire  signed [15:0] r_V_10_0_1_fu_273_p1;
wire  signed [22:0] r_V_cast1_fu_12985_p1;
wire  signed [15:0] r_V_10_1_2_fu_275_p1;
wire  signed [15:0] r_V_10_1_22_fu_278_p1;
wire  signed [15:0] r_V_10_1_28_fu_279_p1;
wire  signed [15:0] r_V_10_0_s_fu_280_p1;
wire  signed [15:0] r_V_10_1_s_fu_283_p1;
wire  signed [15:0] r_V_10_0_5_fu_285_p1;
wire  signed [15:0] r_V_10_1_18_fu_287_p1;
wire  signed [15:0] r_V_10_1_16_fu_288_p1;
wire  signed [15:0] r_V_10_0_19_fu_290_p1;
wire  signed [15:0] r_V_10_0_17_fu_291_p1;
wire  signed [15:0] r_V_10_0_18_fu_292_p1;
wire  signed [15:0] r_V_10_0_10_fu_293_p1;
wire  signed [15:0] r_V_10_1_15_fu_294_p1;
wire  signed [15:0] r_V_s_fu_295_p1;
wire  signed [15:0] r_V_10_1_3_fu_298_p1;
wire  signed [15:0] r_V_10_1_7_fu_299_p1;
wire  signed [15:0] r_V_10_0_3_fu_300_p1;
wire  signed [15:0] r_V_10_0_29_fu_301_p1;
wire  signed [15:0] r_V_10_0_30_fu_302_p1;
wire  signed [15:0] r_V_10_1_25_fu_304_p1;
wire  signed [15:0] r_V_10_1_23_fu_305_p1;
wire  signed [15:0] r_V_10_0_14_fu_307_p1;
wire  signed [15:0] r_V_10_1_19_fu_308_p1;
wire  signed [15:0] r_V_10_0_9_fu_309_p1;
wire  signed [15:0] r_V_10_0_6_fu_310_p1;
wire  signed [15:0] r_V_10_1_4_fu_311_p1;
wire  signed [15:0] r_V_10_0_21_fu_313_p1;
wire  signed [15:0] r_V_10_1_20_fu_314_p1;
wire  signed [15:0] r_V_10_1_27_fu_315_p1;
wire  signed [15:0] r_V_10_1_8_fu_316_p1;
wire  signed [15:0] r_V_10_0_8_fu_317_p1;
wire   [23:0] r_V_s_fu_295_p2;
wire   [22:0] r_V_10_0_1_fu_273_p2;
wire   [24:0] r_V_10_0_2_fu_272_p2;
wire   [24:0] r_V_10_0_3_fu_300_p2;
wire   [23:0] r_V_10_0_5_fu_285_p2;
wire   [23:0] r_V_10_0_6_fu_310_p2;
wire   [24:0] r_V_10_0_8_fu_317_p2;
wire   [24:0] r_V_10_0_9_fu_309_p2;
wire   [24:0] r_V_10_0_s_fu_280_p2;
wire   [22:0] r_V_10_0_10_fu_293_p2;
wire   [24:0] r_V_10_0_11_fu_269_p2;
wire   [24:0] r_V_10_0_13_fu_257_p2;
wire   [24:0] r_V_10_0_14_fu_307_p2;
wire   [23:0] r_V_10_0_15_fu_256_p2;
wire   [21:0] r_V_10_0_16_fu_262_p2;
wire   [25:0] r_V_10_0_17_fu_291_p2;
wire   [25:0] r_V_10_0_18_fu_292_p2;
wire   [25:0] r_V_10_0_19_fu_290_p2;
wire   [22:0] p_shl21_fu_13171_p3;
wire  signed [23:0] p_shl21_cast_fu_13179_p1;
wire   [23:0] r_V_10_0_20_fu_13189_p2;
wire   [25:0] r_V_10_0_21_fu_313_p2;
wire   [24:0] r_V_10_0_22_fu_265_p2;
wire   [25:0] r_V_10_0_23_fu_264_p2;
wire   [23:0] r_V_10_0_25_fu_13235_p2;
wire   [23:0] r_V_10_0_26_fu_255_p2;
wire   [21:0] r_V_10_0_29_fu_301_p2;
wire   [23:0] r_V_10_0_30_fu_302_p2;
wire   [24:0] r_V_10_1_fu_261_p2;
wire   [25:0] r_V_10_1_1_fu_259_p2;
wire   [25:0] r_V_10_1_2_fu_275_p2;
wire   [25:0] r_V_10_1_3_fu_298_p2;
wire   [24:0] r_V_10_1_4_fu_311_p2;
wire   [24:0] r_V_10_1_5_fu_268_p2;
wire   [25:0] r_V_10_1_7_fu_299_p2;
wire   [24:0] r_V_10_1_8_fu_316_p2;
wire   [25:0] r_V_10_1_9_fu_266_p2;
wire   [25:0] r_V_10_1_s_fu_283_p2;
wire   [24:0] r_V_10_1_11_fu_260_p2;
wire   [25:0] r_V_10_1_12_fu_271_p2;
wire   [23:0] r_V_10_1_14_fu_270_p2;
wire   [24:0] r_V_10_1_15_fu_294_p2;
wire   [24:0] r_V_10_1_16_fu_288_p2;
wire   [18:0] p_shl4_fu_13489_p3;
wire  signed [19:0] p_shl4_cast_fu_13497_p1;
wire   [19:0] p_neg5_fu_13501_p2;
wire  signed [19:0] p_shl10_cast_fu_13435_p1;
wire   [19:0] r_V_10_1_17_fu_13507_p2;
wire   [23:0] r_V_10_1_18_fu_287_p2;
wire   [23:0] r_V_10_1_19_fu_308_p2;
wire   [23:0] r_V_10_1_20_fu_314_p2;
wire   [25:0] r_V_10_1_22_fu_278_p2;
wire   [25:0] r_V_10_1_23_fu_305_p2;
wire   [23:0] r_V_10_1_24_fu_267_p2;
wire   [24:0] r_V_10_1_25_fu_304_p2;
wire   [24:0] r_V_10_1_27_fu_315_p2;
wire   [24:0] r_V_10_1_28_fu_279_p2;
wire   [21:0] p_shl27_fu_13625_p3;
wire  signed [16:0] p_shl28_fu_13636_p3;
wire  signed [22:0] p_shl28_cast1_fu_13643_p1;
wire  signed [22:0] p_shl27_cast_fu_13632_p1;
wire   [22:0] r_V_10_0_4_fu_13651_p2;
wire   [12:0] tmp_376_fu_13657_p4;
wire   [22:0] r_V_10_0_7_fu_13677_p2;
wire   [12:0] tmp_380_fu_13683_p4;
wire   [20:0] p_shl23_fu_13712_p3;
wire   [17:0] p_shl24_fu_13723_p3;
wire  signed [21:0] p_shl23_cast_fu_13719_p1;
wire  signed [21:0] p_shl24_cast_fu_13730_p1;
wire   [21:0] r_V_10_0_12_fu_13734_p2;
wire   [11:0] tmp_390_fu_13740_p4;
wire   [19:0] p_shl20_fu_13772_p3;
wire  signed [22:0] p_shl20_cast_fu_13779_p1;
wire   [22:0] r_V_10_0_24_fu_13783_p2;
wire   [12:0] tmp_661_fu_13789_p4;
wire   [18:0] p_shl16_fu_13809_p3;
wire  signed [23:0] p_shl16_cast_fu_13816_p1;
wire   [23:0] r_V_10_0_27_fu_13820_p2;
wire   [13:0] tmp_408_fu_13825_p4;
wire  signed [23:0] p_shl28_cast_fu_13647_p1;
wire   [23:0] r_V_10_0_28_fu_13839_p2;
wire   [13:0] tmp_410_fu_13844_p4;
wire  signed [16:0] r_V_1_cast_fu_13867_p1;
wire   [16:0] r_V_10_1_6_fu_13879_p2;
wire   [6:0] tmp_663_fu_13885_p4;
wire   [22:0] p_shl9_fu_13902_p3;
wire  signed [23:0] p_shl10_cast1_fu_13913_p1;
wire  signed [23:0] p_shl9_cast_fu_13909_p1;
wire   [23:0] r_V_10_1_10_fu_13919_p2;
wire   [13:0] tmp_664_fu_13925_p4;
wire   [20:0] tmp_424_fu_13942_p3;
wire  signed [21:0] r_V_1_cast7_fu_13864_p1;
wire  signed [21:0] p_shl3_fu_13949_p1;
wire   [21:0] r_V_10_1_13_fu_13953_p2;
wire   [11:0] tmp_665_fu_13959_p4;
wire  signed [21:0] p_shl10_cast2_fu_13916_p1;
wire   [21:0] r_V_10_1_21_fu_13994_p2;
wire   [11:0] tmp_671_fu_14000_p4;
wire   [23:0] p_shl_fu_14020_p3;
wire   [17:0] p_shl1_fu_14031_p3;
wire  signed [24:0] p_shl_cast_fu_14027_p1;
wire  signed [24:0] p_shl1_cast_fu_14038_p1;
wire   [24:0] r_V_10_1_26_fu_14042_p2;
wire   [14:0] tmp_431_fu_14048_p4;
wire  signed [15:0] tmp_415_fu_13870_p1;
wire   [15:0] tmp29_fu_14068_p2;
wire  signed [15:0] tmp_369_fu_13613_p1;
wire   [15:0] tmp30_fu_14080_p2;
wire  signed [15:0] tmp_371_fu_13616_p1;
wire   [15:0] tmp31_fu_14091_p2;
wire  signed [15:0] tmp_373_fu_13619_p1;
wire   [15:0] tmp32_fu_14102_p2;
wire  signed [15:0] tmp_375_fu_13622_p1;
wire  signed [15:0] tmp_417_fu_13873_p1;
wire   [15:0] tmp33_fu_14113_p2;
wire  signed [15:0] tmp_377_fu_13667_p1;
wire  signed [15:0] tmp_419_fu_13876_p1;
wire   [15:0] tmp34_fu_14125_p2;
wire  signed [15:0] tmp_379_fu_13671_p1;
wire  signed [7:0] tmp_445_cast_fu_13895_p1;
wire   [7:0] tmp35_fu_14137_p2;
wire   [14:0] tmp35_cast_fu_14143_p1;
wire  signed [14:0] tmp_397_cast_fu_13674_p1;
wire   [14:0] acc_6_V_fu_14147_p2;
wire   [15:0] tmp36_fu_14157_p2;
wire  signed [15:0] tmp_381_fu_13693_p1;
wire  signed [15:0] tmp_421_fu_13899_p1;
wire   [15:0] tmp37_fu_14168_p2;
wire  signed [15:0] tmp_383_fu_13697_p1;
wire   [15:0] tmp38_fu_14180_p2;
wire  signed [15:0] tmp_385_fu_13700_p1;
wire   [15:0] tmp39_fu_14191_p2;
wire  signed [15:0] tmp_387_fu_13703_p1;
wire  signed [14:0] tmp_449_cast_fu_13935_p1;
wire   [14:0] tmp40_fu_14202_p2;
wire  signed [14:0] tmp_407_cast_fu_13706_p1;
wire   [14:0] acc_11_V_fu_14208_p2;
wire  signed [15:0] tmp_423_fu_13939_p1;
wire   [15:0] tmp41_fu_14218_p2;
wire  signed [15:0] tmp_389_fu_13709_p1;
wire   [15:0] tmp42_fu_14230_p2;
wire  signed [15:0] tmp_391_fu_13750_p1;
wire  signed [12:0] tmp_453_cast_fu_13969_p1;
wire   [12:0] tmp43_fu_14241_p2;
wire  signed [15:0] tmp43_cast_fu_14247_p1;
wire  signed [15:0] tmp_393_fu_13754_p1;
wire  signed [14:0] tmp_455_cast_fu_13973_p1;
wire   [14:0] tmp44_fu_14257_p2;
wire  signed [15:0] tmp44_cast_fu_14263_p1;
wire  signed [15:0] tmp_395_fu_13757_p1;
wire  signed [15:0] tmp_426_fu_13976_p1;
wire   [15:0] tmp45_fu_14273_p2;
wire  signed [15:0] tmp_397_fu_13760_p1;
wire  signed [15:0] tmp_428_fu_13979_p1;
wire   [15:0] tmp46_fu_14285_p2;
wire  signed [15:0] tmp_399_fu_13763_p1;
wire  signed [10:0] tmp_461_cast_fu_13982_p1;
wire   [10:0] tmp47_fu_14297_p2;
wire  signed [15:0] tmp47_cast_fu_14303_p1;
wire  signed [14:0] tmp_463_cast_fu_13985_p1;
wire   [14:0] tmp48_fu_14312_p2;
wire  signed [15:0] tmp48_cast_fu_14318_p1;
wire  signed [14:0] tmp_465_cast_fu_13988_p1;
wire   [14:0] tmp49_fu_14327_p2;
wire  signed [15:0] tmp49_cast_fu_14333_p1;
wire  signed [14:0] tmp_467_cast_fu_13991_p1;
wire   [14:0] tmp50_fu_14342_p2;
wire  signed [15:0] tmp50_cast_fu_14348_p1;
wire  signed [15:0] tmp_401_fu_13766_p1;
wire  signed [12:0] tmp_469_cast_fu_14010_p1;
wire   [12:0] tmp51_fu_14358_p2;
wire  signed [15:0] tmp51_cast_fu_14364_p1;
wire   [15:0] tmp52_fu_14373_p2;
wire  signed [15:0] tmp_403_fu_13769_p1;
wire   [15:0] tmp53_fu_14384_p2;
wire  signed [14:0] tmp_471_cast_fu_14014_p1;
wire   [14:0] tmp54_fu_14394_p2;
wire  signed [14:0] tmp_425_cast_fu_13799_p1;
wire   [14:0] acc_25_V_fu_14400_p2;
wire  signed [15:0] tmp_430_fu_14017_p1;
wire   [15:0] tmp55_fu_14410_p2;
wire  signed [15:0] tmp_405_fu_13803_p1;
wire  signed [15:0] tmp_432_fu_14058_p1;
wire   [15:0] tmp56_fu_14422_p2;
wire  signed [15:0] tmp_407_fu_13806_p1;
wire   [15:0] tmp57_fu_14434_p2;
wire  signed [15:0] tmp_409_fu_13835_p1;
wire  signed [15:0] tmp_434_fu_14062_p1;
wire   [15:0] tmp58_fu_14446_p2;
wire  signed [15:0] tmp_411_fu_13854_p1;
wire   [14:0] tmp59_fu_14458_p2;
wire  signed [14:0] tmp_435_cast_fu_13858_p1;
wire   [14:0] acc_30_V_fu_14464_p2;
wire  signed [15:0] tmp_436_fu_14065_p1;
wire   [15:0] tmp60_fu_14474_p2;
wire  signed [15:0] tmp_413_fu_13861_p1;
wire   [15:0] res_0_V_write_assign_fu_14074_p2;
wire   [15:0] acc_1_V_fu_14085_p2;
wire   [15:0] acc_2_V_fu_14096_p2;
wire   [15:0] acc_3_V_fu_14107_p2;
wire   [15:0] acc_4_V_fu_14119_p2;
wire   [15:0] acc_5_V_fu_14131_p2;
wire  signed [15:0] acc_6_V_cast_fu_14153_p1;
wire   [15:0] acc_7_V_fu_14162_p2;
wire   [15:0] acc_8_V_fu_14174_p2;
wire   [15:0] acc_9_V_fu_14185_p2;
wire   [15:0] acc_10_V_fu_14196_p2;
wire  signed [15:0] acc_11_V_cast_fu_14214_p1;
wire   [15:0] acc_12_V_fu_14224_p2;
wire   [15:0] acc_13_V_fu_14235_p2;
wire   [15:0] acc_14_V_fu_14251_p2;
wire   [15:0] acc_15_V_fu_14267_p2;
wire   [15:0] acc_16_V_fu_14279_p2;
wire   [15:0] acc_17_V_fu_14291_p2;
wire   [15:0] acc_18_V_fu_14307_p2;
wire   [15:0] acc_19_V_fu_14322_p2;
wire   [15:0] acc_20_V_fu_14337_p2;
wire   [15:0] acc_21_V_fu_14352_p2;
wire   [15:0] acc_22_V_fu_14368_p2;
wire   [15:0] acc_23_V_fu_14378_p2;
wire   [15:0] acc_24_V_fu_14389_p2;
wire  signed [15:0] acc_25_V_cast_fu_14406_p1;
wire   [15:0] acc_26_V_fu_14416_p2;
wire   [15:0] acc_27_V_fu_14428_p2;
wire   [15:0] acc_28_V_fu_14440_p2;
wire   [15:0] acc_29_V_fu_14452_p2;
wire  signed [15:0] acc_30_V_cast_fu_14470_p1;
wire   [15:0] acc_31_V_fu_14480_p2;
reg    ap_ce_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;
reg   [15:0] ap_return_6_int_reg;
reg   [15:0] ap_return_7_int_reg;
reg   [15:0] ap_return_8_int_reg;
reg   [15:0] ap_return_9_int_reg;
reg   [15:0] ap_return_10_int_reg;
reg   [15:0] ap_return_11_int_reg;
reg   [15:0] ap_return_12_int_reg;
reg   [15:0] ap_return_13_int_reg;
reg   [15:0] ap_return_14_int_reg;
reg   [15:0] ap_return_15_int_reg;
reg   [15:0] ap_return_16_int_reg;
reg   [15:0] ap_return_17_int_reg;
reg   [15:0] ap_return_18_int_reg;
reg   [15:0] ap_return_19_int_reg;
reg   [15:0] ap_return_20_int_reg;
reg   [15:0] ap_return_21_int_reg;
reg   [15:0] ap_return_22_int_reg;
reg   [15:0] ap_return_23_int_reg;
reg   [15:0] ap_return_24_int_reg;
reg   [15:0] ap_return_25_int_reg;
reg   [15:0] ap_return_26_int_reg;
reg   [15:0] ap_return_27_int_reg;
reg   [15:0] ap_return_28_int_reg;
reg   [15:0] ap_return_29_int_reg;
reg   [15:0] ap_return_30_int_reg;
reg   [15:0] ap_return_31_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= res_0_V_write_assign_fu_14074_p2;
        ap_return_10_int_reg <= acc_10_V_fu_14196_p2;
        ap_return_11_int_reg <= acc_11_V_cast_fu_14214_p1;
        ap_return_12_int_reg <= acc_12_V_fu_14224_p2;
        ap_return_13_int_reg <= acc_13_V_fu_14235_p2;
        ap_return_14_int_reg <= acc_14_V_fu_14251_p2;
        ap_return_15_int_reg <= acc_15_V_fu_14267_p2;
        ap_return_16_int_reg <= acc_16_V_fu_14279_p2;
        ap_return_17_int_reg <= acc_17_V_fu_14291_p2;
        ap_return_18_int_reg <= acc_18_V_fu_14307_p2;
        ap_return_19_int_reg <= acc_19_V_fu_14322_p2;
        ap_return_1_int_reg <= acc_1_V_fu_14085_p2;
        ap_return_20_int_reg <= acc_20_V_fu_14337_p2;
        ap_return_21_int_reg <= acc_21_V_fu_14352_p2;
        ap_return_22_int_reg <= acc_22_V_fu_14368_p2;
        ap_return_23_int_reg <= acc_23_V_fu_14378_p2;
        ap_return_24_int_reg <= acc_24_V_fu_14389_p2;
        ap_return_25_int_reg <= acc_25_V_cast_fu_14406_p1;
        ap_return_26_int_reg <= acc_26_V_fu_14416_p2;
        ap_return_27_int_reg <= acc_27_V_fu_14428_p2;
        ap_return_28_int_reg <= acc_28_V_fu_14440_p2;
        ap_return_29_int_reg <= acc_29_V_fu_14452_p2;
        ap_return_2_int_reg <= acc_2_V_fu_14096_p2;
        ap_return_30_int_reg <= acc_30_V_cast_fu_14470_p1;
        ap_return_31_int_reg <= acc_31_V_fu_14480_p2;
        ap_return_3_int_reg <= acc_3_V_fu_14107_p2;
        ap_return_4_int_reg <= acc_4_V_fu_14119_p2;
        ap_return_5_int_reg <= acc_5_V_fu_14131_p2;
        ap_return_6_int_reg <= acc_6_V_cast_fu_14153_p1;
        ap_return_7_int_reg <= acc_7_V_fu_14162_p2;
        ap_return_8_int_reg <= acc_8_V_fu_14174_p2;
        ap_return_9_int_reg <= acc_9_V_fu_14185_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        p_neg_reg_14778[23 : 7] <= p_neg_fu_13183_p2[23 : 7];
        p_shl10_reg_14884[16 : 1] <= p_shl10_fu_13427_p3[16 : 1];
        tmp_2_reg_14824 <= {{data_V_read[31:16]}};
        tmp_33_0_1_reg_14768 <= {{r_V_10_0_18_fu_292_p2[25:10]}};
        tmp_33_0_2_reg_14773 <= {{r_V_10_0_19_fu_290_p2[25:10]}};
        tmp_33_0_3_reg_14789 <= {{r_V_10_0_21_fu_313_p2[25:10]}};
        tmp_33_0_4_reg_14799 <= {{r_V_10_0_23_fu_264_p2[25:10]}};
        tmp_33_0_s_reg_14763 <= {{r_V_10_0_17_fu_291_p2[25:10]}};
        tmp_33_1_1_reg_14839 <= {{r_V_10_1_1_fu_259_p2[25:10]}};
        tmp_33_1_2_reg_14844 <= {{r_V_10_1_2_fu_275_p2[25:10]}};
        tmp_33_1_3_reg_14849 <= {{r_V_10_1_3_fu_298_p2[25:10]}};
        tmp_33_1_4_reg_14895 <= {{r_V_10_1_12_fu_271_p2[25:10]}};
        tmp_33_1_5_reg_14935 <= {{r_V_10_1_22_fu_278_p2[25:10]}};
        tmp_33_1_6_reg_14940 <= {{r_V_10_1_23_fu_305_p2[25:10]}};
        tmp_33_1_7_reg_14864 <= {{r_V_10_1_7_fu_299_p2[25:10]}};
        tmp_33_1_9_reg_14874 <= {{r_V_10_1_9_fu_266_p2[25:10]}};
        tmp_33_1_s_reg_14879 <= {{r_V_10_1_s_fu_283_p2[25:10]}};
        tmp_370_reg_14693 <= {{r_V_10_0_1_fu_273_p2[22:10]}};
        tmp_372_reg_14698 <= {{r_V_10_0_2_fu_272_p2[24:10]}};
        tmp_374_reg_14703 <= {{r_V_10_0_3_fu_300_p2[24:10]}};
        tmp_378_reg_14708 <= {{r_V_10_0_5_fu_285_p2[23:10]}};
        tmp_382_reg_14718 <= {{r_V_10_0_8_fu_317_p2[24:10]}};
        tmp_384_reg_14723 <= {{r_V_10_0_9_fu_309_p2[24:10]}};
        tmp_386_reg_14728 <= {{r_V_10_0_s_fu_280_p2[24:10]}};
        tmp_388_reg_14738 <= {{r_V_10_0_11_fu_269_p2[24:10]}};
        tmp_392_reg_14743 <= {{r_V_10_0_13_fu_257_p2[24:10]}};
        tmp_394_reg_14748 <= {{r_V_10_0_14_fu_307_p2[24:10]}};
        tmp_396_reg_14753 <= {{r_V_10_0_15_fu_256_p2[23:10]}};
        tmp_398_reg_14758 <= {{r_V_10_0_16_fu_262_p2[21:10]}};
        tmp_400_reg_14784 <= {{r_V_10_0_20_fu_13189_p2[23:10]}};
        tmp_402_reg_14794 <= {{r_V_10_0_22_fu_265_p2[24:10]}};
        tmp_404_reg_14804 <= {{r_V_10_0_25_fu_13235_p2[23:10]}};
        tmp_406_reg_14809 <= {{r_V_10_0_26_fu_255_p2[23:10]}};
        tmp_412_reg_14819 <= {{r_V_10_0_30_fu_302_p2[23:10]}};
        tmp_414_reg_14834 <= {{r_V_10_1_fu_261_p2[24:10]}};
        tmp_416_reg_14854 <= {{r_V_10_1_4_fu_311_p2[24:10]}};
        tmp_418_reg_14859 <= {{r_V_10_1_5_fu_268_p2[24:10]}};
        tmp_420_reg_14869 <= {{r_V_10_1_8_fu_316_p2[24:10]}};
        tmp_422_reg_14890 <= {{r_V_10_1_11_fu_260_p2[24:10]}};
        tmp_425_reg_14905 <= {{r_V_10_1_15_fu_294_p2[24:10]}};
        tmp_427_reg_14910 <= {{r_V_10_1_16_fu_288_p2[24:10]}};
        tmp_429_reg_14950 <= {{r_V_10_1_25_fu_304_p2[24:10]}};
        tmp_433_reg_14955 <= {{r_V_10_1_27_fu_315_p2[24:10]}};
        tmp_435_reg_14960 <= {{r_V_10_1_28_fu_279_p2[24:10]}};
        tmp_659_reg_14713 <= {{r_V_10_0_6_fu_310_p2[23:10]}};
        tmp_660_reg_14733 <= {{r_V_10_0_10_fu_293_p2[22:10]}};
        tmp_662_reg_14814 <= {{r_V_10_0_29_fu_301_p2[21:10]}};
        tmp_666_reg_14900 <= {{r_V_10_1_14_fu_270_p2[23:10]}};
        tmp_667_reg_14915 <= {{r_V_10_1_17_fu_13507_p2[19:10]}};
        tmp_668_reg_14920 <= {{r_V_10_1_18_fu_287_p2[23:10]}};
        tmp_669_reg_14925 <= {{r_V_10_1_19_fu_308_p2[23:10]}};
        tmp_670_reg_14930 <= {{r_V_10_1_20_fu_314_p2[23:10]}};
        tmp_672_reg_14945 <= {{r_V_10_1_24_fu_267_p2[23:10]}};
        tmp_reg_14678 <= tmp_fu_12943_p1;
        tmp_s_reg_14688 <= {{r_V_s_fu_295_p2[23:10]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = res_0_V_write_assign_fu_14074_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = acc_1_V_fu_14085_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_10 = ap_return_10_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_10 = acc_10_V_fu_14196_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_11 = ap_return_11_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_11 = acc_11_V_cast_fu_14214_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_12 = ap_return_12_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_12 = acc_12_V_fu_14224_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_13 = ap_return_13_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_13 = acc_13_V_fu_14235_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_14 = ap_return_14_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_14 = acc_14_V_fu_14251_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_15 = ap_return_15_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_15 = acc_15_V_fu_14267_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_16 = ap_return_16_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_16 = acc_16_V_fu_14279_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_17 = ap_return_17_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_17 = acc_17_V_fu_14291_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_18 = ap_return_18_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_18 = acc_18_V_fu_14307_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_19 = ap_return_19_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_19 = acc_19_V_fu_14322_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = acc_2_V_fu_14096_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_20 = ap_return_20_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_20 = acc_20_V_fu_14337_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_21 = ap_return_21_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_21 = acc_21_V_fu_14352_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_22 = ap_return_22_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_22 = acc_22_V_fu_14368_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_23 = ap_return_23_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_23 = acc_23_V_fu_14378_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_24 = ap_return_24_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_24 = acc_24_V_fu_14389_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_25 = ap_return_25_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_25 = acc_25_V_cast_fu_14406_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_26 = ap_return_26_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_26 = acc_26_V_fu_14416_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_27 = ap_return_27_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_27 = acc_27_V_fu_14428_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_28 = ap_return_28_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_28 = acc_28_V_fu_14440_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_29 = ap_return_29_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_29 = acc_29_V_fu_14452_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = acc_3_V_fu_14107_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_30 = ap_return_30_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_30 = acc_30_V_cast_fu_14470_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_31 = ap_return_31_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_31 = acc_31_V_fu_14480_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = acc_4_V_fu_14119_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = acc_5_V_fu_14131_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = acc_6_V_cast_fu_14153_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_7 = ap_return_7_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_7 = acc_7_V_fu_14162_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_8 = ap_return_8_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_8 = acc_8_V_fu_14174_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_9 = ap_return_9_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_9 = acc_9_V_fu_14185_p2;
    end
end

assign acc_10_V_fu_14196_p2 = ($signed(tmp39_fu_14191_p2) + $signed(tmp_387_fu_13703_p1));

assign acc_11_V_cast_fu_14214_p1 = $signed(acc_11_V_fu_14208_p2);

assign acc_11_V_fu_14208_p2 = ($signed(tmp40_fu_14202_p2) + $signed(tmp_407_cast_fu_13706_p1));

assign acc_12_V_fu_14224_p2 = ($signed(tmp41_fu_14218_p2) + $signed(tmp_389_fu_13709_p1));

assign acc_13_V_fu_14235_p2 = ($signed(tmp42_fu_14230_p2) + $signed(tmp_391_fu_13750_p1));

assign acc_14_V_fu_14251_p2 = ($signed(tmp43_cast_fu_14247_p1) + $signed(tmp_393_fu_13754_p1));

assign acc_15_V_fu_14267_p2 = ($signed(tmp44_cast_fu_14263_p1) + $signed(tmp_395_fu_13757_p1));

assign acc_16_V_fu_14279_p2 = ($signed(tmp45_fu_14273_p2) + $signed(tmp_397_fu_13760_p1));

assign acc_17_V_fu_14291_p2 = ($signed(tmp46_fu_14285_p2) + $signed(tmp_399_fu_13763_p1));

assign acc_18_V_fu_14307_p2 = ($signed(tmp47_cast_fu_14303_p1) + $signed(tmp_33_0_s_reg_14763));

assign acc_19_V_fu_14322_p2 = ($signed(tmp48_cast_fu_14318_p1) + $signed(tmp_33_0_1_reg_14768));

assign acc_1_V_fu_14085_p2 = ($signed(tmp30_fu_14080_p2) + $signed(tmp_371_fu_13616_p1));

assign acc_20_V_fu_14337_p2 = ($signed(tmp49_cast_fu_14333_p1) + $signed(tmp_33_0_2_reg_14773));

assign acc_21_V_fu_14352_p2 = ($signed(tmp50_cast_fu_14348_p1) + $signed(tmp_401_fu_13766_p1));

assign acc_22_V_fu_14368_p2 = ($signed(tmp51_cast_fu_14364_p1) + $signed(tmp_33_0_3_reg_14789));

assign acc_23_V_fu_14378_p2 = ($signed(tmp52_fu_14373_p2) + $signed(tmp_403_fu_13769_p1));

assign acc_24_V_fu_14389_p2 = (tmp53_fu_14384_p2 + tmp_33_0_4_reg_14799);

assign acc_25_V_cast_fu_14406_p1 = $signed(acc_25_V_fu_14400_p2);

assign acc_25_V_fu_14400_p2 = ($signed(tmp54_fu_14394_p2) + $signed(tmp_425_cast_fu_13799_p1));

assign acc_26_V_fu_14416_p2 = ($signed(tmp55_fu_14410_p2) + $signed(tmp_405_fu_13803_p1));

assign acc_27_V_fu_14428_p2 = ($signed(tmp56_fu_14422_p2) + $signed(tmp_407_fu_13806_p1));

assign acc_28_V_fu_14440_p2 = ($signed(tmp57_fu_14434_p2) + $signed(tmp_409_fu_13835_p1));

assign acc_29_V_fu_14452_p2 = ($signed(tmp58_fu_14446_p2) + $signed(tmp_411_fu_13854_p1));

assign acc_2_V_fu_14096_p2 = ($signed(tmp31_fu_14091_p2) + $signed(tmp_373_fu_13619_p1));

assign acc_30_V_cast_fu_14470_p1 = $signed(acc_30_V_fu_14464_p2);

assign acc_30_V_fu_14464_p2 = ($signed(tmp59_fu_14458_p2) + $signed(tmp_435_cast_fu_13858_p1));

assign acc_31_V_fu_14480_p2 = ($signed(tmp60_fu_14474_p2) + $signed(tmp_413_fu_13861_p1));

assign acc_3_V_fu_14107_p2 = ($signed(tmp32_fu_14102_p2) + $signed(tmp_375_fu_13622_p1));

assign acc_4_V_fu_14119_p2 = ($signed(tmp33_fu_14113_p2) + $signed(tmp_377_fu_13667_p1));

assign acc_5_V_fu_14131_p2 = ($signed(tmp34_fu_14125_p2) + $signed(tmp_379_fu_13671_p1));

assign acc_6_V_cast_fu_14153_p1 = $signed(acc_6_V_fu_14147_p2);

assign acc_6_V_fu_14147_p2 = ($signed(tmp35_cast_fu_14143_p1) + $signed(tmp_397_cast_fu_13674_p1));

assign acc_7_V_fu_14162_p2 = ($signed(tmp36_fu_14157_p2) + $signed(tmp_381_fu_13693_p1));

assign acc_8_V_fu_14174_p2 = ($signed(tmp37_fu_14168_p2) + $signed(tmp_383_fu_13697_p1));

assign acc_9_V_fu_14185_p2 = ($signed(tmp38_fu_14180_p2) + $signed(tmp_385_fu_13700_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign p_neg5_fu_13501_p2 = ($signed(20'd0) - $signed(p_shl4_cast_fu_13497_p1));

assign p_neg_fu_13183_p2 = ($signed(24'd0) - $signed(p_shl21_cast_fu_13179_p1));

assign p_shl10_cast1_fu_13913_p1 = p_shl10_reg_14884;

assign p_shl10_cast2_fu_13916_p1 = p_shl10_reg_14884;

assign p_shl10_cast_fu_13435_p1 = p_shl10_fu_13427_p3;

assign p_shl10_fu_13427_p3 = {{tmp_2_fu_13281_p4}, {1'd0}};

assign p_shl16_cast_fu_13816_p1 = $signed(p_shl16_fu_13809_p3);

assign p_shl16_fu_13809_p3 = {{tmp_reg_14678}, {3'd0}};

assign p_shl1_cast_fu_14038_p1 = $signed(p_shl1_fu_14031_p3);

assign p_shl1_fu_14031_p3 = {{tmp_2_reg_14824}, {2'd0}};

assign p_shl20_cast_fu_13779_p1 = $signed(p_shl20_fu_13772_p3);

assign p_shl20_fu_13772_p3 = {{tmp_reg_14678}, {4'd0}};

assign p_shl21_cast_fu_13179_p1 = $signed(p_shl21_fu_13171_p3);

assign p_shl21_fu_13171_p3 = {{tmp_fu_12943_p1}, {7'd0}};

assign p_shl23_cast_fu_13719_p1 = $signed(p_shl23_fu_13712_p3);

assign p_shl23_fu_13712_p3 = {{tmp_reg_14678}, {5'd0}};

assign p_shl24_cast_fu_13730_p1 = $signed(p_shl24_fu_13723_p3);

assign p_shl24_fu_13723_p3 = {{tmp_reg_14678}, {2'd0}};

assign p_shl27_cast_fu_13632_p1 = $signed(p_shl27_fu_13625_p3);

assign p_shl27_fu_13625_p3 = {{tmp_reg_14678}, {6'd0}};

assign p_shl28_cast1_fu_13643_p1 = p_shl28_fu_13636_p3;

assign p_shl28_cast_fu_13647_p1 = p_shl28_fu_13636_p3;

assign p_shl28_fu_13636_p3 = {{tmp_reg_14678}, {1'd0}};

assign p_shl3_fu_13949_p1 = $signed(tmp_424_fu_13942_p3);

assign p_shl4_cast_fu_13497_p1 = $signed(p_shl4_fu_13489_p3);

assign p_shl4_fu_13489_p3 = {{tmp_2_fu_13281_p4}, {3'd0}};

assign p_shl9_cast_fu_13909_p1 = $signed(p_shl9_fu_13902_p3);

assign p_shl9_fu_13902_p3 = {{tmp_2_reg_14824}, {7'd0}};

assign p_shl_cast_fu_14027_p1 = $signed(p_shl_fu_14020_p3);

assign p_shl_fu_14020_p3 = {{tmp_2_reg_14824}, {8'd0}};

assign r_V_10_0_10_fu_293_p1 = r_V_cast1_fu_12985_p1;

assign r_V_10_0_10_fu_293_p2 = ($signed({{1'b0}, {23'd47}}) * $signed(r_V_10_0_10_fu_293_p1));

assign r_V_10_0_11_fu_269_p1 = r_V_cast4_fu_12956_p1;

assign r_V_10_0_11_fu_269_p2 = ($signed({{1'b0}, {25'd225}}) * $signed(r_V_10_0_11_fu_269_p1));

assign r_V_10_0_12_fu_13734_p2 = ($signed(p_shl23_cast_fu_13719_p1) - $signed(p_shl24_cast_fu_13730_p1));

assign r_V_10_0_13_fu_257_p1 = r_V_cast4_fu_12956_p1;

assign r_V_10_0_13_fu_257_p2 = ($signed({{1'b0}, {25'd159}}) * $signed(r_V_10_0_13_fu_257_p1));

assign r_V_10_0_14_fu_307_p1 = r_V_cast4_fu_12956_p1;

assign r_V_10_0_14_fu_307_p2 = ($signed(25'd33554243) * $signed(r_V_10_0_14_fu_307_p1));

assign r_V_10_0_15_fu_256_p1 = r_V_cast9_fu_12975_p1;

assign r_V_10_0_15_fu_256_p2 = ($signed(24'd16777097) * $signed(r_V_10_0_15_fu_256_p1));

assign r_V_10_0_16_fu_262_p1 = r_V_cast6_fu_12969_p1;

assign r_V_10_0_16_fu_262_p2 = ($signed({{1'b0}, {22'd19}}) * $signed(r_V_10_0_16_fu_262_p1));

assign r_V_10_0_17_fu_291_p1 = r_V_cast_fu_12947_p1;

assign r_V_10_0_17_fu_291_p2 = ($signed({{1'b0}, {26'd322}}) * $signed(r_V_10_0_17_fu_291_p1));

assign r_V_10_0_18_fu_292_p1 = r_V_cast_fu_12947_p1;

assign r_V_10_0_18_fu_292_p2 = ($signed({{1'b0}, {26'd269}}) * $signed(r_V_10_0_18_fu_292_p1));

assign r_V_10_0_19_fu_290_p1 = r_V_cast_fu_12947_p1;

assign r_V_10_0_19_fu_290_p2 = ($signed({{1'b0}, {26'd275}}) * $signed(r_V_10_0_19_fu_290_p1));

assign r_V_10_0_1_fu_273_p1 = r_V_cast1_fu_12985_p1;

assign r_V_10_0_1_fu_273_p2 = ($signed({{1'b0}, {23'd54}}) * $signed(r_V_10_0_1_fu_273_p1));

assign r_V_10_0_20_fu_13189_p2 = ($signed(p_neg_fu_13183_p2) - $signed(r_V_cast9_fu_12975_p1));

assign r_V_10_0_21_fu_313_p1 = r_V_cast_fu_12947_p1;

assign r_V_10_0_21_fu_313_p2 = ($signed({{1'b0}, {26'd330}}) * $signed(r_V_10_0_21_fu_313_p1));

assign r_V_10_0_22_fu_265_p1 = r_V_cast4_fu_12956_p1;

assign r_V_10_0_22_fu_265_p2 = ($signed(25'd33554284) * $signed(r_V_10_0_22_fu_265_p1));

assign r_V_10_0_23_fu_264_p1 = r_V_cast_fu_12947_p1;

assign r_V_10_0_23_fu_264_p2 = ($signed({{1'b0}, {26'd324}}) * $signed(r_V_10_0_23_fu_264_p1));

assign r_V_10_0_24_fu_13783_p2 = ($signed(p_shl27_cast_fu_13632_p1) - $signed(p_shl20_cast_fu_13779_p1));

assign r_V_10_0_25_fu_13235_p2 = ($signed(r_V_cast9_fu_12975_p1) - $signed(p_shl21_cast_fu_13179_p1));

assign r_V_10_0_26_fu_255_p1 = r_V_cast9_fu_12975_p1;

assign r_V_10_0_26_fu_255_p2 = ($signed(24'd16777125) * $signed(r_V_10_0_26_fu_255_p1));

assign r_V_10_0_27_fu_13820_p2 = ($signed(p_neg_reg_14778) - $signed(p_shl16_cast_fu_13816_p1));

assign r_V_10_0_28_fu_13839_p2 = ($signed(p_neg_reg_14778) - $signed(p_shl28_cast_fu_13647_p1));

assign r_V_10_0_29_fu_301_p1 = r_V_cast6_fu_12969_p1;

assign r_V_10_0_29_fu_301_p2 = ($signed(22'd4194281) * $signed(r_V_10_0_29_fu_301_p1));

assign r_V_10_0_2_fu_272_p1 = r_V_cast4_fu_12956_p1;

assign r_V_10_0_2_fu_272_p2 = ($signed(25'd33554301) * $signed(r_V_10_0_2_fu_272_p1));

assign r_V_10_0_30_fu_302_p1 = r_V_cast9_fu_12975_p1;

assign r_V_10_0_30_fu_302_p2 = ($signed(24'd16777147) * $signed(r_V_10_0_30_fu_302_p1));

assign r_V_10_0_3_fu_300_p1 = r_V_cast4_fu_12956_p1;

assign r_V_10_0_3_fu_300_p2 = ($signed({{1'b0}, {25'd229}}) * $signed(r_V_10_0_3_fu_300_p1));

assign r_V_10_0_4_fu_13651_p2 = ($signed(p_shl28_cast1_fu_13643_p1) + $signed(p_shl27_cast_fu_13632_p1));

assign r_V_10_0_5_fu_285_p1 = r_V_cast9_fu_12975_p1;

assign r_V_10_0_5_fu_285_p2 = ($signed(24'd16777137) * $signed(r_V_10_0_5_fu_285_p1));

assign r_V_10_0_6_fu_310_p1 = r_V_cast9_fu_12975_p1;

assign r_V_10_0_6_fu_310_p2 = ($signed({{1'b0}, {24'd109}}) * $signed(r_V_10_0_6_fu_310_p1));

assign r_V_10_0_7_fu_13677_p2 = ($signed(23'd0) - $signed(p_shl27_cast_fu_13632_p1));

assign r_V_10_0_8_fu_317_p1 = r_V_cast4_fu_12956_p1;

assign r_V_10_0_8_fu_317_p2 = ($signed(25'd33554221) * $signed(r_V_10_0_8_fu_317_p1));

assign r_V_10_0_9_fu_309_p1 = r_V_cast4_fu_12956_p1;

assign r_V_10_0_9_fu_309_p2 = ($signed(25'd33554236) * $signed(r_V_10_0_9_fu_309_p1));

assign r_V_10_0_s_fu_280_p1 = r_V_cast4_fu_12956_p1;

assign r_V_10_0_s_fu_280_p2 = ($signed(25'd33554219) * $signed(r_V_10_0_s_fu_280_p1));

assign r_V_10_1_10_fu_13919_p2 = ($signed(p_shl10_cast1_fu_13913_p1) + $signed(p_shl9_cast_fu_13909_p1));

assign r_V_10_1_11_fu_260_p1 = r_V_1_cast9_fu_13304_p1;

assign r_V_10_1_11_fu_260_p2 = ($signed(25'd33554215) * $signed(r_V_10_1_11_fu_260_p1));

assign r_V_10_1_12_fu_271_p1 = r_V_1_cast8_fu_13291_p1;

assign r_V_10_1_12_fu_271_p2 = ($signed(26'd67108497) * $signed(r_V_10_1_12_fu_271_p1));

assign r_V_10_1_13_fu_13953_p2 = ($signed(r_V_1_cast7_fu_13864_p1) - $signed(p_shl3_fu_13949_p1));

assign r_V_10_1_14_fu_270_p1 = r_V_1_cast1_fu_13318_p1;

assign r_V_10_1_14_fu_270_p2 = ($signed(24'd16777147) * $signed(r_V_10_1_14_fu_270_p1));

assign r_V_10_1_15_fu_294_p1 = r_V_1_cast9_fu_13304_p1;

assign r_V_10_1_15_fu_294_p2 = ($signed(25'd33554213) * $signed(r_V_10_1_15_fu_294_p1));

assign r_V_10_1_16_fu_288_p1 = r_V_1_cast9_fu_13304_p1;

assign r_V_10_1_16_fu_288_p2 = ($signed({{1'b0}, {25'd191}}) * $signed(r_V_10_1_16_fu_288_p1));

assign r_V_10_1_17_fu_13507_p2 = ($signed(p_neg5_fu_13501_p2) - $signed(p_shl10_cast_fu_13435_p1));

assign r_V_10_1_18_fu_287_p1 = r_V_1_cast1_fu_13318_p1;

assign r_V_10_1_18_fu_287_p2 = ($signed(24'd16777123) * $signed(r_V_10_1_18_fu_287_p1));

assign r_V_10_1_19_fu_308_p1 = r_V_1_cast1_fu_13318_p1;

assign r_V_10_1_19_fu_308_p2 = ($signed({{1'b0}, {24'd89}}) * $signed(r_V_10_1_19_fu_308_p1));

assign r_V_10_1_1_fu_259_p1 = r_V_1_cast8_fu_13291_p1;

assign r_V_10_1_1_fu_259_p2 = ($signed(26'd67108456) * $signed(r_V_10_1_1_fu_259_p1));

assign r_V_10_1_20_fu_314_p1 = r_V_1_cast1_fu_13318_p1;

assign r_V_10_1_20_fu_314_p2 = ($signed(24'd16777093) * $signed(r_V_10_1_20_fu_314_p1));

assign r_V_10_1_21_fu_13994_p2 = ($signed(p_shl10_cast2_fu_13916_p1) - $signed(p_shl3_fu_13949_p1));

assign r_V_10_1_22_fu_278_p1 = r_V_1_cast8_fu_13291_p1;

assign r_V_10_1_22_fu_278_p2 = ($signed(26'd67108502) * $signed(r_V_10_1_22_fu_278_p1));

assign r_V_10_1_23_fu_305_p1 = r_V_1_cast8_fu_13291_p1;

assign r_V_10_1_23_fu_305_p2 = ($signed({{1'b0}, {26'd285}}) * $signed(r_V_10_1_23_fu_305_p1));

assign r_V_10_1_24_fu_267_p1 = r_V_1_cast1_fu_13318_p1;

assign r_V_10_1_24_fu_267_p2 = ($signed({{1'b0}, {24'd94}}) * $signed(r_V_10_1_24_fu_267_p1));

assign r_V_10_1_25_fu_304_p1 = r_V_1_cast9_fu_13304_p1;

assign r_V_10_1_25_fu_304_p2 = ($signed(25'd33554185) * $signed(r_V_10_1_25_fu_304_p1));

assign r_V_10_1_26_fu_14042_p2 = ($signed(p_shl_cast_fu_14027_p1) - $signed(p_shl1_cast_fu_14038_p1));

assign r_V_10_1_27_fu_315_p1 = r_V_1_cast9_fu_13304_p1;

assign r_V_10_1_27_fu_315_p2 = ($signed(25'd33554206) * $signed(r_V_10_1_27_fu_315_p1));

assign r_V_10_1_28_fu_279_p1 = r_V_1_cast9_fu_13304_p1;

assign r_V_10_1_28_fu_279_p2 = ($signed(25'd33554258) * $signed(r_V_10_1_28_fu_279_p1));

assign r_V_10_1_2_fu_275_p1 = r_V_1_cast8_fu_13291_p1;

assign r_V_10_1_2_fu_275_p2 = ($signed(26'd67108552) * $signed(r_V_10_1_2_fu_275_p1));

assign r_V_10_1_3_fu_298_p1 = r_V_1_cast8_fu_13291_p1;

assign r_V_10_1_3_fu_298_p2 = ($signed({{1'b0}, {26'd266}}) * $signed(r_V_10_1_3_fu_298_p1));

assign r_V_10_1_4_fu_311_p1 = r_V_1_cast9_fu_13304_p1;

assign r_V_10_1_4_fu_311_p2 = ($signed({{1'b0}, {25'd140}}) * $signed(r_V_10_1_4_fu_311_p1));

assign r_V_10_1_5_fu_268_p1 = r_V_1_cast9_fu_13304_p1;

assign r_V_10_1_5_fu_268_p2 = ($signed(25'd33554222) * $signed(r_V_10_1_5_fu_268_p1));

assign r_V_10_1_6_fu_13879_p2 = ($signed(17'd0) - $signed(r_V_1_cast_fu_13867_p1));

assign r_V_10_1_7_fu_299_p1 = r_V_1_cast8_fu_13291_p1;

assign r_V_10_1_7_fu_299_p2 = ($signed({{1'b0}, {26'd309}}) * $signed(r_V_10_1_7_fu_299_p1));

assign r_V_10_1_8_fu_316_p1 = r_V_1_cast9_fu_13304_p1;

assign r_V_10_1_8_fu_316_p2 = ($signed(25'd33554265) * $signed(r_V_10_1_8_fu_316_p1));

assign r_V_10_1_9_fu_266_p1 = r_V_1_cast8_fu_13291_p1;

assign r_V_10_1_9_fu_266_p2 = ($signed({{1'b0}, {26'd263}}) * $signed(r_V_10_1_9_fu_266_p1));

assign r_V_10_1_fu_261_p1 = r_V_1_cast9_fu_13304_p1;

assign r_V_10_1_fu_261_p2 = ($signed(25'd33554298) * $signed(r_V_10_1_fu_261_p1));

assign r_V_10_1_s_fu_283_p1 = r_V_1_cast8_fu_13291_p1;

assign r_V_10_1_s_fu_283_p2 = ($signed(26'd67108434) * $signed(r_V_10_1_s_fu_283_p1));

assign r_V_1_cast1_fu_13318_p1 = tmp_2_fu_13281_p4;

assign r_V_1_cast7_fu_13864_p1 = tmp_2_reg_14824;

assign r_V_1_cast8_fu_13291_p1 = tmp_2_fu_13281_p4;

assign r_V_1_cast9_fu_13304_p1 = tmp_2_fu_13281_p4;

assign r_V_1_cast_fu_13867_p1 = tmp_2_reg_14824;

assign r_V_cast1_fu_12985_p1 = tmp_fu_12943_p1;

assign r_V_cast4_fu_12956_p1 = tmp_fu_12943_p1;

assign r_V_cast6_fu_12969_p1 = tmp_fu_12943_p1;

assign r_V_cast9_fu_12975_p1 = tmp_fu_12943_p1;

assign r_V_cast_fu_12947_p1 = tmp_fu_12943_p1;

assign r_V_s_fu_295_p1 = r_V_cast9_fu_12975_p1;

assign r_V_s_fu_295_p2 = ($signed(24'd16777126) * $signed(r_V_s_fu_295_p1));

assign res_0_V_write_assign_fu_14074_p2 = ($signed(tmp29_fu_14068_p2) + $signed(tmp_369_fu_13613_p1));

assign tmp29_fu_14068_p2 = ($signed(16'd65495) + $signed(tmp_415_fu_13870_p1));

assign tmp30_fu_14080_p2 = ($signed(16'd65382) + $signed(tmp_33_1_1_reg_14839));

assign tmp31_fu_14091_p2 = ($signed(16'd65316) + $signed(tmp_33_1_2_reg_14844));

assign tmp32_fu_14102_p2 = (16'd306 + tmp_33_1_3_reg_14849);

assign tmp33_fu_14113_p2 = ($signed(16'd335) + $signed(tmp_417_fu_13873_p1));

assign tmp34_fu_14125_p2 = ($signed(16'd65489) + $signed(tmp_419_fu_13876_p1));

assign tmp35_cast_fu_14143_p1 = tmp35_fu_14137_p2;

assign tmp35_fu_14137_p2 = ($signed(8'd132) + $signed(tmp_445_cast_fu_13895_p1));

assign tmp36_fu_14157_p2 = (16'd246 + tmp_33_1_7_reg_14864);

assign tmp37_fu_14168_p2 = ($signed(16'd65381) + $signed(tmp_421_fu_13899_p1));

assign tmp38_fu_14180_p2 = ($signed(16'd65394) + $signed(tmp_33_1_9_reg_14874));

assign tmp39_fu_14191_p2 = ($signed(16'd65291) + $signed(tmp_33_1_s_reg_14879));

assign tmp40_fu_14202_p2 = ($signed(15'd308) + $signed(tmp_449_cast_fu_13935_p1));

assign tmp41_fu_14218_p2 = ($signed(16'd65350) + $signed(tmp_423_fu_13939_p1));

assign tmp42_fu_14230_p2 = ($signed(16'd65417) + $signed(tmp_33_1_4_reg_14895));

assign tmp43_cast_fu_14247_p1 = $signed(tmp43_fu_14241_p2);

assign tmp43_fu_14241_p2 = ($signed(13'd30) + $signed(tmp_453_cast_fu_13969_p1));

assign tmp44_cast_fu_14263_p1 = $signed(tmp44_fu_14257_p2);

assign tmp44_fu_14257_p2 = ($signed(15'd32641) + $signed(tmp_455_cast_fu_13973_p1));

assign tmp45_fu_14273_p2 = ($signed(16'd65496) + $signed(tmp_426_fu_13976_p1));

assign tmp46_fu_14285_p2 = ($signed(16'd228) + $signed(tmp_428_fu_13979_p1));

assign tmp47_cast_fu_14303_p1 = $signed(tmp47_fu_14297_p2);

assign tmp47_fu_14297_p2 = ($signed(11'd83) + $signed(tmp_461_cast_fu_13982_p1));

assign tmp48_cast_fu_14318_p1 = $signed(tmp48_fu_14312_p2);

assign tmp48_fu_14312_p2 = ($signed(15'd1) + $signed(tmp_463_cast_fu_13985_p1));

assign tmp49_cast_fu_14333_p1 = $signed(tmp49_fu_14327_p2);

assign tmp49_fu_14327_p2 = ($signed(15'd281) + $signed(tmp_465_cast_fu_13988_p1));

assign tmp50_cast_fu_14348_p1 = $signed(tmp50_fu_14342_p2);

assign tmp50_fu_14342_p2 = ($signed(15'd32617) + $signed(tmp_467_cast_fu_13991_p1));

assign tmp51_cast_fu_14364_p1 = $signed(tmp51_fu_14358_p2);

assign tmp51_fu_14358_p2 = ($signed(13'd132) + $signed(tmp_469_cast_fu_14010_p1));

assign tmp52_fu_14373_p2 = ($signed(16'd65291) + $signed(tmp_33_1_5_reg_14935));

assign tmp53_fu_14384_p2 = (16'd279 + tmp_33_1_6_reg_14940);

assign tmp54_fu_14394_p2 = ($signed(15'd281) + $signed(tmp_471_cast_fu_14014_p1));

assign tmp55_fu_14410_p2 = ($signed(16'd65370) + $signed(tmp_430_fu_14017_p1));

assign tmp56_fu_14422_p2 = ($signed(16'd81) + $signed(tmp_432_fu_14058_p1));

assign tmp57_fu_14434_p2 = ($signed(16'd65419) + $signed(tmp_421_fu_13899_p1));

assign tmp58_fu_14446_p2 = ($signed(16'd65321) + $signed(tmp_434_fu_14062_p1));

assign tmp59_fu_14458_p2 = ($signed(15'd166) + $signed(tmp_449_cast_fu_13935_p1));

assign tmp60_fu_14474_p2 = ($signed(16'd65428) + $signed(tmp_436_fu_14065_p1));

assign tmp_2_fu_13281_p4 = {{data_V_read[31:16]}};

assign tmp_369_fu_13613_p1 = $signed(tmp_s_reg_14688);

assign tmp_371_fu_13616_p1 = $signed(tmp_370_reg_14693);

assign tmp_373_fu_13619_p1 = $signed(tmp_372_reg_14698);

assign tmp_375_fu_13622_p1 = $signed(tmp_374_reg_14703);

assign tmp_376_fu_13657_p4 = {{r_V_10_0_4_fu_13651_p2[22:10]}};

assign tmp_377_fu_13667_p1 = $signed(tmp_376_fu_13657_p4);

assign tmp_379_fu_13671_p1 = $signed(tmp_378_reg_14708);

assign tmp_380_fu_13683_p4 = {{r_V_10_0_7_fu_13677_p2[22:10]}};

assign tmp_381_fu_13693_p1 = $signed(tmp_380_fu_13683_p4);

assign tmp_383_fu_13697_p1 = $signed(tmp_382_reg_14718);

assign tmp_385_fu_13700_p1 = $signed(tmp_384_reg_14723);

assign tmp_387_fu_13703_p1 = $signed(tmp_386_reg_14728);

assign tmp_389_fu_13709_p1 = $signed(tmp_388_reg_14738);

assign tmp_390_fu_13740_p4 = {{r_V_10_0_12_fu_13734_p2[21:10]}};

assign tmp_391_fu_13750_p1 = $signed(tmp_390_fu_13740_p4);

assign tmp_393_fu_13754_p1 = $signed(tmp_392_reg_14743);

assign tmp_395_fu_13757_p1 = $signed(tmp_394_reg_14748);

assign tmp_397_cast_fu_13674_p1 = $signed(tmp_659_reg_14713);

assign tmp_397_fu_13760_p1 = $signed(tmp_396_reg_14753);

assign tmp_399_fu_13763_p1 = $signed(tmp_398_reg_14758);

assign tmp_401_fu_13766_p1 = $signed(tmp_400_reg_14784);

assign tmp_403_fu_13769_p1 = $signed(tmp_402_reg_14794);

assign tmp_405_fu_13803_p1 = $signed(tmp_404_reg_14804);

assign tmp_407_cast_fu_13706_p1 = $signed(tmp_660_reg_14733);

assign tmp_407_fu_13806_p1 = $signed(tmp_406_reg_14809);

assign tmp_408_fu_13825_p4 = {{r_V_10_0_27_fu_13820_p2[23:10]}};

assign tmp_409_fu_13835_p1 = $signed(tmp_408_fu_13825_p4);

assign tmp_410_fu_13844_p4 = {{r_V_10_0_28_fu_13839_p2[23:10]}};

assign tmp_411_fu_13854_p1 = $signed(tmp_410_fu_13844_p4);

assign tmp_413_fu_13861_p1 = $signed(tmp_412_reg_14819);

assign tmp_415_fu_13870_p1 = $signed(tmp_414_reg_14834);

assign tmp_417_fu_13873_p1 = $signed(tmp_416_reg_14854);

assign tmp_419_fu_13876_p1 = $signed(tmp_418_reg_14859);

assign tmp_421_fu_13899_p1 = $signed(tmp_420_reg_14869);

assign tmp_423_fu_13939_p1 = $signed(tmp_422_reg_14890);

assign tmp_424_fu_13942_p3 = {{tmp_2_reg_14824}, {5'd0}};

assign tmp_425_cast_fu_13799_p1 = $signed(tmp_661_fu_13789_p4);

assign tmp_426_fu_13976_p1 = $signed(tmp_425_reg_14905);

assign tmp_428_fu_13979_p1 = $signed(tmp_427_reg_14910);

assign tmp_430_fu_14017_p1 = $signed(tmp_429_reg_14950);

assign tmp_431_fu_14048_p4 = {{r_V_10_1_26_fu_14042_p2[24:10]}};

assign tmp_432_fu_14058_p1 = $signed(tmp_431_fu_14048_p4);

assign tmp_434_fu_14062_p1 = $signed(tmp_433_reg_14955);

assign tmp_435_cast_fu_13858_p1 = $signed(tmp_662_reg_14814);

assign tmp_436_fu_14065_p1 = $signed(tmp_435_reg_14960);

assign tmp_445_cast_fu_13895_p1 = $signed(tmp_663_fu_13885_p4);

assign tmp_449_cast_fu_13935_p1 = $signed(tmp_664_fu_13925_p4);

assign tmp_453_cast_fu_13969_p1 = $signed(tmp_665_fu_13959_p4);

assign tmp_455_cast_fu_13973_p1 = $signed(tmp_666_reg_14900);

assign tmp_461_cast_fu_13982_p1 = $signed(tmp_667_reg_14915);

assign tmp_463_cast_fu_13985_p1 = $signed(tmp_668_reg_14920);

assign tmp_465_cast_fu_13988_p1 = $signed(tmp_669_reg_14925);

assign tmp_467_cast_fu_13991_p1 = $signed(tmp_670_reg_14930);

assign tmp_469_cast_fu_14010_p1 = $signed(tmp_671_fu_14000_p4);

assign tmp_471_cast_fu_14014_p1 = $signed(tmp_672_reg_14945);

assign tmp_661_fu_13789_p4 = {{r_V_10_0_24_fu_13783_p2[22:10]}};

assign tmp_663_fu_13885_p4 = {{r_V_10_1_6_fu_13879_p2[16:10]}};

assign tmp_664_fu_13925_p4 = {{r_V_10_1_10_fu_13919_p2[23:10]}};

assign tmp_665_fu_13959_p4 = {{r_V_10_1_13_fu_13953_p2[21:10]}};

assign tmp_671_fu_14000_p4 = {{r_V_10_1_21_fu_13994_p2[21:10]}};

assign tmp_fu_12943_p1 = data_V_read[15:0];

always @ (posedge ap_clk) begin
    p_neg_reg_14778[6:0] <= 7'b0000000;
    p_shl10_reg_14884[0] <= 1'b0;
end

endmodule //dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0
