// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dense_latency_ap_fixed_ap_fixed_18_6_5_3_0_config2_0_0_0_0_0_0_0_0_0_HH_
#define _dense_latency_ap_fixed_ap_fixed_18_6_5_3_0_config2_0_0_0_0_0_0_0_0_0_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct dense_latency_ap_fixed_ap_fixed_18_6_5_3_0_config2_0_0_0_0_0_0_0_0_0 : public sc_module {
    // Port declarations 12
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<36> > data_V_read;
    sc_out< sc_lv<18> > ap_return_0;
    sc_out< sc_lv<18> > ap_return_1;
    sc_out< sc_lv<18> > ap_return_2;
    sc_out< sc_lv<18> > ap_return_3;
    sc_out< sc_lv<18> > ap_return_4;
    sc_out< sc_lv<18> > ap_return_5;
    sc_out< sc_lv<18> > ap_return_6;
    sc_out< sc_lv<18> > ap_return_7;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    dense_latency_ap_fixed_ap_fixed_18_6_5_3_0_config2_0_0_0_0_0_0_0_0_0(sc_module_name name);
    SC_HAS_PROCESS(dense_latency_ap_fixed_ap_fixed_18_6_5_3_0_config2_0_0_0_0_0_0_0_0_0);

    ~dense_latency_ap_fixed_ap_fixed_18_6_5_3_0_config2_0_0_0_0_0_0_0_0_0();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<18> > tmp_3_reg_1517;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<18> > tmp_33_0_1_reg_1522;
    sc_signal< sc_lv<17> > tmp_s_reg_1527;
    sc_signal< sc_lv<18> > tmp_33_0_3_reg_1532;
    sc_signal< sc_lv<9> > tmp_18_reg_1537;
    sc_signal< sc_lv<18> > tmp_33_0_5_reg_1542;
    sc_signal< sc_lv<18> > tmp_33_0_6_reg_1547;
    sc_signal< sc_lv<18> > tmp_33_0_7_reg_1552;
    sc_signal< sc_lv<18> > tmp_33_1_reg_1557;
    sc_signal< sc_lv<18> > tmp_33_1_1_reg_1562;
    sc_signal< sc_lv<18> > tmp_33_1_2_reg_1567;
    sc_signal< sc_lv<18> > tmp_33_1_3_reg_1572;
    sc_signal< sc_lv<18> > tmp_33_1_4_reg_1577;
    sc_signal< sc_lv<16> > tmp_20_reg_1582;
    sc_signal< sc_lv<18> > tmp_33_1_6_reg_1587;
    sc_signal< sc_lv<18> > tmp_33_1_7_reg_1592;
    sc_signal< sc_lv<18> > r_V_10_1_4_fu_92_p1;
    sc_signal< sc_lv<30> > r_V_1_cast_fu_1310_p1;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<18> > r_V_10_1_1_fu_93_p1;
    sc_signal< sc_lv<18> > r_V_10_0_3_fu_95_p1;
    sc_signal< sc_lv<30> > r_V_cast_fu_1187_p1;
    sc_signal< sc_lv<18> > r_V_10_0_7_fu_96_p1;
    sc_signal< sc_lv<18> > r_V_10_0_5_fu_97_p1;
    sc_signal< sc_lv<18> > r_V_10_0_1_fu_98_p1;
    sc_signal< sc_lv<18> > r_V_10_0_6_fu_99_p1;
    sc_signal< sc_lv<18> > r_V_10_1_3_fu_100_p1;
    sc_signal< sc_lv<18> > r_V_10_0_2_fu_101_p1;
    sc_signal< sc_lv<18> > r_V_10_1_fu_102_p1;
    sc_signal< sc_lv<18> > r_V_10_1_2_fu_103_p1;
    sc_signal< sc_lv<18> > r_V_s_fu_104_p1;
    sc_signal< sc_lv<18> > r_V_10_1_6_fu_105_p1;
    sc_signal< sc_lv<18> > r_V_10_1_7_fu_106_p1;
    sc_signal< sc_lv<18> > r_V_10_1_5_fu_107_p1;
    sc_signal< sc_lv<18> > tmp_fu_1174_p1;
    sc_signal< sc_lv<30> > r_V_s_fu_104_p2;
    sc_signal< sc_lv<30> > r_V_10_0_1_fu_98_p2;
    sc_signal< sc_lv<29> > r_V_10_0_2_fu_101_p2;
    sc_signal< sc_lv<30> > r_V_10_0_3_fu_95_p2;
    sc_signal< sc_lv<20> > tmp_22_fu_1237_p3;
    sc_signal< sc_lv<21> > r_V_cast7_fu_1178_p1;
    sc_signal< sc_lv<21> > p_shl_fu_1245_p1;
    sc_signal< sc_lv<21> > r_V_10_0_4_fu_1249_p2;
    sc_signal< sc_lv<30> > r_V_10_0_5_fu_97_p2;
    sc_signal< sc_lv<30> > r_V_10_0_6_fu_99_p2;
    sc_signal< sc_lv<30> > r_V_10_0_7_fu_96_p2;
    sc_signal< sc_lv<18> > tmp_2_fu_1295_p4;
    sc_signal< sc_lv<30> > r_V_10_1_fu_102_p2;
    sc_signal< sc_lv<30> > r_V_10_1_1_fu_93_p2;
    sc_signal< sc_lv<30> > r_V_10_1_2_fu_103_p2;
    sc_signal< sc_lv<30> > r_V_10_1_3_fu_100_p2;
    sc_signal< sc_lv<30> > r_V_10_1_4_fu_92_p2;
    sc_signal< sc_lv<28> > r_V_10_1_5_fu_107_p2;
    sc_signal< sc_lv<30> > r_V_10_1_6_fu_105_p2;
    sc_signal< sc_lv<30> > r_V_10_1_7_fu_106_p2;
    sc_signal< sc_lv<18> > tmp1_fu_1410_p2;
    sc_signal< sc_lv<18> > tmp2_fu_1420_p2;
    sc_signal< sc_lv<18> > tmp_17_fu_1401_p1;
    sc_signal< sc_lv<18> > tmp_19_fu_1404_p1;
    sc_signal< sc_lv<18> > tmp_21_fu_1407_p1;
    sc_signal< sc_lv<18> > tmp3_fu_1449_p2;
    sc_signal< sc_lv<18> > tmp4_fu_1459_p2;
    sc_signal< sc_lv<18> > res_0_V_write_assign_fu_1415_p2;
    sc_signal< sc_lv<18> > acc_1_V_fu_1425_p2;
    sc_signal< sc_lv<18> > acc_2_V_fu_1430_p2;
    sc_signal< sc_lv<18> > acc_3_V_fu_1435_p2;
    sc_signal< sc_lv<18> > acc_4_V_fu_1439_p2;
    sc_signal< sc_lv<18> > acc_5_V_fu_1444_p2;
    sc_signal< sc_lv<18> > acc_6_V_fu_1454_p2;
    sc_signal< sc_lv<18> > acc_7_V_fu_1464_p2;
    sc_signal< sc_logic > ap_ce_reg;
    sc_signal< sc_lv<18> > ap_return_0_int_reg;
    sc_signal< sc_lv<18> > ap_return_1_int_reg;
    sc_signal< sc_lv<18> > ap_return_2_int_reg;
    sc_signal< sc_lv<18> > ap_return_3_int_reg;
    sc_signal< sc_lv<18> > ap_return_4_int_reg;
    sc_signal< sc_lv<18> > ap_return_5_int_reg;
    sc_signal< sc_lv<18> > ap_return_6_int_reg;
    sc_signal< sc_lv<18> > ap_return_7_int_reg;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<30> ap_const_lv30_3FFFFB10;
    static const sc_lv<30> ap_const_lv30_1136;
    static const sc_lv<30> ap_const_lv30_3FFFFA66;
    static const sc_lv<30> ap_const_lv30_1320;
    static const sc_lv<30> ap_const_lv30_3FFFF762;
    static const sc_lv<30> ap_const_lv30_12FF;
    static const sc_lv<30> ap_const_lv30_1077;
    static const sc_lv<30> ap_const_lv30_3FFFFA01;
    static const sc_lv<29> ap_const_lv29_1FFFFCD6;
    static const sc_lv<30> ap_const_lv30_4EA;
    static const sc_lv<30> ap_const_lv30_3FFFF47A;
    static const sc_lv<30> ap_const_lv30_3FFFF857;
    static const sc_lv<30> ap_const_lv30_C02;
    static const sc_lv<30> ap_const_lv30_83B;
    static const sc_lv<28> ap_const_lv28_FFFFEFB;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_23;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<18> ap_const_lv18_3FF9A;
    static const sc_lv<18> ap_const_lv18_3F49D;
    static const sc_lv<18> ap_const_lv18_3F3B6;
    static const sc_lv<18> ap_const_lv18_3F4DA;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_acc_1_V_fu_1425_p2();
    void thread_acc_2_V_fu_1430_p2();
    void thread_acc_3_V_fu_1435_p2();
    void thread_acc_4_V_fu_1439_p2();
    void thread_acc_5_V_fu_1444_p2();
    void thread_acc_6_V_fu_1454_p2();
    void thread_acc_7_V_fu_1464_p2();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_2();
    void thread_ap_return_3();
    void thread_ap_return_4();
    void thread_ap_return_5();
    void thread_ap_return_6();
    void thread_ap_return_7();
    void thread_p_shl_fu_1245_p1();
    void thread_r_V_10_0_1_fu_98_p1();
    void thread_r_V_10_0_1_fu_98_p2();
    void thread_r_V_10_0_2_fu_101_p1();
    void thread_r_V_10_0_2_fu_101_p2();
    void thread_r_V_10_0_3_fu_95_p1();
    void thread_r_V_10_0_3_fu_95_p2();
    void thread_r_V_10_0_4_fu_1249_p2();
    void thread_r_V_10_0_5_fu_97_p1();
    void thread_r_V_10_0_5_fu_97_p2();
    void thread_r_V_10_0_6_fu_99_p1();
    void thread_r_V_10_0_6_fu_99_p2();
    void thread_r_V_10_0_7_fu_96_p1();
    void thread_r_V_10_0_7_fu_96_p2();
    void thread_r_V_10_1_1_fu_93_p1();
    void thread_r_V_10_1_1_fu_93_p2();
    void thread_r_V_10_1_2_fu_103_p1();
    void thread_r_V_10_1_2_fu_103_p2();
    void thread_r_V_10_1_3_fu_100_p1();
    void thread_r_V_10_1_3_fu_100_p2();
    void thread_r_V_10_1_4_fu_92_p1();
    void thread_r_V_10_1_4_fu_92_p2();
    void thread_r_V_10_1_5_fu_107_p1();
    void thread_r_V_10_1_5_fu_107_p2();
    void thread_r_V_10_1_6_fu_105_p1();
    void thread_r_V_10_1_6_fu_105_p2();
    void thread_r_V_10_1_7_fu_106_p1();
    void thread_r_V_10_1_7_fu_106_p2();
    void thread_r_V_10_1_fu_102_p1();
    void thread_r_V_10_1_fu_102_p2();
    void thread_r_V_1_cast_fu_1310_p1();
    void thread_r_V_cast7_fu_1178_p1();
    void thread_r_V_cast_fu_1187_p1();
    void thread_r_V_s_fu_104_p1();
    void thread_r_V_s_fu_104_p2();
    void thread_res_0_V_write_assign_fu_1415_p2();
    void thread_tmp1_fu_1410_p2();
    void thread_tmp2_fu_1420_p2();
    void thread_tmp3_fu_1449_p2();
    void thread_tmp4_fu_1459_p2();
    void thread_tmp_17_fu_1401_p1();
    void thread_tmp_19_fu_1404_p1();
    void thread_tmp_21_fu_1407_p1();
    void thread_tmp_22_fu_1237_p3();
    void thread_tmp_2_fu_1295_p4();
    void thread_tmp_fu_1174_p1();
};

}

using namespace ap_rtl;

#endif
